// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// What BanzAI may say about conformance profiles, derived from the single normative source:
//   contracts/production/conformance-profiles.production.json
//
// Two things come from here, and both need the CLOSED set rather than a list of names:
//
//   the profiles BanzAI states           — L0..Ln, exactly as the registry names them
//   the identifiers BanzAI REFUSES       — anything profile-shaped that the registry does not register
//
// The second is why this file exists. Measured before it did: "What is the L7 conformance profile?"
// resolved a confident definition of conformance, so an identifier the protocol never published became
// a real profile through lexical similarity. An engine that cannot enumerate what exists cannot decline
// what does not.
//
// A profile is a technical capability an implementation demonstrates. It is never a certification state,
// an operational status, a regulatory permission or a production approval, and a profile NAME must never
// encode one — see docs/governance/certification-boundary.md.

/// One profile, exactly as the normative registry names it.
pub struct CanonicalProfile {
    /// The profile identifier. A machine token: never translated.
    pub level: &'static str,
    /// The canonical name, from the normative registry. Never translated, never localised.
    pub name: &'static str,
}

#[rustfmt::skip]
pub const CANONICAL_PROFILES: [CanonicalProfile; 5] = [
    CanonicalProfile { level: "L0", name: "Protocol Sandbox" },
    CanonicalProfile { level: "L1", name: "Core Payment Capability" },
    CanonicalProfile { level: "L2", name: "Payment Initiation Capability" },
    CanonicalProfile { level: "L3", name: "Inter-Operator Interoperability" },
    CanonicalProfile { level: "L4", name: "External Interoperability" },
];

/// The canonical name for a profile identifier, or `None` when the registry does not register it.
///
/// Case-insensitive on the IDENTIFIER only. The registry writes "L0"; a normalized query carries "l0",
/// and comparing them literally made every profile look unregistered — measured, that turned seven
/// published facts into refusals while the guard reported success at refusing L7. The NAME is never
/// case-folded: it is canonical text, returned exactly as the registry writes it.
pub fn canonical_name(level: &str) -> Option<&'static str> {
    CANONICAL_PROFILES
        .iter()
        .find(|p| p.level.eq_ignore_ascii_case(level))
        .map(|p| p.name)
}

/// True when `level` is a profile the protocol actually publishes.
pub fn is_registered(level: &str) -> bool {
    canonical_name(level).is_some()
}

/// A profile-shaped token in `nq` that the registry does NOT register, if any.
///
/// Profile-shaped means `l` followed by digits — the form the protocol uses. The check is deliberately
/// exact: an unregistered identifier is never corrected into a registered one, because "L7" is not a
/// misspelling of "L4", it is a question about something that does not exist. Fuzzy-matching canonical
/// identifiers is what would turn that into a confident wrong answer.
pub fn unregistered_profile_token(nq: &str) -> Option<String> {
    nq.split(|c: char| !c.is_alphanumeric())
        .find(|t| {
            let t = t.to_ascii_lowercase();
            t.len() >= 2
                && t.starts_with('l')
                && t[1..].chars().all(|c| c.is_ascii_digit())
                && !is_registered(&t)
        })
        .map(|t| t.to_ascii_lowercase())
}
