//! banzai-query-core (ADR-037, M2.18B.7) — the single Rust authority for the BanzAI Query Core.
//!
//! This crate owns the deterministic query logic that used to live inside `banzai-api-kb`: the
//! embedded canonical corpus + retrieval primitives (this file), and — migrated tier by tier — the
//! normalization, typo recovery, query ontology / intent taxonomy, entity / attribute / alias
//! registries, resolution, relation graph, retrieval + answer planning, factual package, reason codes
//! and coverage decisions. It is pure Rust: deterministic, no `wasm-bindgen`, no HTTP service, no LLM,
//! no network. `banzai-api-kb` depends on this crate for all business logic and owns only the WASM
//! adaptation surface (the `#[wasm_bindgen]` JSON wrappers) that re-exports `banzai_query_core::*`.
//!
//! The retrieval foundation below is a faithful, byte-parity port of
//! `services/banzai-api/src/knowledge.js`'s `normalize`, `scoreEntry` and `retrieveTopK`, over the
//! embedded entry keyword index (`entries-index.json`, generated from `ENTRIES`). Deterministic; no
//! LLM, no network. Native build powers the parity tests; the Node WASM build (in `banzai-api-kb`) is
//! loaded synchronously by the live service.

use serde::Deserialize;
use std::sync::OnceLock;
use unicode_normalization::UnicodeNormalization;

// ── The Query Core modules (M2.18B.7) — the single Rust authority for understanding, routing and
// grounding a question. Migrated verbatim from banzai-api-kb; banzai-api-kb re-exports them and owns
// only the WASM adaptation surface. Ordering is alphabetical; the dependency graph is internal. ──
pub mod answerplan;
pub mod artifact;
pub mod attribute;
pub mod boundary;
pub mod catalogue;
pub mod concept;
pub mod context;
pub mod coverage;
pub mod diagnose;
pub mod disposition;
pub mod docref;
pub mod factcheck;
pub mod factpack;
pub mod fuzzy;
pub mod glossary;
pub mod intent;
pub mod obligations;
pub mod operational;
pub mod prompt;
pub mod queue_policy;
pub mod reason;
pub mod relation;
pub mod resolve;
pub mod retrieval;
pub mod route;
pub mod scenarios;
pub mod schemacheck;
pub mod source_policy;
pub mod synth;
pub mod taskcheck;
pub mod tasked;
pub mod taxonomy;
pub mod terminal;
pub mod toolplan;
pub mod validate;

/// The entry keyword index, generated from knowledge.js `ENTRIES` (id + keywords).
const ENTRIES_JSON: &str = include_str!("entries-index.json");

#[derive(Deserialize)]
struct Entry {
    id: String,
    keywords: Vec<String>,
}

fn entries() -> &'static [Entry] {
    static E: OnceLock<Vec<Entry>> = OnceLock::new();
    E.get_or_init(|| serde_json::from_str(ENTRIES_JSON).expect("entries-index.json"))
}

// ── M2.9A (ADR-049) documentary index — real protocol-doc chunks generated by the build-time
// banzai-doc-indexer. Used ONLY to ENRICH the grounded Qwen context with real doc excerpts; it never
// changes routing and the curated entries remain the primary grounding/fallback. ──

/// The documentary index (generated by `banzai-doc-indexer`; excludes all secrets/keys/infra).
const DOC_INDEX_JSON: &str = include_str!("doc-index.json");

#[derive(Deserialize)]
pub struct DocChunk {
    pub path: String,
    pub title: String,
    pub section: String,
    pub anchor: String,
    pub source_type: String,
    #[serde(default)]
    pub tags: Vec<String>,
    pub chunk: String,
    #[serde(default)]
    pub operator_facing_flag: bool,
}

pub fn doc_chunks() -> &'static [DocChunk] {
    static D: OnceLock<Vec<DocChunk>> = OnceLock::new();
    D.get_or_init(|| serde_json::from_str(DOC_INDEX_JSON).unwrap_or_default())
}

/// Score a documentary chunk against the normalized query terms: count distinct query terms (len>2)
/// present in the chunk's normalized (title+section+tags+text), + a small operator-facing boost when
/// the query itself is operator-oriented. Deterministic; no LLM.
fn score_doc_chunk(terms: &[&str], operator_query: bool, c: &DocChunk) -> i64 {
    let hay = normalize(&format!(
        "{} {} {} {}",
        c.title,
        c.section,
        c.tags.join(" "),
        c.chunk
    ));
    let mut score = 0i64;
    for t in terms {
        if t.len() > 2 && hay.contains(t) {
            score += 1;
        }
    }
    if operator_query && c.operator_facing_flag && score > 0 {
        score += 1;
    }
    score
}

/// Retrieve the top-k documentary chunks for a query (score ≥ 3), best first, stable for ties.
pub fn retrieve_doc_chunks(query: &str, k: usize) -> Vec<&'static DocChunk> {
    let nq = normalize(query);
    if nq.is_empty() {
        return vec![];
    }
    let terms: Vec<&str> = nq.split(' ').filter(|w| w.len() > 2).collect();
    if terms.is_empty() {
        return vec![];
    }
    let operator_query = terms.iter().any(|t| {
        matches!(
            *t,
            "operador"
                | "operator"
                | "onboarding"
                | "federar"
                | "federacao"
                | "conformidade"
                | "conformance"
                | "manifest"
                | "manifesto"
                | "evidencia"
                | "evidence"
                | "trust"
                | "implementar"
                | "comeco"
                | "comecar"
        )
    });
    let mut kept: Vec<(usize, i64, &'static DocChunk)> = doc_chunks()
        .iter()
        .enumerate()
        .map(|(i, c)| (i, score_doc_chunk(&terms, operator_query, c), c))
        .filter(|x| x.1 >= 3)
        .collect();
    kept.sort_by_key(|x| (std::cmp::Reverse(x.1), x.0));
    kept.into_iter().take(k.max(1)).map(|x| x.2).collect()
}

// ── M2.13B PR2 — repository-wide index (banza + banzai), generated by `banzai-repo-indexer`. Used to
// ENRICH the grounded local answer with real, citable repo sources (code, docs, guards, license,
// website, Operador Zero, reports). Additive: routing (incl. the action boundary) is unchanged and the
// curated entries remain the primary grounding/fallback. The index is secret-free (proven by the
// indexer's safety artifact + make banzai-repo-knowledge-safety-check). ──

const REPO_INDEX_JSON: &str = include_str!("repoindex/banzai-repo-index.json");
const REPO_INDEX_MANIFEST_JSON: &str = include_str!("repoindex/banzai-repo-index-manifest.json");

/// One repo-wide chunk (subset of the indexer's record needed for retrieval + citation). Some fields
/// are read only across the WASM serialization boundary (citation display), so they are `dead_code` on
/// the native build used by the parity tests.
#[derive(Deserialize)]
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
pub struct RepoChunk {
    pub repo: String,
    pub path: String,
    pub file_name: String,
    pub source_category: String,
    pub title: String,
    #[serde(default)]
    pub heading: String,
    #[serde(default)]
    pub symbol_name: String,
    #[serde(default)]
    pub language: String,
    #[serde(default)]
    pub line_start: usize,
    #[serde(default)]
    pub line_end: usize,
    pub content: String,
    #[serde(default)]
    pub normative_weight: u8,
    #[serde(default)]
    pub implementation_weight: u8,
}

pub fn repo_chunks() -> &'static [RepoChunk] {
    static R: OnceLock<Vec<RepoChunk>> = OnceLock::new();
    R.get_or_init(|| serde_json::from_str(REPO_INDEX_JSON).unwrap_or_default())
}

/// The raw repo-index manifest JSON (counts, commits, index_hash, categories, tool version). The
/// embedded manifest is owned here; the WASM layer only serialises it across the boundary.
pub fn repo_index_manifest() -> &'static str {
    REPO_INDEX_MANIFEST_JSON
}

/// The stable index hash from the manifest (used by the JS cache key so a changed index invalidates
/// every cached model answer). Returns "" if the manifest is unreadable.
pub fn repo_index_hash() -> &'static str {
    static H: OnceLock<String> = OnceLock::new();
    H.get_or_init(|| {
        serde_json::from_str::<serde_json::Value>(REPO_INDEX_MANIFEST_JSON)
            .ok()
            .and_then(|v| {
                v.get("index_hash")
                    .and_then(|x| x.as_str())
                    .map(String::from)
            })
            .unwrap_or_default()
    })
}

/// Which categories a query should prefer, inferred from its terms. Empty = all categories.
fn preferred_categories(terms: &[&str]) -> Vec<&'static str> {
    let has = |ws: &[&str]| terms.iter().any(|t| ws.contains(t));
    let mut cats: Vec<&'static str> = Vec::new();
    if has(&["licenca", "license", "licenciamento", "apache", "notice"]) {
        cats.push("legal-license");
    }
    if has(&["guard", "guards", "check", "ci", "workflow", "makefile"]) {
        cats.push("guard-ci");
    }
    if has(&[
        "boundary",
        "fronteira",
        "recusa",
        "seguranca",
        "safety",
        "refuse",
        "proibido",
    ]) {
        cats.push("security-boundary");
    }
    if has(&[
        "operador",
        "operator",
        "zero",
        "kz_demo",
        "subdominio",
        "endpoint",
        "endpoints",
    ]) {
        cats.push("operator-zero");
    }
    if has(&[
        "banzai",
        "retrieval",
        "retrieve",
        "provider",
        "qwen",
        "cache",
        "routing",
        "indexa",
        "indexador",
    ]) {
        cats.push("banzai-runtime");
        cats.push("banzai");
    }
    if has(&[
        "website",
        "rota",
        "rotas",
        "route",
        "middleware",
        "pagina",
        "componente",
    ]) {
        cats.push("website");
    }
    if has(&[
        "adr",
        "rfc",
        "decisao",
        "decisoes",
        "norma",
        "normativo",
        "spec",
        "contrato",
    ]) {
        cats.push("normative");
        cats.push("decision");
    }
    if has(&["relatorio", "report", "estado", "recente"]) {
        cats.push("report");
    }
    if has(&[
        "ficheiro",
        "ficheiros",
        "file",
        "crate",
        "engine",
        "motor",
        "rust",
        "codigo",
        "implementa",
        "implementam",
    ]) {
        cats.push("implementation");
        cats.push("banzai-runtime");
        cats.push("operator-zero");
    }
    cats.sort();
    cats.dedup();
    cats
}

/// Score a repo chunk: distinct query-term hits in (title+heading+symbol+path+content), + a category
/// boost when the query prefers that category, + a small weight nudge. Deterministic; no LLM.
fn score_repo_chunk(terms: &[&str], prefer: &[&str], c: &RepoChunk) -> i64 {
    let hay = normalize(&format!(
        "{} {} {} {} {}",
        c.title, c.heading, c.symbol_name, c.path, c.content
    ));
    let mut score = 0i64;
    for t in terms {
        if t.len() > 2 && hay.contains(t) {
            score += 1;
        }
    }
    if score == 0 {
        return 0;
    }
    if prefer.contains(&c.source_category.as_str()) {
        score += 2;
    }
    score += (c.normative_weight.max(c.implementation_weight)) as i64;
    score
}

/// Retrieve the top-k repo-wide chunks for a query (score ≥ 3), best first, stable for ties. Optional
/// `categories` filter restricts to those source categories (used by source-aware retrieval).
pub fn retrieve_repo_chunks(query: &str, k: usize, categories: &[&str]) -> Vec<&'static RepoChunk> {
    let nq = normalize(query);
    if nq.is_empty() {
        return vec![];
    }
    let terms: Vec<&str> = nq.split(' ').filter(|w| w.len() > 2).collect();
    if terms.is_empty() {
        return vec![];
    }
    let inferred = preferred_categories(&terms);
    let prefer: Vec<&str> = if categories.is_empty() {
        inferred.clone()
    } else {
        categories.to_vec()
    };
    let mut kept: Vec<(usize, i64, &'static RepoChunk)> = repo_chunks()
        .iter()
        .enumerate()
        .filter(|(_, c)| categories.is_empty() || categories.contains(&c.source_category.as_str()))
        .map(|(i, c)| (i, score_repo_chunk(&terms, &prefer, c), c))
        .filter(|x| x.1 >= 3)
        .collect();
    kept.sort_by_key(|x| (std::cmp::Reverse(x.1), x.0));
    kept.into_iter().take(k.max(1)).map(|x| x.2).collect()
}

/// Map a common Cyrillic / Greek HOMOGLYPH to its Latin look-alike (M2.14J adversarial SEC-FIX wave 5).
/// An adversary swaps a Latin letter for a visually identical Cyrillic/Greek one ("сertifica" with a
/// Cyrillic 'с', "trаnsfere" with a Cyrillic 'а') to slip a command past the boundary detectors. These
/// scripts never appear in a legitimate PT/EN protocol query, so folding the confusables to Latin is
/// safe. Input is already lowercased.
fn fold_homoglyph(c: char) -> char {
    match c {
        // Cyrillic → Latin
        '\u{0430}' => 'a', // а
        '\u{0435}' => 'e', // е
        '\u{043e}' => 'o', // о
        '\u{0440}' => 'p', // р
        '\u{0441}' => 'c', // с
        '\u{0443}' => 'y', // у
        '\u{0445}' => 'x', // х
        '\u{0456}' => 'i', // і
        '\u{0458}' => 'j', // ј
        '\u{0455}' => 's', // ѕ
        '\u{043a}' => 'k', // к
        '\u{043c}' => 'm', // м (look-alike in some fonts)
        '\u{0432}' => 'b', // в
        '\u{043d}' => 'h', // н
        '\u{0442}' => 't', // т
        // Greek → Latin
        '\u{03bf}' => 'o', // ο
        '\u{03b1}' => 'a', // α
        '\u{03b5}' => 'e', // ε
        '\u{03c1}' => 'p', // ρ
        '\u{03bd}' => 'v', // ν
        '\u{03b9}' => 'i', // ι
        '\u{03ba}' => 'k', // κ
        '\u{03c4}' => 't', // τ
        '\u{03c5}' => 'y', // υ
        '\u{03c7}' => 'x', // χ
        other => other,
    }
}

/// De-leet a single already-mapped token (M2.14J adversarial SEC-FIX wave 5). A leetspeak command
/// ("ap4ga", "tr4nsfere", "c3rtifica", "rem0ve") hides its verb from the whole-word detectors. Replace
/// a leet digit (0→o,1→i,3→e,4→a,5→s,7→t) ONLY when the token is word-like: ≥2 ascii letters and 1..=2
/// digits, all of which are leet digits. This leaves amounts ("100kz"→3 digits), versions/hashes
/// ("sha256"/"base64"/"ed25519"→non-leet digit or >2 digits) and bare numbers untouched.
fn deleet_token(tok: &str) -> String {
    // A digit-led token ending in a currency suffix is an AMOUNT, never a leet word ("50usd", "100kz",
    // "5000kwanza") — leave it intact so the currency-amount detector still sees it. (Leet words are
    // letter-led except for a leading leet digit like "3xpoe", which does NOT end in a currency suffix.)
    let is_currency = tok.starts_with(|c: char| c.is_ascii_digit())
        && (tok.ends_with("kz")
            || tok.ends_with("kwanza")
            || tok.ends_with("aoa")
            || tok.ends_with("usd")
            || tok.ends_with("eur")
            || tok.ends_with("dolar")
            || tok.ends_with("dolares"));
    if is_currency {
        return tok.to_string();
    }
    let letters = tok.chars().filter(|c| c.is_ascii_alphabetic()).count();
    let digits: Vec<char> = tok.chars().filter(|c| c.is_ascii_digit()).collect();
    let all_leet = digits
        .iter()
        .all(|d| matches!(d, '0' | '1' | '3' | '4' | '5' | '7'));
    // Word-dominant token whose every digit is a leet digit → de-leet (handles multi-leet
    // "c3rt1f1ca"/"tr4nsf3r3"/"ap4ga"/"3xpoe"). letters STRICTLY > digits keeps hashes/versions/amounts
    // (sha256/base64 → non-leet digit; "50kz"/"100kz"/"5000kz" → digits >= the 2 currency letters)
    // untouched, so glued currency amounts survive for the currency-amount detector.
    if letters >= 2 && !digits.is_empty() && letters > digits.len() && all_leet {
        tok.chars()
            .map(|c| match c {
                '0' => 'o',
                '1' => 'i',
                '3' => 'e',
                '4' => 'a',
                '5' => 's',
                '7' => 't',
                other => other,
            })
            .collect()
    } else {
        tok.to_string()
    }
}

/// M2.14J adversarial SEC-FIX (wave 6) — collapse a run of ≥3 identical consecutive ASCII letters to one
/// ("registaaa" → "regista", "apagaaa" → "apaga"): elongation is a deliberate evasion, and no PT/EN word
/// has three identical letters in a row, so this is false-positive-free.
fn collapse_elongation(tok: &str) -> String {
    let chars: Vec<char> = tok.chars().collect();
    let mut out = String::with_capacity(tok.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        let mut j = i + 1;
        while j < chars.len() && chars[j] == c {
            j += 1;
        }
        let run = j - i;
        // a run of ≥3 identical letters collapses to ONE; ≤2 (legit "ss"/"rr"/"ee") is preserved.
        let keep = if c.is_ascii_alphabetic() && run >= 3 {
            1
        } else {
            run
        };
        for _ in 0..keep {
            out.push(c);
        }
        i = j;
    }
    out
}

/// Byte-faithful port of the JS `normalize`, hardened in M2.14J (wave 5) against boundary obfuscation:
/// drop zero-width / soft-hyphen format chars, fold Cyrillic/Greek homoglyphs → lowercase → NFD → strip
/// combining diacritics → replace every char not in `[a-z0-9\s/]` with a space → de-leet word-like
/// tokens → collapse a run of ≥3 single-letter tokens (spelled-out evasion "a p a g a") → collapse
/// whitespace → trim.
pub fn normalize(q: &str) -> String {
    // 1. Drop zero-width / BOM / soft-hyphen format chars (an adversary inserts them mid-word to break
    //    whole-word detection: "ap\u{200b}aga", "trans\u{00ad}fere"); fold homoglyphs to Latin.
    let cleaned: String = q
        .chars()
        .filter(|c| {
            !matches!(
                c,
                '\u{200b}' | '\u{200c}' | '\u{200d}' | '\u{2060}' | '\u{feff}' | '\u{00ad}'
            )
        })
        .collect();
    let lowered: String = cleaned.to_lowercase().chars().map(fold_homoglyph).collect();
    let stripped: String = lowered
        .nfd()
        .filter(|c| !('\u{0300}'..='\u{036f}').contains(c))
        .collect();
    let mapped: String = stripped
        .chars()
        .map(|c| {
            if c.is_ascii_lowercase() || c.is_ascii_digit() || c.is_whitespace() || c == '/' {
                c
            } else {
                ' '
            }
        })
        .collect();
    // De-leet each token, then collapse a maximal run of ≥3 consecutive single-letter tokens into one
    // word (the spelled-out evasion "c e r t i f i c a"). The downstream detectors are substring/prefix
    // based, so a trailing merged article ("a p a g a o trust root" → "apagao trust root") still contains
    // the verb ("apaga") — the collapse only needs to remove the intra-word spaces.
    let toks: Vec<String> = mapped
        .split_whitespace()
        .map(deleet_token)
        .map(|t| collapse_elongation(&t))
        .collect::<Vec<_>>();
    let mut out: Vec<String> = Vec::with_capacity(toks.len());
    let mut i = 0;
    while i < toks.len() {
        let is_single =
            |t: &str| t.chars().count() == 1 && t.chars().all(|c| c.is_ascii_alphabetic());
        if is_single(&toks[i]) {
            let mut j = i;
            while j < toks.len() && is_single(&toks[j]) {
                j += 1;
            }
            if j - i >= 3 {
                out.push(toks[i..j].concat());
                i = j;
                continue;
            }
        }
        out.push(toks[i].clone());
        i += 1;
    }
    out.join(" ")
}

/// True if `w` is a whole space-delimited token in `nq` (never a substring). Mirrors route.rs `has_word`.
fn contains_word(nq: &str, w: &str) -> bool {
    nq.split(' ').any(|t| t == w)
}

/// Grammatical / interrogative stopwords excluded from the per-word content count — they are not
/// evidence of a topic match. Two of them in a long keyword phrase used to reach the threshold and
/// ground off-topic questions ("how does a jet engine work?", "what does HTTP mean?"). PT + EN.
fn is_stopword(w: &str) -> bool {
    matches!(
        w,
        "como"
            | "funciona"
            | "does"
            | "the"
            | "what"
            | "mean"
            | "work"
            | "works"
            | "how"
            | "why"
            | "when"
            | "where"
            | "which"
            | "who"
            | "que"
            | "para"
            | "com"
            | "sem"
            | "dos"
            | "das"
            | "uma"
            | "por"
            | "and"
            | "are"
            | "was"
            | "were"
            | "you"
            | "your"
            | "our"
            | "not"
            | "nao"
            | "sao"
            | "tem"
            | "ser"
            | "this"
            | "that"
            | "with"
            | "from"
            | "into"
            | "tres"
            | "three"
            | "isso"
            | "isto"
            | "aqui"
            | "seu"
            | "sua"
            | "meu"
            | "minha"
    )
}

/// Score an entry against the normalized query. M2.9A hardening (ADR-049) over the original JS port:
///  * a MULTI-word keyword that is a full substring of nq is a phrase hit (word_count + 2);
///  * a SINGLE-word keyword must match as a WHOLE WORD and not be a stopword (kills "brl"/"qr"/"trust"
///    substring collisions) — worth 3 (phrase-equivalent);
///  * otherwise count DISTINCT, non-stopword content words (len>2) present as substrings — deduplicated
///    so a keyword repeating a word ("como … como …", "operator to operator") can't over-count.
fn score_entry(nq: &str, keywords: &[String]) -> i64 {
    let mut score = 0i64;
    for kw in keywords {
        let nk = normalize(kw);
        let words: Vec<&str> = nk.split(' ').filter(|w| !w.is_empty()).collect();
        if words.len() <= 1 {
            let w = words.first().copied().unwrap_or("");
            if w.len() > 2 && !is_stopword(w) && contains_word(nq, w) {
                score = score.max(3);
            }
            continue;
        }
        if nq.contains(&nk) {
            score = score.max(words.len() as i64 + 2); // phrase hit
            continue;
        }
        let mut seen: Vec<&str> = Vec::new();
        let mut hits = 0i64;
        for w in &words {
            // Whole-word (not substring): a keyword word must match a whole query token, never merely
            // be a prefix of a longer one — so grammatical prefix collisions cannot inflate the score.
            if w.len() > 2 && !is_stopword(w) && !seen.contains(w) && contains_word(nq, w) {
                seen.push(w);
                hits += 1;
            }
        }
        score = score.max(hits);
    }
    score
}

/// Byte-faithful port of the JS `retrieveTopK`: returns the ids of the best entries (score >= 2),
/// best first, stable for ties (preserving `ENTRIES` order), at most `max(1, k)`.
pub fn retrieve_topk_ids(question: &str, k: usize) -> Vec<String> {
    let nq = normalize(question);
    if nq.is_empty() {
        return vec![];
    }
    let mut kept: Vec<(usize, i64, &str)> = entries()
        .iter()
        .enumerate()
        .map(|(i, e)| (i, score_entry(&nq, &e.keywords), e.id.as_str()))
        .filter(|x| x.1 >= 2)
        .collect();
    // JS Array.sort is stable; sort by score descending, preserving original order for equal scores.
    kept.sort_by_key(|x| std::cmp::Reverse(x.1));
    kept.into_iter()
        .take(k.max(1))
        .map(|x| x.2.to_string())
        .collect()
}
