//! banzai-query-core (ADR-038, M2.18B.7) — the single Rust authority for the BanzAI Query Core.
//!
//! This crate owns the deterministic query logic that used to live inside `banzai-api-kb`: the
//! embedded canonical corpus + retrieval primitives (this file), and — migrated tier by tier — the
//! normalization, typo recovery, query ontology / intent taxonomy, entity / attribute / alias
//! registries, resolution, relation graph, retrieval + answer planning, factual package, reason codes
//! and coverage decisions. It is pure Rust: deterministic, no `wasm-bindgen`, no HTTP service, no LLM,
//! no network. `banzai-api-kb` depends on this crate for all business logic and owns only the WASM
//! adaptation surface (the `#[wasm_bindgen]` JSON wrappers) that re-exports `banzai_query_core::*`.
//!
//! The retrieval foundation below is a faithful, byte-parity port of
//! `services/banzai-api/src/knowledge.js`'s `normalize`, `scoreEntry` and `retrieveTopK`, over the
//! embedded entry keyword index (`entries-index.json`, generated from the subset of canonical `ENTRIES`
//! explicitly marked `lexicalCandidate: true`). Deterministic; no
//! LLM, no network. Native build powers the parity tests; the Node WASM build (in `banzai-api-kb`) is
//! loaded synchronously by the live service.

use serde::Deserialize;
use std::sync::OnceLock;
use unicode_normalization::UnicodeNormalization;

// ── The Query Core modules (M2.18B.7) — the single Rust authority for understanding, routing and
// grounding a question. Migrated verbatim from banzai-api-kb; banzai-api-kb re-exports them and owns
// only the WASM adaptation surface. Ordering is alphabetical; the dependency graph is internal. ──
pub mod answerplan;
pub mod artifact;
pub mod attribute;
pub mod boundary;
// The generated file keeps `.generated.` in its name so nobody hand-edits it by mistake; the module is
// named for what it is.
#[path = "canonical_profiles.generated.rs"]
pub mod canonical_profiles;
pub mod catalogue;
pub mod concept;
pub mod context;
pub mod coverage;
pub mod diagnose;
pub mod disposition;
pub mod docref;
pub mod factcheck;
pub mod factpack;
pub mod frame;
pub mod fuzzy;
pub mod glossary;
pub mod intent;
pub mod obligations;
pub mod operational;
pub mod prompt;
pub mod queue_policy;
pub mod reason;
pub mod relation;
pub mod resolve;
pub mod retrieval;
pub mod route;
pub mod scenarios;
pub mod schemacheck;
pub mod source_policy;
pub mod synth;
pub mod taskcheck;
pub mod tasked;
#[path = "tasked_item_ids.generated.rs"]
pub mod tasked_item_ids;
pub mod taxonomy;
pub mod terminal;
pub mod toolplan;
pub mod validate;

/// The entry keyword index: the candidate set for `retrieve_topk_ids`, generated by
/// `tools/gen-banzai-entries-index.mjs` from the subset of knowledge.js `ENTRIES` explicitly marked
/// `lexicalCandidate: true` (id + keywords).
///
/// It is a CURATED ALLOWLIST, not a projection of every entry, and membership is NOT `critical`. Most
/// critical entries are deliberately absent and are resolved by the subject, concept, glossary and
/// deterministic paths instead. A reader who counts 27 rows next to 163 entries and concludes the file
/// is stale would be wrong — and the previous wording, "generated from `ENTRIES`", invited exactly that
/// conclusion. Adding an entry here changes which questions this keyword mechanism can win, so it is a
/// deliberate decision recorded at the source, one entry at a time.
const ENTRIES_JSON: &str = include_str!("entries-index.json");

#[derive(Deserialize)]
struct Entry {
    id: String,
    keywords: Vec<String>,
    /// Whether this entry is STABLE KNOWLEDGE the engine may state without a model.
    ///
    /// Declared on the canonical entry and derived into the index. It replaces an inference from the id
    /// prefix — a `def-` name used to mean "settle this model-free", which put semantics in a naming
    /// convention where nobody could see it and where the two cases that matter are inexpressible: a
    /// definition that should NOT be settled, and a settled fact whose id is not a definition.
    ///
    /// Defaults to false so an index generated before this field existed cannot silently promote anything.
    #[serde(default)]
    deterministic: bool,
}

/// Surface forms the RESOLVER recognises: keywords of indexed entries, words of critical-subject
/// aliases, and canonical profile identifiers.
///
/// Typo recovery consults this so it cannot "repair" a word that is already valid vocabulary. Measured
/// before it existed: "What are the BANZA profiles?" had `profiles` rewritten to `profile` as a
/// high-confidence correction, because the fuzzy vocabulary happened to carry the singular and not the
/// plural — and the router only ever sees the corrected form, so a legitimate English plural was
/// normalised out of its own alias while the Portuguese twin matched.
///
/// Deliberately NOT "every word in the documentation": that would freeze the corpus and disable recovery
/// wherever a misspelling coincides with prose. Only vocabulary a resolver actually matches on.
/// Technical terms the engine knows that are too short for the fuzzy vocabulary's five-character floor.
///
/// See the comment at the use site in `registered_surface_forms`. Every member must be resolvable by
/// the glossary on its own — enforced by `tests/known_word_is_not_a_typo.rs`.
const SHORT_DECLARED_TERMS: &[&str] = &[
    "rust", "wasm", "adr", "rfc", "bcj", "qr", "kyc", "kyb", "psp",
];

/// The short declared terms, for the guard that pins each of them to a word the glossary resolves.
pub fn short_declared_terms() -> &'static [&'static str] {
    SHORT_DECLARED_TERMS
}

fn registered_surface_forms() -> &'static std::collections::HashSet<String> {
    static V: OnceLock<std::collections::HashSet<String>> = OnceLock::new();
    V.get_or_init(|| {
        let mut set = std::collections::HashSet::new();
        for e in entries() {
            for k in &e.keywords {
                for w in normalize(k).split(' ') {
                    if w.chars().count() > 2 {
                        set.insert(w.to_string());
                    }
                }
            }
        }
        for w in crate::glossary::critical_subject_words() {
            let n = normalize(w);
            if n.chars().count() > 2 {
                set.insert(n);
            }
        }
        // Declared technical terms SHORTER than the fuzzy vocabulary's floor.
        //
        // Two different questions were being answered by one set: which words a typo may be corrected
        // TO, and which words are KNOWN and must never be corrected FROM. `fuzzy::vocabulary` answers
        // the first, and admits only tokens of five characters or more — a sensible rule for correction
        // targets, which then silently decided that every shorter declared term was an unknown word.
        //
        // `rust` is four characters. It is a concept this engine answers (`def-rust`), and ADR-038 makes
        // it the language of every official BANZA engine. Recovery rewrote it to `trust` — one edit
        // away, five characters, in the target set — at high confidence, in every phrasing, before any
        // router saw the question. Production then answered "não é necessário usar trust para
        // implementar BANZA".
        //
        // This list is deliberately NOT the concept-alias table. That table is matched by SUBSTRING, so
        // an alias `rust` there matches inside `trust` and sends every trust question to ADR-038 —
        // measured, and caught by the golden-answer guard before it shipped. These terms are for
        // known-word protection only: never a correction target, never a concept alias.
        //
        // `short_declared_terms_are_resolvable` pins every member to something the glossary actually
        // resolves, so this cannot drift into a list of words the engine does not know.
        for w in SHORT_DECLARED_TERMS {
            set.insert(normalize(w));
        }
        for p in crate::canonical_profiles::CANONICAL_PROFILES.iter() {
            set.insert(normalize(p.level));
        }
        set
    })
}

/// Whole keywords of indexed entries — COMPLETE surfaces, not the words they are made of.
///
/// `registered_surface_forms()` below splits keywords into words, which is right for typo recovery and
/// wrong for deciding whether a turn names a subject. The two are kept apart deliberately.
pub(crate) fn entry_keyword_surfaces() -> &'static std::collections::HashSet<String> {
    static K: OnceLock<std::collections::HashSet<String>> = OnceLock::new();
    K.get_or_init(|| {
        entries()
            .iter()
            .flat_map(|e| e.keywords.iter())
            .map(|k| normalize(k))
            .collect()
    })
}

/// True when `tok` is a surface form the resolver already recognises, so recovery must leave it alone.
pub fn is_registered_surface_form(tok: &str) -> bool {
    registered_surface_forms().contains(tok)
}

/// Whether the entry with this id is declared stable knowledge answerable without a model.
pub fn entry_is_deterministic(entry_id: &str) -> bool {
    entries()
        .iter()
        .any(|e| e.id == entry_id && e.deterministic)
}

fn entries() -> &'static [Entry] {
    static E: OnceLock<Vec<Entry>> = OnceLock::new();
    E.get_or_init(|| serde_json::from_str(ENTRIES_JSON).expect("entries-index.json"))
}

// ── M2.9A (ADR-036) documentary index — real protocol-doc chunks generated by the build-time
// banzai-doc-indexer. Used ONLY to ENRICH the grounded Qwen context with real doc excerpts; it never
// changes routing and the curated entries remain the primary grounding/fallback. ──

/// The documentary index (generated by `banzai-doc-indexer`; excludes all secrets/keys/infra).
const DOC_INDEX_JSON: &str = include_str!("doc-index.json");

#[derive(Deserialize)]
pub struct DocChunk {
    pub path: String,
    pub title: String,
    pub section: String,
    pub anchor: String,
    pub source_type: String,
    #[serde(default)]
    pub tags: Vec<String>,
    pub chunk: String,
    #[serde(default)]
    pub operator_facing_flag: bool,
}

pub fn doc_chunks() -> &'static [DocChunk] {
    static D: OnceLock<Vec<DocChunk>> = OnceLock::new();
    D.get_or_init(|| serde_json::from_str(DOC_INDEX_JSON).unwrap_or_default())
}

/// Score a documentary chunk against the normalized query terms: count distinct query terms (len>2)
/// present in the chunk's normalized (title+section+tags+text), + a small operator-facing boost when
/// the query itself is operator-oriented. Deterministic; no LLM.
fn score_doc_chunk(terms: &[&str], operator_query: bool, c: &DocChunk) -> i64 {
    let hay = normalize(&format!(
        "{} {} {} {}",
        c.title,
        c.section,
        c.tags.join(" "),
        c.chunk
    ));
    let mut score = 0i64;
    for t in terms {
        if t.len() > 2 && hay.contains(t) {
            score += 1;
        }
    }
    if operator_query && c.operator_facing_flag && score > 0 {
        score += 1;
    }
    score
}

/// Retrieve the top-k documentary chunks for a query (score ≥ 3), best first, stable for ties.
pub fn retrieve_doc_chunks(query: &str, k: usize) -> Vec<&'static DocChunk> {
    let nq = normalize(query);
    if nq.is_empty() {
        return vec![];
    }
    let terms: Vec<&str> = nq.split(' ').filter(|w| w.len() > 2).collect();
    if terms.is_empty() {
        return vec![];
    }
    let operator_query = terms.iter().any(|t| {
        matches!(
            *t,
            "operador"
                | "operator"
                | "onboarding"
                | "federar"
                | "federacao"
                | "conformidade"
                | "conformance"
                | "manifest"
                | "manifesto"
                | "evidencia"
                | "evidence"
                | "trust"
                | "implementar"
                | "comeco"
                | "comecar"
        )
    });
    let mut kept: Vec<(usize, i64, &'static DocChunk)> = doc_chunks()
        .iter()
        .enumerate()
        .map(|(i, c)| (i, score_doc_chunk(&terms, operator_query, c), c))
        .filter(|x| x.1 >= 3)
        .collect();
    kept.sort_by_key(|x| (std::cmp::Reverse(x.1), x.0));
    kept.into_iter().take(k.max(1)).map(|x| x.2).collect()
}

// ── M2.13B PR2 — repository-wide index (banza + banzai), generated by `banzai-repo-indexer`. Used to
// ENRICH the grounded local answer with real, citable repo sources (code, docs, guards, license,
// website, Operador Zero, reports). Additive: routing (incl. the action boundary) is unchanged and the
// curated entries remain the primary grounding/fallback. The index is secret-free (proven by the
// indexer's safety artifact + make banzai-repo-knowledge-safety-check). ──

const REPO_INDEX_JSON: &str = include_str!("repoindex/banzai-repo-index.json");
const REPO_INDEX_MANIFEST_JSON: &str = include_str!("repoindex/banzai-repo-index-manifest.json");

/// One repo-wide chunk (subset of the indexer's record needed for retrieval + citation). Some fields
/// are read only across the WASM serialization boundary (citation display), so they are `dead_code` on
/// the native build used by the parity tests.
#[derive(Deserialize)]
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
pub struct RepoChunk {
    pub repo: String,
    pub path: String,
    pub file_name: String,
    pub source_category: String,
    pub title: String,
    #[serde(default)]
    pub heading: String,
    #[serde(default)]
    pub symbol_name: String,
    #[serde(default)]
    pub language: String,
    #[serde(default)]
    pub line_start: usize,
    #[serde(default)]
    pub line_end: usize,
    pub content: String,
    #[serde(default)]
    pub normative_weight: u8,
    #[serde(default)]
    pub implementation_weight: u8,
}

pub fn repo_chunks() -> &'static [RepoChunk] {
    static R: OnceLock<Vec<RepoChunk>> = OnceLock::new();
    R.get_or_init(|| serde_json::from_str(REPO_INDEX_JSON).unwrap_or_default())
}

/// The raw repo-index manifest JSON (counts, commits, index_hash, categories, tool version). The
/// embedded manifest is owned here; the WASM layer only serialises it across the boundary.
pub fn repo_index_manifest() -> &'static str {
    REPO_INDEX_MANIFEST_JSON
}

/// The stable index hash from the manifest (used by the JS cache key so a changed index invalidates
/// every cached model answer). Returns "" if the manifest is unreadable.
pub fn repo_index_hash() -> &'static str {
    static H: OnceLock<String> = OnceLock::new();
    H.get_or_init(|| {
        serde_json::from_str::<serde_json::Value>(REPO_INDEX_MANIFEST_JSON)
            .ok()
            .and_then(|v| {
                v.get("index_hash")
                    .and_then(|x| x.as_str())
                    .map(String::from)
            })
            .unwrap_or_default()
    })
}

/// Which categories a query should prefer, inferred from its terms. Empty = all categories.
fn preferred_categories(terms: &[&str]) -> Vec<&'static str> {
    let has = |ws: &[&str]| terms.iter().any(|t| ws.contains(t));
    let mut cats: Vec<&'static str> = Vec::new();
    if has(&["licenca", "license", "licenciamento", "apache", "notice"]) {
        cats.push("legal-license");
    }
    if has(&["guard", "guards", "check", "ci", "workflow", "makefile"]) {
        cats.push("guard-ci");
    }
    if has(&[
        "boundary",
        "fronteira",
        "recusa",
        "seguranca",
        "safety",
        "refuse",
        "proibido",
    ]) {
        cats.push("security-boundary");
    }
    if has(&[
        "operador",
        "operator",
        "zero",
        "kz_demo",
        "subdominio",
        "endpoint",
        "endpoints",
    ]) {
        cats.push("operator-zero");
    }
    if has(&[
        "banzai",
        "retrieval",
        "retrieve",
        "provider",
        "qwen",
        "cache",
        "routing",
        "indexa",
        "indexador",
    ]) {
        cats.push("banzai-runtime");
        cats.push("banzai");
    }
    if has(&[
        "website",
        "rota",
        "rotas",
        "route",
        "middleware",
        "pagina",
        "componente",
    ]) {
        cats.push("website");
    }
    if has(&[
        "adr",
        "rfc",
        "decisao",
        "decisoes",
        "norma",
        "normativo",
        "spec",
        "contrato",
    ]) {
        cats.push("normative");
        cats.push("decision");
    }
    if has(&["relatorio", "report", "estado", "recente"]) {
        cats.push("report");
    }
    if has(&[
        "ficheiro",
        "ficheiros",
        "file",
        "crate",
        "engine",
        "motor",
        "rust",
        "codigo",
        "implementa",
        "implementam",
    ]) {
        cats.push("implementation");
        cats.push("banzai-runtime");
        cats.push("operator-zero");
    }
    cats.sort();
    cats.dedup();
    cats
}

/// Score a repo chunk: distinct query-term hits in (title+heading+symbol+path+content), + a category
/// boost when the query prefers that category, + a small weight nudge. Deterministic; no LLM.
fn score_repo_chunk(terms: &[&str], prefer: &[&str], c: &RepoChunk) -> i64 {
    let hay = normalize(&format!(
        "{} {} {} {} {}",
        c.title, c.heading, c.symbol_name, c.path, c.content
    ));
    let mut score = 0i64;
    for t in terms {
        if t.len() > 2 && hay.contains(t) {
            score += 1;
        }
    }
    if score == 0 {
        return 0;
    }
    if prefer.contains(&c.source_category.as_str()) {
        score += 2;
    }
    score += (c.normative_weight.max(c.implementation_weight)) as i64;
    score
}

/// Retrieve the top-k repo-wide chunks for a query (score ≥ 3), best first, stable for ties. Optional
/// `categories` filter restricts to those source categories (used by source-aware retrieval).
pub fn retrieve_repo_chunks(query: &str, k: usize, categories: &[&str]) -> Vec<&'static RepoChunk> {
    let nq = normalize(query);
    if nq.is_empty() {
        return vec![];
    }
    let terms: Vec<&str> = nq.split(' ').filter(|w| w.len() > 2).collect();
    if terms.is_empty() {
        return vec![];
    }
    let inferred = preferred_categories(&terms);
    let prefer: Vec<&str> = if categories.is_empty() {
        inferred.clone()
    } else {
        categories.to_vec()
    };
    let mut kept: Vec<(usize, i64, &'static RepoChunk)> = repo_chunks()
        .iter()
        .enumerate()
        .filter(|(_, c)| categories.is_empty() || categories.contains(&c.source_category.as_str()))
        .map(|(i, c)| (i, score_repo_chunk(&terms, &prefer, c), c))
        .filter(|x| x.1 >= 3)
        .collect();
    kept.sort_by_key(|x| (std::cmp::Reverse(x.1), x.0));
    kept.into_iter().take(k.max(1)).map(|x| x.2).collect()
}

/// Map a common Cyrillic / Greek HOMOGLYPH to its Latin look-alike (M2.14J adversarial SEC-FIX wave 5).
/// An adversary swaps a Latin letter for a visually identical Cyrillic/Greek one ("сertifica" with a
/// Cyrillic 'с', "trаnsfere" with a Cyrillic 'а') to slip a command past the boundary detectors. These
/// scripts never appear in a legitimate PT/EN protocol query, so folding the confusables to Latin is
/// safe. Input is already lowercased.
fn fold_homoglyph(c: char) -> char {
    match c {
        // Cyrillic → Latin
        '\u{0430}' => 'a', // а
        '\u{0435}' => 'e', // е
        '\u{043e}' => 'o', // о
        '\u{0440}' => 'p', // р
        '\u{0441}' => 'c', // с
        '\u{0443}' => 'y', // у
        '\u{0445}' => 'x', // х
        '\u{0456}' => 'i', // і
        '\u{0458}' => 'j', // ј
        '\u{0455}' => 's', // ѕ
        '\u{043a}' => 'k', // к
        '\u{043c}' => 'm', // м (look-alike in some fonts)
        '\u{0432}' => 'b', // в
        '\u{043d}' => 'h', // н
        '\u{0442}' => 't', // т
        // Greek → Latin
        '\u{03bf}' => 'o', // ο
        '\u{03b1}' => 'a', // α
        '\u{03b5}' => 'e', // ε
        '\u{03c1}' => 'p', // ρ
        '\u{03bd}' => 'v', // ν
        '\u{03b9}' => 'i', // ι
        '\u{03ba}' => 'k', // κ
        '\u{03c4}' => 't', // τ
        '\u{03c5}' => 'y', // υ
        '\u{03c7}' => 'x', // χ
        other => other,
    }
}

/// De-leet a single already-mapped token (M2.14J adversarial SEC-FIX wave 5). A leetspeak command
/// ("ap4ga", "tr4nsfere", "c3rtifica", "rem0ve") hides its verb from the whole-word detectors. Replace
/// a leet digit (0→o,1→i,3→e,4→a,5→s,7→t) ONLY when the token is word-like: ≥2 ascii letters and 1..=2
/// digits, all of which are leet digits. This leaves amounts ("100kz"→3 digits), versions/hashes
/// ("sha256"/"base64"/"ed25519"→non-leet digit or >2 digits) and bare numbers untouched.
fn deleet_token(tok: &str) -> String {
    // A digit-led token ending in a currency suffix is an AMOUNT, never a leet word ("50usd", "100kz",
    // "5000kwanza") — leave it intact so the currency-amount detector still sees it. (Leet words are
    // letter-led except for a leading leet digit like "3xpoe", which does NOT end in a currency suffix.)
    let is_currency = tok.starts_with(|c: char| c.is_ascii_digit())
        && (tok.ends_with("kz")
            || tok.ends_with("kwanza")
            || tok.ends_with("aoa")
            || tok.ends_with("usd")
            || tok.ends_with("eur")
            || tok.ends_with("dolar")
            || tok.ends_with("dolares"));
    if is_currency {
        return tok.to_string();
    }
    let letters = tok.chars().filter(|c| c.is_ascii_alphabetic()).count();
    let digits: Vec<char> = tok.chars().filter(|c| c.is_ascii_digit()).collect();
    let all_leet = digits
        .iter()
        .all(|d| matches!(d, '0' | '1' | '3' | '4' | '5' | '7'));
    // Word-dominant token whose every digit is a leet digit → de-leet (handles multi-leet
    // "c3rt1f1ca"/"tr4nsf3r3"/"ap4ga"/"3xpoe"). letters STRICTLY > digits keeps hashes/versions/amounts
    // (sha256/base64 → non-leet digit; "50kz"/"100kz"/"5000kz" → digits >= the 2 currency letters)
    // untouched, so glued currency amounts survive for the currency-amount detector.
    if letters >= 2 && !digits.is_empty() && letters > digits.len() && all_leet {
        tok.chars()
            .map(|c| match c {
                '0' => 'o',
                '1' => 'i',
                '3' => 'e',
                '4' => 'a',
                '5' => 's',
                '7' => 't',
                other => other,
            })
            .collect()
    } else {
        tok.to_string()
    }
}

/// M2.14J adversarial SEC-FIX (wave 6) — collapse a run of ≥3 identical consecutive ASCII letters to one
/// ("registaaa" → "regista", "apagaaa" → "apaga"): elongation is a deliberate evasion, and no PT/EN word
/// has three identical letters in a row, so this is false-positive-free.
fn collapse_elongation(tok: &str) -> String {
    let chars: Vec<char> = tok.chars().collect();
    let mut out = String::with_capacity(tok.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        let mut j = i + 1;
        while j < chars.len() && chars[j] == c {
            j += 1;
        }
        let run = j - i;
        // a run of ≥3 identical letters collapses to ONE; ≤2 (legit "ss"/"rr"/"ee") is preserved.
        let keep = if c.is_ascii_alphabetic() && run >= 3 {
            1
        } else {
            run
        };
        for _ in 0..keep {
            out.push(c);
        }
        i = j;
    }
    out
}

/// Byte-faithful port of the JS `normalize`, hardened in M2.14J (wave 5) against boundary obfuscation:
/// drop zero-width / soft-hyphen format chars, fold Cyrillic/Greek homoglyphs → lowercase → NFD → strip
/// combining diacritics → replace every char not in `[a-z0-9\s/]` with a space → de-leet word-like
/// tokens → collapse a run of ≥3 single-letter tokens (spelled-out evasion "a p a g a") → collapse
/// whitespace → trim.
pub fn normalize(q: &str) -> String {
    // 1. Drop zero-width / BOM / soft-hyphen format chars (an adversary inserts them mid-word to break
    //    whole-word detection: "ap\u{200b}aga", "trans\u{00ad}fere"); fold homoglyphs to Latin.
    let cleaned: String = q
        .chars()
        .filter(|c| {
            !matches!(
                c,
                '\u{200b}' | '\u{200c}' | '\u{200d}' | '\u{2060}' | '\u{feff}' | '\u{00ad}'
            )
        })
        .collect();
    let lowered: String = cleaned.to_lowercase().chars().map(fold_homoglyph).collect();
    let stripped: String = lowered
        .nfd()
        .filter(|c| !('\u{0300}'..='\u{036f}').contains(c))
        .collect();
    let mapped: String = stripped
        .chars()
        .map(|c| {
            if c.is_ascii_lowercase() || c.is_ascii_digit() || c.is_whitespace() || c == '/' {
                c
            } else {
                ' '
            }
        })
        .collect();
    // De-leet each token, then collapse a maximal run of ≥3 consecutive single-letter tokens into one
    // word (the spelled-out evasion "c e r t i f i c a"). The downstream detectors are substring/prefix
    // based, so a trailing merged article ("a p a g a o trust root" → "apagao trust root") still contains
    // the verb ("apaga") — the collapse only needs to remove the intra-word spaces.
    let toks: Vec<String> = mapped
        .split_whitespace()
        .map(deleet_token)
        .map(|t| collapse_elongation(&t))
        .collect::<Vec<_>>();
    let mut out: Vec<String> = Vec::with_capacity(toks.len());
    let mut i = 0;
    while i < toks.len() {
        let is_single =
            |t: &str| t.chars().count() == 1 && t.chars().all(|c| c.is_ascii_alphabetic());
        if is_single(&toks[i]) {
            let mut j = i;
            while j < toks.len() && is_single(&toks[j]) {
                j += 1;
            }
            if j - i >= 3 {
                out.push(toks[i..j].concat());
                i = j;
                continue;
            }
        }
        out.push(toks[i].clone());
        i += 1;
    }
    out.join(" ")
}

/// True if `w` is a whole space-delimited token in `nq` (never a substring). Mirrors route.rs `has_word`.
fn contains_word(nq: &str, w: &str) -> bool {
    nq.split(' ').any(|t| t == w)
}

/// Does `nq` contain this keyword as a run of WHOLE tokens?
///
/// The single-word path has always required a whole-word match, for a reason it states: a keyword word must
/// never merely be a prefix of a longer one. The phrase path did not, and the asymmetry was a live defect.
/// Adding the Portuguese surface form "o que e o banza" to the BANZA identity entry made that phrase a
/// substring of the same question about a DIFFERENT ecosystem identity whose name extends the same stem. It
/// scored as a five-word phrase hit and took that question away from its own entry — the ecosystem-identity
/// collision the kb tests exist to forbid, arriving through the one path that was not checking.
/// The boundary is ALPHABETIC — not whitespace, and not alphanumeric either. Both stricter rules were tried
/// and both moved 313 probes, because the index deliberately carries `"adr 0"` as a numeric-prefix keyword
/// so that "explain ADR-001" reaches the decision index. A digit continuing the match is intended; a LETTER
/// continuing it is the defect. "banza" followed by "m" is a different word; "adr 0" followed by "01" is the
/// same reference.
fn contains_phrase(nq: &str, phrase: &str) -> bool {
    if phrase.is_empty() {
        return false;
    }
    let bytes = nq.as_bytes();
    let alnum = |i: usize| bytes[i].is_ascii_alphabetic();
    let mut from = 0;
    while let Some(rel) = nq[from..].find(phrase) {
        let start = from + rel;
        let end = start + phrase.len();
        let before_ok = start == 0 || !alnum(start - 1);
        let after_ok = end == bytes.len() || !alnum(end);
        if before_ok && after_ok {
            return true;
        }
        from = start + 1;
    }
    false
}

/// Interrogative words, paired across the two languages the engine answers in.
///
/// An interrogative asks *about* a subject; it never *is* one. That makes it worthless as evidence of a
/// topic match, and worse than worthless when a keyword phrase is long enough that the interrogative plus
/// one shared verb reaches the match threshold on its own.
///
/// This is kept as an explicit PT↔EN table rather than a flat list because the flat list is what failed:
/// `who` was excluded and `quem` was not, so "quem controla a Root?" scored `quem` + `controla` = 2 against
/// the keyword "quem controla o banza" and selected the operator-authority definition — a settled claim
/// about operators, chosen for a question about the Root — while the English "who controls the Root?"
/// correctly resolved nothing. One missing word produced both a wrong answer and a PT/EN divergence.
///
/// Parity is asserted by a test, so half of a pair can no longer be added alone.
pub(crate) const INTERROGATIVES: &[(&str, &str)] = &[
    ("quem", "who"),
    ("qual", "which"),
    ("quais", "what"),
    ("onde", "where"),
    ("quando", "when"),
    ("porque", "why"),
    ("quantos", "how"),
    ("quantas", "how"),
    ("quanto", "how"),
    ("como", "how"),
    ("que", "what"),
];

/// Grammatical / interrogative stopwords excluded from the per-word content count — they are not
/// evidence of a topic match. Two of them in a long keyword phrase used to reach the threshold and
/// ground off-topic questions ("how does a jet engine work?", "what does HTTP mean?"). PT + EN.
fn is_stopword(w: &str) -> bool {
    if INTERROGATIVES.iter().any(|(pt, en)| *pt == w || *en == w) {
        return true;
    }
    matches!(
        w,
        "como"
            | "funciona"
            | "does"
            | "the"
            | "what"
            | "mean"
            | "work"
            | "works"
            | "how"
            | "why"
            | "when"
            | "where"
            | "which"
            | "who"
            | "que"
            | "para"
            | "com"
            | "sem"
            | "dos"
            | "das"
            | "uma"
            | "por"
            | "and"
            | "are"
            | "was"
            | "were"
            | "you"
            | "your"
            | "our"
            | "not"
            | "nao"
            | "sao"
            | "tem"
            | "ser"
            | "this"
            | "that"
            | "with"
            | "from"
            | "into"
            | "tres"
            | "three"
            | "isso"
            | "isto"
            | "aqui"
            | "seu"
            | "sua"
            | "meu"
            | "minha"
    )
}

/// Score an entry against the normalized query. M2.9A hardening (ADR-036) over the original JS port:
///  * a MULTI-word keyword that is a full substring of nq is a phrase hit (word_count + 2);
///  * a SINGLE-word keyword must match as a WHOLE WORD and not be a stopword (kills "brl"/"qr"/"trust"
///    substring collisions) — worth 3 (phrase-equivalent);
///  * otherwise count DISTINCT, non-stopword content words (len>2) present as substrings — deduplicated
///    so a keyword repeating a word ("como … como …", "operator to operator") can't over-count.
fn score_entry(nq: &str, keywords: &[String]) -> i64 {
    let mut score = 0i64;
    for kw in keywords {
        let nk = normalize(kw);
        let words: Vec<&str> = nk.split(' ').filter(|w| !w.is_empty()).collect();
        if words.len() <= 1 {
            let w = words.first().copied().unwrap_or("");
            if w.len() > 2 && !is_stopword(w) && contains_word(nq, w) {
                score = score.max(3);
            }
            continue;
        }
        if contains_phrase(nq, &nk) {
            score = score.max(words.len() as i64 + 2); // phrase hit
            continue;
        }
        let mut seen: Vec<&str> = Vec::new();
        let mut hits = 0i64;
        for w in &words {
            // Whole-word (not substring): a keyword word must match a whole query token, never merely
            // be a prefix of a longer one — so grammatical prefix collisions cannot inflate the score.
            if w.len() > 2 && !is_stopword(w) && !seen.contains(w) && contains_word(nq, w) {
                seen.push(w);
                hits += 1;
            }
        }
        score = score.max(hits);
    }
    score
}

/// A fingerprint of the bytes that decide how a query resolves, computed over what this binary EMBEDS.
///
/// The vendored WASM is what production runs; the Rust source is what the tests exercise. When they
/// disagree, every test can be green while the deployed engine behaves like an older revision — and that
/// happened twice while this was being built. Byte-comparing the binary cannot detect it, because
/// `wasm-pack` does not emit a reproducible `.wasm` for the same source: measured, the generated JS
/// wrappers matched a fresh build exactly while the binary differed.
///
/// So the binary carries its own origin. `include_str!` embeds each declared input at compile time, so
/// hashing them here hashes what THIS artifact was built from. A checker reads the input NAMES out of the
/// fingerprint and hashes the same files on disk: equal means this binary came from this source state.
///
/// The manifest below is the point of the design. The first version hashed `route.rs` and the entries
/// index only — and then a change to `fuzzy.rs` altered how queries resolve while the guard still called
/// the artifact fresh. The rule is therefore stated rather than assumed:
///
///   AN INPUT BELONGS HERE WHEN ITS STALE VENDORED FORM CAN CHANGE HOW A QUERY RESOLVES.
///
/// It is deliberately not "every file in the crate": hashing unrelated code would make the guard fire on
/// changes that cannot affect resolution, and a guard that cries wolf gets disabled. It is also not a
/// behavioural sample — this is source-freshness IDENTITY. A comment-only edit invalidates freshness, and
/// that is correct: the artifact genuinely was not built from these bytes.
///
/// FNV-1a, not SHA-256: this detects accidental staleness, not a forged artifact, and the alternative was
/// pulling a crypto dependency into a WASM crate that has three. A checker reimplements it in six lines.
const SEMANTIC_SOURCES: &[(&str, &str)] = &[
    // Routing decision and the candidate set it scores.
    ("route.rs", include_str!("route.rs")),
    ("entries-index.json", include_str!("entries-index.json")),
    // Query understanding: typo recovery, concept and alias resolution, intent, evidence planning. Each of
    // these can change which concept a question resolves to, and therefore which evidence answers it.
    ("fuzzy.rs", include_str!("fuzzy.rs")),
    ("concept.rs", include_str!("concept.rs")),
    ("catalogue.rs", include_str!("catalogue.rs")),
    ("resolve.rs", include_str!("resolve.rs")),
    ("retrieval.rs", include_str!("retrieval.rs")),
    ("intent.rs", include_str!("intent.rs")),
    ("glossary.rs", include_str!("glossary.rs")),
    // Conversational semantics: which slot of a turn is inherited from the turn before it. A stale form of
    // this file resolves a follow-up against the previous SENTENCE instead of the previous SUBJECT.
    ("frame.rs", include_str!("frame.rs")),
    // The CLOSED profile set. A stale copy would let an identifier the registry no longer publishes keep
    // resolving, or a newly published one keep being refused — both change how a query resolves.
    (
        "canonical_profiles.generated.rs",
        include_str!("canonical_profiles.generated.rs"),
    ),
    // The lexical scorer and its stopword lexicon. Added when a missing PT interrogative was found to
    // change which entry a question selects: `is_stopword` and `score_entry` decide resolution just as
    // directly as `route.rs` does, and their absence here was a real hole in the rule above — a stale
    // vendored artifact carrying the old lexicon would have been reported fresh.
    ("lib.rs", include_str!("lib.rs")),
];

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

/// `{ inputs: [{name, hash}], combined, entries_count }` — the semantic source state this binary embeds.
///
/// The names travel with the hashes so a checker needs no second copy of the list: adding an input here
/// extends the check automatically, which is the whole reason the first version's two hardcoded fields
/// were the wrong shape.
pub fn engine_source_fingerprint() -> String {
    let mut inputs = String::new();
    let mut combined: u64 = 0xcbf2_9ce4_8422_2325;
    for (name, body) in SEMANTIC_SOURCES {
        let h = fnv1a64(body.as_bytes());
        if !inputs.is_empty() {
            inputs.push(',');
        }
        inputs.push_str(&format!("{{\"name\":\"{name}\",\"hash\":\"{h:016x}\"}}"));
        combined = fnv1a64(format!("{combined:016x}{name}{h:016x}").as_bytes());
    }
    format!(
        "{{\"inputs\":[{inputs}],\"combined\":\"{combined:016x}\",\"entries_count\":{}}}",
        entries().len()
    )
}

/// Whether a matched entry's keyword accounts for most of the query — i.e. the question IS that
/// definition rather than merely containing its words.
///
/// Coverage, not score: a keyword hit tells us the words are present, which is exactly the signal that
/// misleads. "quem controla os operadores" is covered ~fully by its keyword; "o que faz o banzai quando
/// um operador autoriza um pagamento" is not, because the keyword is a fragment of a longer, different
/// question. Measured on normalized character length so it needs no tokenizer and cannot disagree with
/// `normalize`.
pub fn keyword_is_the_question(nq: &str, entry_id: &str) -> bool {
    // Two thirds: enough to admit a natural leading/trailing word ("afinal, quem controla os
    // operadores?") while rejecting a keyword embedded in a question about something else.
    const MIN_COVERAGE: f64 = 0.66;
    let q_len = nq.chars().count() as f64;
    if q_len == 0.0 {
        return false;
    }
    entries()
        .iter()
        .filter(|e| e.id == entry_id)
        .flat_map(|e| e.keywords.iter())
        .any(|k| {
            let nk = normalize(k);
            !nk.is_empty()
                && nq.contains(&nk)
                && (nk.chars().count() as f64) / q_len >= MIN_COVERAGE
        })
}

/// Byte-faithful port of the JS `retrieveTopK`: returns the ids of the best entries (score >= 2),
/// best first, stable for ties (preserving `ENTRIES` order), at most `max(1, k)`.
pub fn retrieve_topk_ids(question: &str, k: usize) -> Vec<String> {
    let nq = normalize(question);
    if nq.is_empty() {
        return vec![];
    }
    let mut kept: Vec<(usize, i64, &str)> = entries()
        .iter()
        .enumerate()
        .map(|(i, e)| (i, score_entry(&nq, &e.keywords), e.id.as_str()))
        .filter(|x| x.1 >= 2)
        .collect();
    // JS Array.sort is stable; sort by score descending, preserving original order for equal scores.
    kept.sort_by_key(|x| std::cmp::Reverse(x.1));
    kept.into_iter()
        .take(k.max(1))
        .map(|x| x.2.to_string())
        .collect()
}
