// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// The canonical profile vocabulary, derived from the single normative source:
//   contracts/production/conformance-profiles.production.json
//
// The website carries its own copy because its Docker build context is `website/` alone and does not
// contain `contracts/`. It is derived, not authored: `make profile-vocabulary-check` compares it
// byte-for-byte against a fresh generation.
//
// A profile is a technical capability an implementation demonstrates. It is never a certification
// state, an operational status, a regulatory permission or a production approval, and a profile NAME
// must never encode one — see docs/governance/certification-boundary.md.

export type CanonicalProfile = {
  /** The profile identifier. A machine token: never translated. */
  level: string;
  /** The canonical name, from the normative registry. Never translated, never localised. */
  name: string;
};

export const CANONICAL_PROFILES: readonly CanonicalProfile[] = [
  { level: "L0", name: "Protocol Sandbox" },
  { level: "L1", name: "Core Payment Capability" },
  { level: "L2", name: "Payment Initiation Capability" },
  { level: "L3", name: "Inter-Operator Interoperability" },
  { level: "L4", name: "External Interoperability" },
] as const;

/** The canonical name for a profile identifier, or `undefined` if it is not a profile.
 *
 * Unknown identifiers do not resolve by guesswork: an alias is valid only if the registry registers
 * one, and the registry registers none. */
export function canonicalProfileName(level: string): string | undefined {
  return CANONICAL_PROFILES.find((p) => p.level === level)?.name;
}
