// GENERATED by tools/gen-website-decisions-registry.mjs — do not edit by hand.
// The canonical records are decisions/adr/ and decisions/rfc/; this file mirrors what exists there.
export type DecisionType = "ADR" | "RFC";
export interface Decision {
  type: DecisionType;
  id: string;
  slug: string;
  title: string;
  path: string;
  canonicalUrl: string;
  category: string;
  summary: string;
}

export const decisions: Decision[] = [
  {
    "type": "ADR",
    "id": "ADR-001",
    "slug": "adr-001",
    "title": "Open financial protocol: what BANZA is and is not",
    "path": "decisions/adr/ADR-001-open-financial-protocol-what-banza-is-and-is-not.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-001-open-financial-protocol-what-banza-is-and-is-not.md",
    "category": "Identidade e camadas",
    "summary": "BANZA is defined as an open financial protocol: a technology-neutral specification of protocol-level models for financial interoperability, published under Apache 2.0 at github.com/banza-protocol/banza."
  },
  {
    "type": "ADR",
    "id": "ADR-002",
    "slug": "adr-002",
    "title": "Ecosystem naming: BANZA, BanzAI and operators",
    "path": "decisions/adr/ADR-002-ecosystem-naming-banza-banzai-and-operators.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-002-ecosystem-naming-banza-banzai-and-operators.md",
    "category": "Identidade e camadas",
    "summary": "Fix the canonical ecosystem names to match the durable roles."
  },
  {
    "type": "ADR",
    "id": "ADR-003",
    "slug": "adr-003",
    "title": "Three institutional layers",
    "path": "decisions/adr/ADR-003-three-institutional-layers.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-003-three-institutional-layers.md",
    "category": "Identidade e camadas",
    "summary": "BANZA has, until now, been described mostly as \"the open protocol\" plus a growing set of subsystems (conformance, trust, BanzAI, Operador Zero). As the project approaches its v1.0 launch it must present a single, canonical institutional arc"
  },
  {
    "type": "ADR",
    "id": "ADR-004",
    "slug": "adr-004",
    "title": "Technical certification is not scheme admission and not regulatory authorisation",
    "path": "decisions/adr/ADR-004-technical-certification-is-not-scheme-admission-and-not-regu.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-004-technical-certification-is-not-scheme-admission-and-not-regu.md",
    "category": "Identidade e camadas",
    "summary": "ADR-003 fixes the three-layer institutional architecture and ADR-006 names Banzami as the designated operator of the first scheme. The single most dangerous ambiguity that remains is the collapse of three distinct determinations into one pe"
  },
  {
    "type": "ADR",
    "id": "ADR-005",
    "slug": "adr-005",
    "title": "Regulatory-state boundary and the real-money activation gate",
    "path": "decisions/adr/ADR-005-regulatory-state-boundary-and-the-real-money-activation-gate.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-005-regulatory-state-boundary-and-the-real-money-activation-gate.md",
    "category": "Identidade e camadas",
    "summary": "ADR-006 records that Banzami's internal state is REGULATORY_AUTHORIZATION_IN_PROGRESS and that every real-money path is fail-closed until formal evidence exists. This ADR makes that boundary precise and enforceable: it fixes exactly what th"
  },
  {
    "type": "ADR",
    "id": "ADR-006",
    "slug": "adr-006",
    "title": "Designated operator scheme",
    "path": "decisions/adr/ADR-006-designated-operator-scheme.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-006-designated-operator-scheme.md",
    "category": "Identidade e camadas",
    "summary": "ADR-044 already names Banzami — Tecnologia e Serviços, Lda. as the creator and initial institutional maintainer/steward of the open protocol (a governance/attribution role). ADR-003 introduces a third institutional layer — the first operati"
  },
  {
    "type": "ADR",
    "id": "ADR-007",
    "slug": "adr-007",
    "title": "Conflict of interest: infrastructure and key separation",
    "path": "decisions/adr/ADR-007-conflict-of-interest-infrastructure-and-key-separation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-007-conflict-of-interest-infrastructure-and-key-separation.md",
    "category": "Identidade e camadas",
    "summary": "ADR-044 names Banzami — Tecnologia e Serviços, Lda. as the creator and initial institutional maintainer of the open protocol, and ADR-006 designates the same company as the operator of the first operational scheme (Layer 3). The creator of "
  },
  {
    "type": "ADR",
    "id": "ADR-008",
    "slug": "adr-008",
    "title": "Protocol infrastructure independent of any operator",
    "path": "decisions/adr/ADR-008-protocol-infrastructure-independent-of-any-operator.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-008-protocol-infrastructure-independent-of-any-operator.md",
    "category": "Identidade e camadas",
    "summary": ""
  },
  {
    "type": "ADR",
    "id": "ADR-009",
    "slug": "adr-009",
    "title": "Normative authority and versioning",
    "path": "decisions/adr/ADR-009-normative-authority-and-versioning.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-009-normative-authority-and-versioning.md",
    "category": "Autoridade e determinismo",
    "summary": "The normative-completeness audit established that the canonical byte form on which every BANZA signature and digest depends is not specified anywhere in the public surface. It exists only as serde_json::to_string() inside engines/banza-trus"
  },
  {
    "type": "ADR",
    "id": "ADR-010",
    "slug": "adr-010",
    "title": "BANZA Canonical JSON (BCJ/1)",
    "path": "decisions/adr/ADR-010-banza-canonical-json-bcj-1.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-010-banza-canonical-json-bcj-1.md",
    "category": "Autoridade e determinismo",
    "summary": "BANZA signs and digests JSON artifacts — the Key Manifest, the BANZA Revocation List, signed protocol metadata, evidence bundles, receipts. Verification requires that two parties derive exactly the same bytes from the same logical document."
  },
  {
    "type": "ADR",
    "id": "ADR-011",
    "slug": "adr-011",
    "title": "Double-entry ledger and monetary precision",
    "path": "decisions/adr/ADR-011-double-entry-ledger-and-monetary-precision.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-011-double-entry-ledger-and-monetary-precision.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Implement double-entry bookkeeping with an immutable, append-only ledger. Represent all monetary amounts as integer minor units."
  },
  {
    "type": "ADR",
    "id": "ADR-012",
    "slug": "adr-012",
    "title": "Account and participant identity",
    "path": "decisions/adr/ADR-012-account-and-participant-identity.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-012-account-and-participant-identity.md",
    "category": "Execução e primitivas financeiras",
    "summary": "BANZA defines a protocol-level account and participant identity model that can be implemented by operators or applications using wallets, accounts, balances or equivalent account systems. BANZA itself is not a wallet, does not operate user "
  },
  {
    "type": "ADR",
    "id": "ADR-013",
    "slug": "adr-013",
    "title": "Provider abstraction",
    "path": "decisions/adr/ADR-013-provider-abstraction.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-013-provider-abstraction.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Every external integration point is expressed as a provider interface defined by the protocol core. Operators implement each interface for the specific providers they use. The protocol core is generic over the interface and depends on no sp"
  },
  {
    "type": "ADR",
    "id": "ADR-014",
    "slug": "adr-014",
    "title": "Payment intent",
    "path": "decisions/adr/ADR-014-payment-intent.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-014-payment-intent.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Introduce PaymentIntent as the canonical payment-initiation primitive. A PaymentIntent is an intent to receive value into a payee wallet. Payment Links, QR codes, and Payment Requests are surfaces (realizations) of a PaymentIntent — the con"
  },
  {
    "type": "ADR",
    "id": "ADR-015",
    "slug": "adr-015",
    "title": "Payment session",
    "path": "decisions/adr/ADR-015-payment-session.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-015-payment-session.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Introduce the Payment Session standard. A Payment Session is a PaymentIntent (ADR-014) presented through one or more interfaces. It introduces no new money object — the PaymentIntent remains the financial object; the session is the rule tha"
  },
  {
    "type": "ADR",
    "id": "ADR-016",
    "slug": "adr-016",
    "title": "QR payments",
    "path": "decisions/adr/ADR-016-qr-payments.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-016-qr-payments.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Implement both QR types in a single qr_codes domain with a shared scan flow."
  },
  {
    "type": "ADR",
    "id": "ADR-017",
    "slug": "adr-017",
    "title": "Payment links",
    "path": "decisions/adr/ADR-017-payment-links.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-017-payment-links.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Implement a Payment Links domain as a first-class primitive."
  },
  {
    "type": "ADR",
    "id": "ADR-018",
    "slug": "adr-018",
    "title": "Payment collections",
    "path": "decisions/adr/ADR-018-payment-collections.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-018-payment-collections.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Operators need to collect one logical amount from multiple payers — split a bill, group contributions, shared invoices, tuition, condominium dues, events, crowdfunding. A 2026-06-28 reference audit found a merchant \"split charge\" being appr"
  },
  {
    "type": "ADR",
    "id": "ADR-019",
    "slug": "adr-019",
    "title": "Wallet accounts",
    "path": "decisions/adr/ADR-019-wallet-accounts.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-019-wallet-accounts.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Introduce one reference-only protocol concept: the Wallet Account."
  },
  {
    "type": "ADR",
    "id": "ADR-020",
    "slug": "adr-020",
    "title": "Wallet payments and the refund source model",
    "path": "decisions/adr/ADR-020-wallet-payments-and-the-refund-source-model.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-020-wallet-payments-and-the-refund-source-model.md",
    "category": "Execução e primitivas financeiras",
    "summary": "### 1. Wallet/account merchant payments are first-class payment objects"
  },
  {
    "type": "ADR",
    "id": "ADR-021",
    "slug": "adr-021",
    "title": "Fees and application settlement",
    "path": "decisions/adr/ADR-021-fees-and-application-settlement.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-021-fees-and-application-settlement.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Introduce three reference-only protocol concepts and two financial primitives. The protocol carries references and structure; it never carries percentages, money math, or commercial rules."
  },
  {
    "type": "ADR",
    "id": "ADR-022",
    "slug": "adr-022",
    "title": "Transaction proof and public verification",
    "path": "decisions/adr/ADR-022-transaction-proof-and-public-verification.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-022-transaction-proof-and-public-verification.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Define a protocol-level, operator-agnostic standard: the TransactionProof. A proof is an immutable, publicly verifiable assertion that a given transaction exists in an operator's ledger, with its real amount, parties and status. Every opera"
  },
  {
    "type": "ADR",
    "id": "ADR-023",
    "slug": "adr-023",
    "title": "Reason codes",
    "path": "decisions/adr/ADR-023-reason-codes.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-023-reason-codes.md",
    "category": "Execução e primitivas financeiras",
    "summary": "records, revocation entries, root revocation, the BRL, and the Open Trust Evaluation check ids) and that three fields remained open string arrays: failed_checks, and reason_codes on the journey receipt and the operation receipt."
  },
  {
    "type": "ADR",
    "id": "ADR-024",
    "slug": "adr-024",
    "title": "Idempotency",
    "path": "decisions/adr/ADR-024-idempotency.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-024-idempotency.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Idempotency is a protocol invariant. Every financial write MUST carry a caller-supplied idempotency_key. Re-submitting the same key MUST return the original result without creating a duplicate effect; the same key submitted with a different"
  },
  {
    "type": "ADR",
    "id": "ADR-025",
    "slug": "adr-025",
    "title": "Environment isolation: sandbox and production",
    "path": "decisions/adr/ADR-025-environment-isolation-sandbox-and-production.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-025-environment-isolation-sandbox-and-production.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Environment isolation is enforced at multiple levels:"
  },
  {
    "type": "ADR",
    "id": "ADR-026",
    "slug": "adr-026",
    "title": "PostgreSQL as protocol state store, not a ledger",
    "path": "decisions/adr/ADR-026-postgresql-as-protocol-state-store-not-a-ledger.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-026-postgresql-as-protocol-state-store-not-a-ledger.md",
    "category": "Execução e primitivas financeiras",
    "summary": "BANZA is an open financial protocol. It serves public, signed protocol artifacts (root manifest, key manifest, operator registry, conformance evidence hashes, revocation list), it indexes its own reference so the native protocol agent (Banz"
  },
  {
    "type": "ADR",
    "id": "ADR-027",
    "slug": "adr-027",
    "title": "Open protocol trust model without a certificate authority",
    "path": "decisions/adr/ADR-027-open-protocol-trust-model-without-a-certificate-authority.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-027-open-protocol-trust-model-without-a-certificate-authority.md",
    "category": "Confiança e chaves",
    "summary": "BANZA is an open financial protocol. Its trust model does not depend on a central authority over operators. The open governance model is recorded in docs/governance/OPEN_PROTOCOL_GOVERNANCE.md and docs/governance/OPEN_PROTOCOL_ARCHITECTURE."
  },
  {
    "type": "ADR",
    "id": "ADR-028",
    "slug": "adr-028",
    "title": "Root authorization: three authorities, threshold two",
    "path": "decisions/adr/ADR-028-root-authorization-three-authorities-threshold-two.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-028-root-authorization-three-authorities-threshold-two.md",
    "category": "Confiança e chaves",
    "summary": "The BANZA Trust Root is the anchor every conforming implementation pins once and uses to verify all subsequent protocol material. Whatever controls it controls the maximum authority in the protocol, so the question \"how many parties must ac"
  },
  {
    "type": "ADR",
    "id": "ADR-029",
    "slug": "adr-029",
    "title": "Private keys never reside on serving infrastructure",
    "path": "decisions/adr/ADR-029-private-keys-never-reside-on-serving-infrastructure.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-029-private-keys-never-reside-on-serving-infrastructure.md",
    "category": "Confiança e chaves",
    "summary": ""
  },
  {
    "type": "ADR",
    "id": "ADR-030",
    "slug": "adr-030",
    "title": "Anti-rollback for versioned trust material",
    "path": "decisions/adr/ADR-030-anti-rollback-for-versioned-trust-material.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-030-anti-rollback-for-versioned-trust-material.md",
    "category": "Confiança e chaves",
    "summary": "The trust-availability audit measured the published surface against twenty questions. Most were already answered normatively: manifests are cacheable with a stated TTL, the BRL has a six-hour staleness bound, expired material is untrusted, "
  },
  {
    "type": "ADR",
    "id": "ADR-031",
    "slug": "adr-031",
    "title": "Federation trust evaluation without certificates",
    "path": "decisions/adr/ADR-031-federation-trust-evaluation-without-certificates.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-031-federation-trust-evaluation-without-certificates.md",
    "category": "Confiança e chaves",
    "summary": "BANZA is an open financial protocol. Its trust model removes any central authority over operators: the general Open Protocol Trust Model (ADR-027) replaced CA/certificate-based operator trust with signed protocol metadata, operator manifest"
  },
  {
    "type": "ADR",
    "id": "ADR-032",
    "slug": "adr-032",
    "title": "KYC stays operator policy; only trust assertions federate",
    "path": "decisions/adr/ADR-032-kyc-stays-operator-policy-only-trust-assertions-federate.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-032-kyc-stays-operator-policy-only-trust-assertions-federate.md",
    "category": "Confiança e chaves",
    "summary": "KYC is operator policy. The BANZA protocol does not define how an operator verifies identity. Per ADR-001's litmus test, a concept belongs in the protocol only if it touches a shared surface (a wire contract, a manifest capability, a certif"
  },
  {
    "type": "ADR",
    "id": "ADR-033",
    "slug": "adr-033",
    "title": "Operator self-publication and machine-verifiable conformance",
    "path": "decisions/adr/ADR-033-operator-self-publication-and-machine-verifiable-conformance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-033-operator-self-publication-and-machine-verifiable-conformance.md",
    "category": "Conformidade, perfis e registo",
    "summary": "BANZA is an open financial protocol. The canonical decision this ADR implements is:"
  },
  {
    "type": "ADR",
    "id": "ADR-034",
    "slug": "adr-034",
    "title": "Conformance and interoperability certification",
    "path": "decisions/adr/ADR-034-conformance-and-interoperability-certification.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-034-conformance-and-interoperability-certification.md",
    "category": "Conformidade, perfis e registo",
    "summary": "ADR-003 names Layer 2 — BANZA Conformance & Interoperability Certification and ADR-004 fixes what it is (a per-implementation, evidence-based, Rust-decided, reproducible, hash-bound, scoped, time-limited determination that is not a licence,"
  },
  {
    "type": "ADR",
    "id": "ADR-035",
    "slug": "adr-035",
    "title": "Closed certification-state machine",
    "path": "decisions/adr/ADR-035-closed-certification-state-machine.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-035-closed-certification-state-machine.md",
    "category": "Conformidade, perfis e registo",
    "summary": "ADR-034 requires each CertificationRecord to carry a lifecycle — validity, expiration, renewal, suspension, revocation and supersession — and ADR-034 D-064-06 fixes that it must be scoped, time-limited and fail-closed. To be verifiable and "
  },
  {
    "type": "ADR",
    "id": "ADR-036",
    "slug": "adr-036",
    "title": "BANZA Technical Registry",
    "path": "decisions/adr/ADR-036-banza-technical-registry.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-036-banza-technical-registry.md",
    "category": "Conformidade, perfis e registo",
    "summary": "ADR-034 makes an L2 certification a concrete, hash-bound CertificationRecord. Those records need a public, verifiable place to live so that anyone — an operator, an auditor, a regulator, BanzAI — can answer \"is this implementation certified"
  },
  {
    "type": "ADR",
    "id": "ADR-037",
    "slug": "adr-037",
    "title": "Canonical discovery surface",
    "path": "decisions/adr/ADR-037-canonical-discovery-surface.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-037-canonical-discovery-surface.md",
    "category": "Conformidade, perfis e registo",
    "summary": "BANZA's public discovery surface — the machine-readable artefacts an operator publishes so a peer or validator can find and verify it — had drifted into three concurrent, mutually inconsistent naming families for the two central artefacts ("
  },
  {
    "type": "ADR",
    "id": "ADR-038",
    "slug": "adr-038",
    "title": "Endpoint-originated operator validation",
    "path": "decisions/adr/ADR-038-endpoint-originated-operator-validation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-038-endpoint-originated-operator-validation.md",
    "category": "Conformidade, perfis e registo",
    "summary": "BanzAI's validation mode (ADR-041) lets a human validate an implementation of the BANZA protocol through a nine-step journey decided by Rust engines. Until now that journey consumed artifacts that were provided to the interface — bundled ex"
  },
  {
    "type": "ADR",
    "id": "ADR-039",
    "slug": "adr-039",
    "title": "Conformance profiles and capability vocabulary",
    "path": "decisions/adr/ADR-039-conformance-profiles-and-capability-vocabulary.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-039-conformance-profiles-and-capability-vocabulary.md",
    "category": "Conformidade, perfis e registo",
    "summary": "BANZA v1.0 defines five conformance levels (L0–L4). An older per-level model — using operator-type names (Sandbox / Payment / Settlement / Federation / Infrastructure Operator) and an older per-level capability mapping — had been implemente"
  },
  {
    "type": "ADR",
    "id": "ADR-040",
    "slug": "adr-040",
    "title": "Operator onboarding",
    "path": "decisions/adr/ADR-040-operator-onboarding.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-040-operator-onboarding.md",
    "category": "Conformidade, perfis e registo",
    "summary": "ADR-038 established that BanzAI's official validation obtains every artifact from the public endpoints of a selected implementation, resolved from the closed Technical Registry, and that Rust decides every verdict. Until now the only resolv"
  },
  {
    "type": "ADR",
    "id": "ADR-041",
    "slug": "adr-041",
    "title": "Operator Zero: the read-only reference implementation",
    "path": "decisions/adr/ADR-041-operator-zero-the-read-only-reference-implementation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-041-operator-zero-the-read-only-reference-implementation.md",
    "category": "Sistemas de referência e governação",
    "summary": "BANZA specifies a protocol but has never exercised it end to end against a whole operator. The conformance suite validates artifacts in isolation; the BanzAI journey walks an operator through seven steps using per-step examples that do not "
  },
  {
    "type": "ADR",
    "id": "ADR-042",
    "slug": "adr-042",
    "title": "BanzAI: a non-authoritative interface to the protocol",
    "path": "decisions/adr/ADR-042-banzai-a-non-authoritative-interface-to-the-protocol.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-042-banzai-a-non-authoritative-interface-to-the-protocol.md",
    "category": "Sistemas de referência e governação",
    "summary": "BANZA is a specification. Reading a specification well takes expertise most people arriving at a financial interoperability protocol do not have, and the questions they actually need answered — does my implementation conform?, what does thi"
  },
  {
    "type": "ADR",
    "id": "ADR-043",
    "slug": "adr-043",
    "title": "Rust-first official engines",
    "path": "decisions/adr/ADR-043-rust-first-official-engines.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-043-rust-first-official-engines.md",
    "category": "Sistemas de referência e governação",
    "summary": "BANZA is an operator-neutral protocol: external operators may implement their systems in any technology (ADR-001, docs/governance/certification-boundary.md). That neutrality is a permanent protocol invariant and is not in question here."
  },
  {
    "type": "ADR",
    "id": "ADR-044",
    "slug": "adr-044",
    "title": "Licence, notice, trademark and open governance",
    "path": "decisions/adr/ADR-044-licence-notice-trademark-and-open-governance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-044-licence-notice-trademark-and-open-governance.md",
    "category": "Sistemas de referência e governação",
    "summary": "BANZA is an open financial protocol. It was originally created by the startup BANZAMI - TECNOLOGIA E SERVIÇOS, LDA. and is maintained as an open protocol with public governance through the GitHub repository. Until now the repository stated "
  },
  {
    "type": "ADR",
    "id": "ADR-045",
    "slug": "adr-045",
    "title": "Current-only canonical ADR tree",
    "path": "decisions/adr/ADR-045-current-only-canonical-adr-tree.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-045-current-only-canonical-adr-tree.md",
    "category": "Sistemas de referência e governação",
    "summary": "Architecture decision records accumulate. A decision is taken, later amended, later corrected, later superseded — and the conventional practice is to keep every step, marked. After enough steps the directory answers a question nobody asked "
  }
];

export const decisionCategories: string[] = [
  "Identidade e camadas",
  "Autoridade e determinismo",
  "Execução e primitivas financeiras",
  "Confiança e chaves",
  "Conformidade, perfis e registo",
  "Sistemas de referência e governação"
];

export function getDecision(slug: string): Decision | undefined {
  return decisions.find((d) => d.slug === slug);
}
