// Static ADR/RFC metadata derived from decisions/adr/ and decisions/rfc/ (no dynamic runtime source).
// Decision metadata is maintained in this module for the website build context.
export type DecisionType = "ADR" | "RFC";
export type DecisionState = "activo" | "rascunho" | "substituido";
export interface Decision {
  type: DecisionType;
  id: string;
  slug: string;
  title: string;
  status: string;
  state: DecisionState;
  date: string;
  category: string;
  summary: string;
  path: string;
  canonicalUrl: string;
  related: string[];
  normativeLevel: string;
  isDraft: boolean;
  isSuperseded: boolean;
}

export const decisions: Decision[] = [
  {
    "type": "ADR",
    "id": "ADR-059",
    "slug": "adr-059",
    "title": "BANZA Three-Layer Institutional Architecture",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Arquitectura institucional em três camadas — Camada 1 protocolo aberto (neutro, verificável), Camada 2 certificação de conformidade e interoperabilidade (por implementação, baseada em evidência e decidida por Rust) e Camada 3 esquemas operacionais independentes — o primeiro é o Banzami Operational Scheme, com a Banzami como operadora designada do esquema, condicionado ao enquadramento regulatório — com o BanzAI como interface humana transversal, não uma quarta autoridade.",
    "path": "decisions/adr/ADR-059-three-layer-institutional-architecture.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-059-three-layer-institutional-architecture.md",
    "related": [
      "ADR-001",
      "ADR-003",
      "ADR-060",
      "ADR-061",
      "ADR-062",
      "ADR-063"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-060",
    "slug": "adr-060",
    "title": "Banzami Operational Scheme (Designated Operator; BANZA ≠ Banzami)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Operadores",
    "summary": "A Banzami — Tecnologia e Serviços, Lda. é a operadora designada do primeiro scheme operacional sobre o BANZA, condicionada ao enquadramento regulatório aplicável; BANZA ≠ Banzami, a certificação não é exclusiva do scheme e outras entidades legalmente habilitadas podem operar schemes independentes.",
    "path": "decisions/adr/ADR-060-banzami-operational-scheme.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-060-banzami-operational-scheme.md",
    "related": [
      "ADR-003",
      "ADR-043",
      "ADR-059",
      "ADR-061",
      "ADR-062",
      "ADR-063"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-061",
    "slug": "adr-061",
    "title": "Technical Certification ≠ Scheme Admission ≠ Regulatory Authorisation",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "Certificação técnica, admissão a scheme e autorização regulatória são três determinações distintas, com donos distintos; nenhuma implica, propaga-se para ou substitui as outras, e nenhuma superfície as pode apresentar como equivalentes.",
    "path": "decisions/adr/ADR-061-certification-admission-authorisation-separation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-061-certification-admission-authorisation-separation.md",
    "related": [
      "ADR-038",
      "ADR-040",
      "ADR-059",
      "ADR-060",
      "ADR-062"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-062",
    "slug": "adr-062",
    "title": "Regulatory-State Boundary and the RealMoneyActivationGate",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Operadores",
    "summary": "Enquanto não existir evidência formal aplicável, o estado interno da Banzami é REGULATORY_AUTHORIZATION_IN_PROGRESS — não significa autorização concedida nem reconhecimento regulatório; os pagamentos reais permanecem desactivados e qualquer activação de dinheiro real depende de uma única porta de fecho por omissão, decidida por Rust e incontornável.",
    "path": "decisions/adr/ADR-062-regulatory-state-boundary-and-real-money-gate.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-062-regulatory-state-boundary-and-real-money-gate.md",
    "related": [
      "ADR-059",
      "ADR-060",
      "ADR-061",
      "ADR-063"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-063",
    "slug": "adr-063",
    "title": "Conflict of Interest, Infrastructure Separation and Key Separation (Creator == First Operator)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Sendo a criadora do BANZA (Banzami) também a primeira operadora de scheme, o conflito de interesses é controlado estruturalmente: a implementação da Banzami é certificada pelo mesmo caminho público, sem autoprivilégio, com infra-estruturas e chaves criptográficas separadas por domínio e verificáveis por terceiros.",
    "path": "decisions/adr/ADR-063-conflict-of-interest-and-domain-separation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-063-conflict-of-interest-and-domain-separation.md",
    "related": [
      "ADR-028",
      "ADR-037",
      "ADR-038",
      "ADR-042",
      "ADR-059",
      "ADR-060"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-064",
    "slug": "adr-064",
    "title": "BANZA Conformance & Interoperability Certification (Layer 2)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O modelo canónico da certificação técnica (Camada 2): uma CertifiedImplementation (identificada pelo hash do artefacto) é medida contra um InteroperabilityCertificationProfile (público e versionado) e produz um InteroperabilityCertificationRecord decidido por Rust, vinculado a evidência e hash, com âmbito e validade limitados. Certifica uma implementação, nunca uma entidade; não é licença, admissão a scheme nem autorização regulatória.",
    "path": "decisions/adr/ADR-064-conformance-interoperability-certification.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-064-conformance-interoperability-certification.md",
    "related": [
      "ADR-037",
      "ADR-038",
      "ADR-059",
      "ADR-061",
      "ADR-065",
      "ADR-066"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-065",
    "slug": "adr-065",
    "title": "BANZA Technical Registry",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O índice público e verificável por raiz dos artefactos da Camada 2 (perfis, registos de certificação, revogações). Verificável sem conta; o registo técnico (Camada 2) é independente do directório de participantes de um scheme (Camada 3); leituras com fecho por omissão; escrito só por Rust, registos imutáveis; neutro; baseline vazia e honesta (production_certificates = false).",
    "path": "decisions/adr/ADR-065-banza-technical-registry.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-065-banza-technical-registry.md",
    "related": [
      "ADR-038",
      "ADR-059",
      "ADR-060",
      "ADR-061",
      "ADR-064",
      "ADR-066"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-066",
    "slug": "adr-066",
    "title": "Closed Certification-State Machine",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "A máquina de estados fechada da certificação: NOT_CERTIFIED / CERTIFIED / EXPIRED / SUSPENDED / REVOKED / SUPERSEDED, com tabela de transições fixa, REVOKED terminal, renovação como novo registo (nunca extensão), avaliação temporal com fecho por omissão, decidida por Rust sem override humano ou do modelo e sem propagação para admissão ou autorização.",
    "path": "decisions/adr/ADR-066-certification-state-machine.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-066-certification-state-machine.md",
    "related": [
      "ADR-037",
      "ADR-038",
      "ADR-061",
      "ADR-064",
      "ADR-065"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-067",
    "slug": "adr-067",
    "title": "Operador Zero como implementação de referência só de leitura, validada no BanzAI",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O Operador Zero é a implementação canónica de referência, apenas de leitura: expõe identidade, manifest, capabilities, endpoints, metadata, chaves e evidência e não executa simulação, ledger, conformidade, trust, federação nem certificação. Toda a validação humana é iniciada no BanzAI (jornada de 9 etapas), executada pelos motores Rust, com um OperationReceipt por etapa; o Qwen apenas explica. Estado categórico honesto (sem pontuação), certificação NOT_CERTIFIED. Deep links de destino/workflow em lista fechada (seguros contra SSRF).",
    "path": "decisions/adr/ADR-067-operador-zero-read-only-reference-and-banzai-validation-workbench.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-067-operador-zero-read-only-reference-and-banzai-validation-workbench.md",
    "related": [
      "ADR-052",
      "ADR-053",
      "ADR-054",
      "ADR-064",
      "ADR-066"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-057",
    "slug": "adr-057",
    "title": "Current-Only Canonical ADR Tree (Clean-Slate Governance Policy)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Árvore de ADRs current-only: ADRs totalmente substituídos e removidos são apagados da árvore (o histórico Git é o registo); identificadores estáveis, sem renumeração.",
    "path": "decisions/adr/ADR-057-current-only-canonical-adr-tree.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-057-current-only-canonical-adr-tree.md",
    "related": [
      "ADR-001",
      "ADR-002",
      "ADR-005",
      "ADR-037",
      "ADR-043",
      "ADR-038"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-058",
    "slug": "adr-058",
    "title": "Trust Invariant Registry Realignment (Retire the Legacy Trust-Invariant Namespace)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "Realinhamento do registo de invariantes de confiança: retira o namespace legado de invariantes de confiança — já substituído pela Avaliação Aberta de Confiança (INV-OTE-*) e pela avaliação de confiança da federação (INV-FEDEVAL-*) — removendo os identificadores residuais que ficaram nos contratos, specs, motores, grounding e referência. Não reverte nenhuma decisão anterior; remove apenas o resíduo deixado pelas ADR-038/039/040.",
    "path": "decisions/adr/ADR-058-trust-invariant-registry-realignment.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-058-trust-invariant-registry-realignment.md",
    "related": [
      "ADR-037",
      "ADR-038",
      "ADR-039",
      "ADR-040",
      "ADR-042",
      "ADR-057"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-001",
    "slug": "adr-001",
    "title": "BANZA as Open Financial Protocol",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-28",
    "category": "Protocolo",
    "summary": "Separação do BANZA como protocolo financeiro aberto, independente de operadores.",
    "path": "decisions/adr/ADR-001-open-financial-protocol.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-001-open-financial-protocol.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-002",
    "slug": "adr-002",
    "title": "Ecosystem Naming Inversion",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-29",
    "category": "Governação e processo",
    "summary": "Inversão canónica da nomenclatura do ecossistema (BANZA, BanzAI, operadores).",
    "path": "decisions/adr/ADR-002-ecosystem-naming-inversion.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-002-ecosystem-naming-inversion.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-003",
    "slug": "adr-003",
    "title": "Protocol/Operator Separation",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-28",
    "category": "Operadores",
    "summary": "Fronteira entre o núcleo do protocolo e a implementação do operador.",
    "path": "decisions/adr/ADR-003-operator-separation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-003-operator-separation.md",
    "related": [
      "ADR-001",
      "ADR-009"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-005",
    "slug": "adr-005",
    "title": "Protocol-first product development",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-28",
    "category": "Governação e processo",
    "summary": "Desenvolvimento de produto protocolo-primeiro: especificar antes de implementar.",
    "path": "decisions/adr/ADR-005-protocol-first-product-development.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-005-protocol-first-product-development.md",
    "related": [
      "ADR-016"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-006",
    "slug": "adr-006",
    "title": "Double-Entry Ledger and Monetary Precision",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-13",
    "category": "Livro-razão e liquidação",
    "summary": "Livro-razão de partidas dobradas e precisão monetária inteira como base de auditabilidade.",
    "path": "decisions/adr/ADR-006-double-entry-ledger.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-006-double-entry-ledger.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-007",
    "slug": "adr-007",
    "title": "Double-Entry Invariant: Enforcement Strategy",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-28",
    "category": "Protocolo",
    "summary": "Estratégia de imposição do invariante de partidas dobradas.",
    "path": "decisions/adr/ADR-007-double-entry-invariant-enforcement.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-007-double-entry-invariant-enforcement.md",
    "related": [
      "ADR-006"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-008",
    "slug": "adr-008",
    "title": "Markdown-First Content Architecture — docs/reference/en/complete.md as Single Source of Truth",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-19",
    "category": "Governação e processo",
    "summary": "Arquitectura de conteúdo markdown-first; a referência como fonte única de verdade.",
    "path": "decisions/adr/ADR-008-markdown-first-content-architecture.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-008-markdown-first-content-architecture.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-009",
    "slug": "adr-009",
    "title": "Provider Abstraction Model",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-28",
    "category": "Governação e processo",
    "summary": "Modelo de abstracção de fornecedores para integração com sistemas externos.",
    "path": "decisions/adr/ADR-009-provider-abstraction.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-009-provider-abstraction.md",
    "related": [
      "ADR-003"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-010",
    "slug": "adr-010",
    "title": "Account/Participant Identity Model (Account-Based, Not Card-First)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-18",
    "category": "Pagamentos",
    "summary": "Modelo de identidade de conta/participante — baseado em conta, endereçável por QR/@handle, não card-first.",
    "path": "decisions/adr/ADR-010-account-participant-identity.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-010-account-participant-identity.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-011",
    "slug": "adr-011",
    "title": "Idempotency and Rate Limiting with Redis",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-13",
    "category": "Governação e processo",
    "summary": "Idempotência e limitação de taxa nos endpoints de escrita da API pública.",
    "path": "decisions/adr/ADR-011-idempotency-and-rate-limiting.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-011-idempotency-and-rate-limiting.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-012",
    "slug": "adr-012",
    "title": "QR Code Payment System",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-13",
    "category": "Pagamentos",
    "summary": "Sistema de pagamento por código QR, estático e dinâmico.",
    "path": "decisions/adr/ADR-012-qr-payment-system.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-012-qr-payment-system.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-013",
    "slug": "adr-013",
    "title": "Payment Links: Shareable URL Commerce Primitive",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-13",
    "category": "Pagamentos",
    "summary": "Links de pagamento — primitiva de comércio por URL partilhável.",
    "path": "decisions/adr/ADR-013-payment-links.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-013-payment-links.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-014",
    "slug": "adr-014",
    "title": "Payment Intent: the canonical payment-initiation primitive",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-28",
    "category": "Pagamentos",
    "summary": "PaymentIntent — a primitiva canónica de iniciação de pagamento.",
    "path": "decisions/adr/ADR-014-payment-intent.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-014-payment-intent.md",
    "related": [
      "ADR-005",
      "ADR-016"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-015",
    "slug": "adr-015",
    "title": "Payment Session: the unified payment interface",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-30",
    "category": "Pagamentos",
    "summary": "Sessão de pagamento — a interface unificada de pagamento.",
    "path": "decisions/adr/ADR-015-payment-session-unified-payment-interface.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-015-payment-session-unified-payment-interface.md",
    "related": [
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-016",
    "slug": "adr-016",
    "title": "Payment Collections (split / shared / group payments)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-28",
    "category": "Pagamentos",
    "summary": "Cobranças de pagamento — divisão, partilha e pagamentos em grupo.",
    "path": "decisions/adr/ADR-016-payment-collections.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-016-payment-collections.md",
    "related": [
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-017",
    "slug": "adr-017",
    "title": "Wallet-native merchant payments and refund source model",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-18",
    "category": "Pagamentos",
    "summary": "Pagamentos a comerciantes nativos da carteira e modelo de origem de reembolso.",
    "path": "decisions/adr/ADR-017-wallet-native-payment-refund-source-model.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-017-wallet-native-payment-refund-source-model.md",
    "related": [
      "ADR-006",
      "ADR-012",
      "ADR-007"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-018",
    "slug": "adr-018",
    "title": "Merchant-facing refundable-source reference on paid payment events",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-07-04",
    "category": "Pagamentos",
    "summary": "Rascunho: referência de origem reembolsável para comerciantes.",
    "path": "decisions/adr/ADR-018-merchant-refundable-source-reference.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-018-merchant-refundable-source-reference.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-019",
    "slug": "adr-019",
    "title": "Generic Fee & Application-Settlement Architecture",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-29",
    "category": "Livro-razão e liquidação",
    "summary": "Arquitectura genérica de taxas e liquidação de aplicações.",
    "path": "decisions/adr/ADR-019-fee-and-application-settlement-architecture.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-019-fee-and-application-settlement-architecture.md",
    "related": [
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-020",
    "slug": "adr-020",
    "title": "Wallet Accounts (Segregated Accounts within a Wallet)",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-30",
    "category": "Carteiras e identidade",
    "summary": "Contas segregadas dentro de uma carteira.",
    "path": "decisions/adr/ADR-020-wallet-accounts-segregated-accounts.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-020-wallet-accounts-segregated-accounts.md",
    "related": [
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-021",
    "slug": "adr-021",
    "title": "BANZA v1.0 conformance level capability alignment",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-19",
    "category": "Confiança e conformidade",
    "summary": "Alinhamento entre níveis de conformidade e capacidades na v1.0.",
    "path": "decisions/adr/ADR-021-conformance-suite-level-capability-alignment.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-021-conformance-suite-level-capability-alignment.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-023",
    "slug": "adr-023",
    "title": "Transaction Proof Standard",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-29",
    "category": "Pagamentos",
    "summary": "Norma de prova de transacção — a prova é o registo verificável, não o recibo.",
    "path": "decisions/adr/ADR-023-transaction-proof-standard.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-023-transaction-proof-standard.md",
    "related": [
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-024",
    "slug": "adr-024",
    "title": "Public Verification Pages",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07-01",
    "category": "Confiança e conformidade",
    "summary": "Rotas e páginas públicas de verificação do estado do protocolo.",
    "path": "decisions/adr/ADR-024-public-verification-pages.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-024-public-verification-pages.md",
    "related": [
      "ADR-010",
      "ADR-003",
      "ADR-025"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-025",
    "slug": "adr-025",
    "title": "Interactive Financial Documents",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07-01",
    "category": "Governação e processo",
    "summary": "Documentos financeiros interactivos, ancorados em prova verificável.",
    "path": "decisions/adr/ADR-025-interactive-financial-documents.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-025-interactive-financial-documents.md",
    "related": [
      "ADR-003",
      "ADR-005"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-028",
    "slug": "adr-028",
    "title": "Private keys never reside on serving infrastructure",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "As chaves privadas nunca residem na infraestrutura que serve o site.",
    "path": "decisions/adr/ADR-028-keys-never-on-serving-infrastructure.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-028-keys-never-on-serving-infrastructure.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-029",
    "slug": "adr-029",
    "title": "KYC stays operator policy; only Trust Assertions may federate",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-06-28",
    "category": "Confiança e conformidade",
    "summary": "O KYC permanece política do operador; só afirmações de confiança são partilhadas.",
    "path": "decisions/adr/ADR-029-kyc-operator-boundary-and-trust-assertions.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-029-kyc-operator-boundary-and-trust-assertions.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-030",
    "slug": "adr-030",
    "title": "Environment Isolation: Sandbox vs Production",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-05-28",
    "category": "Infraestrutura",
    "summary": "Isolamento de ambientes: sandbox versus produção.",
    "path": "decisions/adr/ADR-030-environment-isolation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-030-environment-isolation.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-031",
    "slug": "adr-031",
    "title": "Canonical verification routes and pre-production behaviour",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "Rotas de verificação canónicas e postura de pré-produção.",
    "path": "decisions/adr/ADR-031-canonical-verification-routes-and-preproduction.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-031-canonical-verification-routes-and-preproduction.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-033",
    "slug": "adr-033",
    "title": "Dedicated infrastructure, independent of any operator",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Operadores",
    "summary": "Infraestrutura dedicada do protocolo, independente de qualquer operador.",
    "path": "decisions/adr/ADR-033-dedicated-independent-infrastructure.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-033-dedicated-independent-infrastructure.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-034",
    "slug": "adr-034",
    "title": "Dedicated PostgreSQL and encrypted off-VM backups",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Infraestrutura",
    "summary": "PostgreSQL dedicado e cópias de segurança encriptadas fora da VM.",
    "path": "decisions/adr/ADR-034-dedicated-postgresql-and-backups.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-034-dedicated-postgresql-and-backups.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-035",
    "slug": "adr-035",
    "title": "Deploy model: Docker Compose, pinned images, secrets outside Git",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Infraestrutura",
    "summary": "Modelo de deploy: Docker Compose, imagens fixadas e gestão de segredos.",
    "path": "decisions/adr/ADR-035-deploy-model.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-035-deploy-model.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-036",
    "slug": "adr-036",
    "title": "DNS and TLS: Cloudflare proxied, Full (strict), Origin Certificate",
    "status": "Proposto",
    "state": "rascunho",
    "date": "2026-07",
    "category": "Infraestrutura",
    "summary": "DNS e TLS: Cloudflare proxied, Full (strict) e certificado de origem.",
    "path": "decisions/adr/ADR-036-dns-and-tls.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-036-dns-and-tls.md",
    "related": [],
    "normativeLevel": "N3",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-037",
    "slug": "adr-037",
    "title": "Rust-first policy for official BANZA and BanzAI engines",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Todos os motores oficiais BANZA/BanzAI são Rust (operadores permanecem neutros quanto a tecnologia); TypeScript é UI/glue.",
    "path": "decisions/adr/ADR-037-rust-first-official-engines.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-037-rust-first-official-engines.md",
    "related": [
      "ADR-003"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-038",
    "slug": "adr-038",
    "title": "Open Protocol Trust Model Without CA",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "Modelo de confiança de protocolo aberto sem autoridade certificadora — metadata assinada, chaves delegadas e revogação.",
    "path": "decisions/adr/ADR-038-open-protocol-trust-model-without-ca.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-038-open-protocol-trust-model-without-ca.md",
    "related": [
      "ADR-039",
      "ADR-040"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-039",
    "slug": "adr-039",
    "title": "Operator Self-Publication and Machine-Verifiable Conformance",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Confiança e conformidade",
    "summary": "O operador auto-publica e assina a sua própria metadata e evidência; a conformidade é verificável por máquina, não concedida.",
    "path": "decisions/adr/ADR-039-operator-self-publication-and-machine-verifiable-conformance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-039-operator-self-publication-and-machine-verifiable-conformance.md",
    "related": [
      "ADR-038",
      "ADR-040"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-040",
    "slug": "adr-040",
    "title": "Federation Trust Evaluation Without Certificates",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Federação",
    "summary": "A federação avalia confiança sem certificados — cada par verifica metadata assinada, evidência e revogação de forma determinística e local.",
    "path": "decisions/adr/ADR-040-federation-trust-evaluation-without-certificates.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-040-federation-trust-evaluation-without-certificates.md",
    "related": [
      "ADR-038",
      "ADR-039"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-041",
    "slug": "adr-041",
    "title": "BanzAI as Native Protocol Agent",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O BanzAI é o agente IA nativo do protocolo — guia, invoca motores e é não normativo; não decide, não aprova nem certifica.",
    "path": "decisions/adr/ADR-041-banzai-native-protocol-agent.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-041-banzai-native-protocol-agent.md",
    "related": [
      "ADR-002"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-042",
    "slug": "adr-042",
    "title": "PostgreSQL as Protocol State Store, not a Financial Ledger",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Infraestrutura",
    "summary": "O PostgreSQL do BANZA guarda estado do protocolo, não valor financeiro — não é livro-razão de pagamentos, carteira, core bancário nem base de operador.",
    "path": "decisions/adr/ADR-042-postgresql-as-protocol-state-store.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-042-postgresql-as-protocol-state-store.md",
    "related": [
      "ADR-006",
      "ADR-007",
      "ADR-033",
      "ADR-034"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-043",
    "slug": "adr-043",
    "title": "License, Notice, Trademark and Open Governance Attribution",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "BANZA mantém-se aberto sob Apache-2.0 canónica; atribuição em NOTICE, marcas em TRADEMARKS, governação aberta em GOVERNANCE; Banzami é criadora original e mantenedora institucional inicial; a governação é aberta hoje via GitHub.",
    "path": "decisions/adr/ADR-043-license-notice-trademark-open-governance-attribution.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-043-license-notice-trademark-open-governance-attribution.md",
    "related": [
      "ADR-001",
      "ADR-002",
      "ADR-005",
      "ADR-041"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-044",
    "slug": "adr-044",
    "title": "BanzAI Local Qwen Inference Runtime",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Inferência de linguagem local on-host (Qwen3-4B-GGUF via llama.cpp), controlada por Rust e benchmark-gated; nada sai do host (external_model_called=false).",
    "path": "decisions/adr/ADR-044-banzai-local-qwen-inference-runtime.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-044-banzai-local-qwen-inference-runtime.md",
    "related": [
      "ADR-041"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-045",
    "slug": "adr-045",
    "title": "BanzAI Local Qwen Latency Tuning & Default Readiness",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Afinação de latência do local_qwen e prontidão do default: prompt compacto em Rust, ≤3 fontes, orçamento de saída inicial.",
    "path": "decisions/adr/ADR-045-banzai-local-qwen-latency-tuning-default-readiness.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-045-banzai-local-qwen-latency-tuning-default-readiness.md",
    "related": [
      "ADR-044"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-046",
    "slug": "adr-046",
    "title": "BanzAI Disable Qwen Reasoning & Prefix Warm-up",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Raciocínio do Qwen desactivado (sem <think>) e aquecimento do prefixo do system prompt para latência estável.",
    "path": "decisions/adr/ADR-046-banzai-disable-qwen-reasoning-prefix-warmup.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-046-banzai-disable-qwen-reasoning-prefix-warmup.md",
    "related": [
      "ADR-044",
      "ADR-045"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-047",
    "slug": "adr-047",
    "title": "BanzAI local_qwen 384-token Default Output Budget",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Orçamento de saída por omissão do local_qwen elevado para 384 tokens; timeout mantém-se em 60 s.",
    "path": "decisions/adr/ADR-047-banzai-local-qwen-384-token-default.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-047-banzai-local-qwen-384-token-default.md",
    "related": [
      "ADR-044",
      "ADR-046"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-048",
    "slug": "adr-048",
    "title": "BanzAI Qwen-first Grounded Routing & Deterministic Fallback",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Encaminhamento Qwen-first para perguntas fundamentadas com fontes suficientes; determinístico para fronteiras críticas, recusas de segurança e ausência de fonte.",
    "path": "decisions/adr/ADR-048-banzai-qwen-first-grounded-routing.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-048-banzai-qwen-first-grounded-routing.md",
    "related": [
      "ADR-041",
      "ADR-044"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-049",
    "slug": "adr-049",
    "title": "BanzAI Protocol Agent Core",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Núcleo do agente do protocolo: intenções operacionais, onboarding, índice documental, jornada guiada do operador e estado de sessão em memória.",
    "path": "decisions/adr/ADR-049-banzai-protocol-agent-core.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-049-banzai-protocol-agent-core.md",
    "related": [
      "ADR-041",
      "ADR-048"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-050",
    "slug": "adr-050",
    "title": "BanzAI Unified Same-Origin Public Interface",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Interface pública única em banza.network/banzai, com o browser a chamar /banzai/ask na mesma origem; subdomínio banzai.banza.network retirado.",
    "path": "decisions/adr/ADR-050-banzai-unified-public-interface.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-050-banzai-unified-public-interface.md",
    "related": [
      "ADR-041",
      "ADR-031"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-051",
    "slug": "adr-051",
    "title": "BanzAI Per-Answer Execution-Path Metadata",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Metadados seguros por resposta indicam o caminho de execução (Qwen local, determinístico, cache, evidência insuficiente, fallback), sem expor prompt nem chaves.",
    "path": "decisions/adr/ADR-051-banzai-per-answer-execution-path-metadata.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-051-banzai-per-answer-execution-path-metadata.md",
    "related": [
      "ADR-044",
      "ADR-048"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-052",
    "slug": "adr-052",
    "title": "Operador Zero: implementação de referência do operador de pagamentos",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O Operador Zero é a implementação canónica de referência de um operador de pagamentos — demonstrativa, sem dinheiro real e sem prestar serviços financeiros; não é um operador real, certificado, aprovado, licenciado ou publicado (simulated=true, production_allowed=false). A ADR-067 reformula esta referência como apenas de leitura: expõe identidade, manifest, capabilities, endpoints, metadata, chaves e evidência, e toda a validação humana é iniciada no BanzAI, a interface humana primária do protocolo.",
    "path": "decisions/adr/ADR-052-operador-zero-reference-payment-operator-simulator.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-052-operador-zero-reference-payment-operator-simulator.md",
    "related": [
      "ADR-003",
      "ADR-053",
      "ADR-067"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-053",
    "slug": "adr-053",
    "title": "Política de demo e exemplo Operator-Zero-Only",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O Operador Zero é o único exemplo/demo oficial em todo o repositório; a carga manual de JSON é um mecanismo avançado, não um exemplo. Mantém a neutralidade e evita exemplos com marcas de operadores.",
    "path": "decisions/adr/ADR-053-operator-zero-only-demo-and-example-policy.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-053-operator-zero-only-demo-and-example-policy.md",
    "related": [
      "ADR-052"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-054",
    "slug": "adr-054",
    "title": "BanzAI como interface primária humano-operador",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "O BanzAI é a interface primária de trabalho entre humanos/operadores e o protocolo BANZA; as regras continuam no protocolo, a verificação nos motores, a prova na evidência e a governança no processo aberto. BanzAI guia; os motores verificam; a evidência prova; a governança decide.",
    "path": "decisions/adr/ADR-054-banzai-primary-human-operator-interface.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-054-banzai-primary-human-operator-interface.md",
    "related": [
      "ADR-041",
      "ADR-050"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-055",
    "slug": "adr-055",
    "title": "Rust-First Grounded Synthesis for BanzAI",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Síntese fundamentada Rust-first: o Rust resolve, planeia, fundamenta e valida a resposta e o modelo local é chamado uma única vez apenas para explicar. Retira a arquitectura de duas passagens e a interpretação por modelo à entrada — o Rust decide, o Qwen explica.",
    "path": "decisions/adr/ADR-055-banzai-rust-first-grounded-synthesis.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-055-banzai-rust-first-grounded-synthesis.md",
    "related": [
      "ADR-037",
      "ADR-041",
      "ADR-044",
      "ADR-049",
      "ADR-054"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "ADR",
    "id": "ADR-056",
    "slug": "adr-056",
    "title": "Definitive Query Core, Canonical Knowledge Coverage and Production Assurance for BanzAI",
    "status": "Aceite",
    "state": "activo",
    "date": "2026-07",
    "category": "Governação e processo",
    "summary": "Núcleo de consulta definitivo, cobertura canónica do conhecimento e garantia de produção do BanzAI: resolução determinística das consultas, cumprimento semântico das tarefas e adequação das fontes, estendendo a síntese fundamentada Rust-first para eliminar falhas de cobertura sem que o modelo decida.",
    "path": "decisions/adr/ADR-056-banzai-definitive-query-core-and-production-assurance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-056-banzai-definitive-query-core-and-production-assurance.md",
    "related": [
      "ADR-037",
      "ADR-044",
      "ADR-049",
      "ADR-054",
      "ADR-055"
    ],
    "normativeLevel": "N3",
    "isDraft": false,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0001",
    "slug": "rfc-0001",
    "title": "Multi-Operator Routing",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Federação",
    "summary": "Proposta: como se decide o encaminhamento de pagamentos entre múltiplos operadores.",
    "path": "decisions/rfc/RFC-0001-multi-operator-routing.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0001-multi-operator-routing.md",
    "related": [],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0002",
    "slug": "rfc-0002",
    "title": "Cross-Operator Settlement",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Livro-razão e liquidação",
    "summary": "Proposta: liquidação quando um pagamento atravessa operadores.",
    "path": "decisions/rfc/RFC-0002-cross-operator-settlement.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0002-cross-operator-settlement.md",
    "related": [
      "RFC-0001"
    ],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0003",
    "slug": "rfc-0003",
    "title": "Wallet Capabilities",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Carteiras e identidade",
    "summary": "Proposta: modelo de capacidades declaráveis das carteiras.",
    "path": "decisions/rfc/RFC-0003-wallet-capabilities.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0003-wallet-capabilities.md",
    "related": [],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0004",
    "slug": "rfc-0004",
    "title": "Provider Capability Negotiation",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Governação e processo",
    "summary": "Proposta: negociação de capacidades de fornecedor no arranque.",
    "path": "decisions/rfc/RFC-0004-provider-capability-negotiation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0004-provider-capability-negotiation.md",
    "related": [
      "RFC-0003"
    ],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0005",
    "slug": "rfc-0005",
    "title": "Operator Discovery",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Federação",
    "summary": "Proposta: mecanismo de descoberta de operadores na rede.",
    "path": "decisions/rfc/RFC-0005-operator-discovery.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0005-operator-discovery.md",
    "related": [
      "RFC-0001",
      "RFC-0004"
    ],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  },
  {
    "type": "RFC",
    "id": "RFC-0006",
    "slug": "rfc-0006",
    "title": "Offline Payment Support",
    "status": "Rascunho",
    "state": "rascunho",
    "date": "2026-05-28",
    "category": "Pagamentos",
    "summary": "Proposta: pagamentos com conectividade intermitente ou ausente.",
    "path": "decisions/rfc/RFC-0006-offline-payment-support.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/rfc/RFC-0006-offline-payment-support.md",
    "related": [
      "RFC-0003"
    ],
    "normativeLevel": "N4",
    "isDraft": true,
    "isSuperseded": false
  }
];


export const decisionCategories: string[] = ["Carteiras e identidade", "Confiança e conformidade", "Federação", "Governação e processo", "Infraestrutura", "Livro-razão e liquidação", "Operadores", "Pagamentos", "Protocolo"];

export function getDecision(slug: string): Decision | undefined {
  return decisions.find((d) => d.slug === slug);
}
