// GENERATED by tools/gen-website-decisions-registry.mjs — do not edit by hand.
// The canonical records are decisions/adr/ and decisions/rfc/; this file mirrors what exists there.
export type DecisionType = "ADR" | "RFC";
export interface Decision {
  type: DecisionType;
  id: string;
  slug: string;
  title: string;
  path: string;
  canonicalUrl: string;
  category: string;
  summary: string;
}

export const decisions: Decision[] = [
  {
    "type": "ADR",
    "id": "ADR-001",
    "slug": "adr-001",
    "title": "Open financial protocol: what BANZA is and is not",
    "path": "decisions/adr/ADR-001-open-financial-protocol-what-banza-is-and-is-not.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-001-open-financial-protocol-what-banza-is-and-is-not.md",
    "category": "Identidade e camadas",
    "summary": "The models beneath any payment system — a double-entry ledger, an account model, a transaction state machine, settlement semantics, a QR payload — are not commercially distinctive. Every operator needs them and every operator builds them ag"
  },
  {
    "type": "ADR",
    "id": "ADR-002",
    "slug": "adr-002",
    "title": "Protocol, implementation and operator separation",
    "path": "decisions/adr/ADR-002-protocol-implementation-and-operator-separation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-002-protocol-implementation-and-operator-separation.md",
    "category": "Identidade e camadas",
    "summary": "Declaring BANZA operator-neutral (ADR-001) does not keep it neutral. Coupling arrives quietly: a function that assumes one country's rails, an enum listing the payment providers that happen to exist today, a default that is only sensible fo"
  },
  {
    "type": "ADR",
    "id": "ADR-003",
    "slug": "adr-003",
    "title": "Protocol-first origination",
    "path": "decisions/adr/ADR-003-protocol-first-origination.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-003-protocol-first-origination.md",
    "category": "Identidade e camadas",
    "summary": "ADR-002 answers the spatial question — does this belong to the protocol or to an operator? It does not answer the temporal one: where is a genuinely new concept allowed to start?"
  },
  {
    "type": "ADR",
    "id": "ADR-004",
    "slug": "adr-004",
    "title": "Three institutional layers",
    "path": "decisions/adr/ADR-004-three-institutional-layers.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-004-three-institutional-layers.md",
    "category": "Identidade e camadas",
    "summary": "BANZA is not only a specification. Around it sit a conformance system that evaluates implementations and an operational scheme that will one day move real money under a regulator. Described as one thing, they are impossible to reason about:"
  },
  {
    "type": "ADR",
    "id": "ADR-005",
    "slug": "adr-005",
    "title": "Certification, admission and authorisation do not propagate",
    "path": "decisions/adr/ADR-005-certification-admission-and-authorisation-do-not-propagate.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-005-certification-admission-and-authorisation-do-not-propagate.md",
    "category": "Identidade e camadas",
    "summary": "Three determinations exist around BANZA, and they look similar enough from outside to be mistaken for stages of one process:"
  },
  {
    "type": "ADR",
    "id": "ADR-006",
    "slug": "adr-006",
    "title": "The designated operator and its conflict of interest",
    "path": "decisions/adr/ADR-006-the-designated-operator-and-its-conflict-of-interest.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-006-the-designated-operator-and-its-conflict-of-interest.md",
    "category": "Identidade e camadas",
    "summary": "The party that designed BANZA also intends to run the first scheme built on it. That is how a protocol gets a first real implementation, and it is a structural conflict of interest: the same party writes the rules, operates the conformance "
  },
  {
    "type": "ADR",
    "id": "ADR-007",
    "slug": "adr-007",
    "title": "Regulatory state and the real-money activation gate",
    "path": "decisions/adr/ADR-007-regulatory-state-and-the-real-money-activation-gate.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-007-regulatory-state-and-the-real-money-activation-gate.md",
    "category": "Identidade e camadas",
    "summary": "The operational scheme (Layer 3) will one day move real money, and until a regulator says so it must not. Between those two states lies a long preparation period, and preparation periods are where two specific failures happen: the project s"
  },
  {
    "type": "ADR",
    "id": "ADR-008",
    "slug": "adr-008",
    "title": "Normative authority and versioning",
    "path": "decisions/adr/ADR-008-normative-authority-and-versioning.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-008-normative-authority-and-versioning.md",
    "category": "Identidade e camadas",
    "summary": "A repository that publishes specifications, contracts, schemas, vectors, decision records, governance documents and a reference implementation has a problem it rarely admits: when two of them disagree, an implementer has no way to know whic"
  },
  {
    "type": "ADR",
    "id": "ADR-009",
    "slug": "adr-009",
    "title": "Licence, trademark and open governance",
    "path": "decisions/adr/ADR-009-licence-trademark-and-open-governance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-009-licence-trademark-and-open-governance.md",
    "category": "Autoridade e determinismo",
    "summary": "An open protocol created by a company faces a pair of opposite misreadings, and both are damaging. If attribution is prominent, the protocol reads as one company's asset with an open-source veneer. If attribution is absent, the origin is ob"
  },
  {
    "type": "ADR",
    "id": "ADR-010",
    "slug": "adr-010",
    "title": "The decision-record tree holds current architecture only",
    "path": "decisions/adr/ADR-010-the-decision-record-tree-holds-current-architecture-only.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-010-the-decision-record-tree-holds-current-architecture-only.md",
    "category": "Autoridade e determinismo",
    "summary": "Decision records accumulate. The usual discipline — never delete, mark the old one superseded, add a record that amends it — produces an archive that is honest about the past and useless for the present. A reader asking \"how does BANZA auth"
  },
  {
    "type": "ADR",
    "id": "ADR-011",
    "slug": "adr-011",
    "title": "BANZA Canonical JSON (BCJ/1)",
    "path": "decisions/adr/ADR-011-banza-canonical-json-bcj-1.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-011-banza-canonical-json-bcj-1.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Every signature, digest and request identity in BANZA is computed over bytes. JSON does not have unique bytes: the same document can be serialised with different key orders, different spacing, different number formats and different escaping"
  },
  {
    "type": "ADR",
    "id": "ADR-012",
    "slug": "adr-012",
    "title": "Double-entry ledger and monetary precision",
    "path": "decisions/adr/ADR-012-double-entry-ledger-and-monetary-precision.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-012-double-entry-ledger-and-monetary-precision.md",
    "category": "Execução e primitivas financeiras",
    "summary": "A payment system's ledger is where errors become permanent. Two failure modes account for most of them, and both are avoidable by construction rather than by care."
  },
  {
    "type": "ADR",
    "id": "ADR-013",
    "slug": "adr-013",
    "title": "The protocol state store is not a ledger",
    "path": "decisions/adr/ADR-013-the-protocol-state-store-is-not-a-ledger.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-013-the-protocol-state-store-is-not-a-ledger.md",
    "category": "Execução e primitivas financeiras",
    "summary": "The protocol serves public signed artifacts — key manifests, registry records, revocation entries, evidence digests — and keeps an audit trail of its own governance events. That needs durable storage, and durable storage inside a financial "
  },
  {
    "type": "ADR",
    "id": "ADR-014",
    "slug": "adr-014",
    "title": "Account and participant identity",
    "path": "decisions/adr/ADR-014-account-and-participant-identity.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-014-account-and-participant-identity.md",
    "category": "Execução e primitivas financeiras",
    "summary": "A payment protocol has to decide what a payment fundamentally is, because everything else follows from it. The dominant model in the industry is card-first: a payment is an authorisation against an instrument issued by a scheme, and account"
  },
  {
    "type": "ADR",
    "id": "ADR-015",
    "slug": "adr-015",
    "title": "Payment initiation: one intent, several surfaces",
    "path": "decisions/adr/ADR-015-payment-initiation-one-intent-several-surfaces.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-015-payment-initiation-one-intent-several-surfaces.md",
    "category": "Execução e primitivas financeiras",
    "summary": "A payee asks to be paid in several ways: a link shared in a message, a printed static QR code on a counter, a dynamic QR generated for one specific amount, a deep link into an application. Each has a different presentation and a different f"
  },
  {
    "type": "ADR",
    "id": "ADR-016",
    "slug": "adr-016",
    "title": "Collections: a composite obligation, never money",
    "path": "decisions/adr/ADR-016-collections-a-composite-obligation-never-money.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-016-collections-a-composite-obligation-never-money.md",
    "category": "Execução e primitivas financeiras",
    "summary": "People pay for things together: a bill split between friends, a shared gift, a group order, a fundraiser with many contributors. Every payment product eventually meets this and the tempting implementation is a container that receives the co"
  },
  {
    "type": "ADR",
    "id": "ADR-017",
    "slug": "adr-017",
    "title": "Wallet accounts: segregation inside a wallet",
    "path": "decisions/adr/ADR-017-wallet-accounts-segregation-inside-a-wallet.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-017-wallet-accounts-segregation-inside-a-wallet.md",
    "category": "Execução e primitivas financeiras",
    "summary": "A wallet holding one balance per currency is enough until a participant needs to keep money apart for a reason. A merchant running a campaign wants that campaign's takings separable. An organisation collecting for a specific purpose needs t"
  },
  {
    "type": "ADR",
    "id": "ADR-018",
    "slug": "adr-018",
    "title": "Wallet payments and the refund source model",
    "path": "decisions/adr/ADR-018-wallet-payments-and-the-refund-source-model.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-018-wallet-payments-and-the-refund-source-model.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Two things a merchant does routinely turn out to depend on the same question. A merchant accepts a payment from a customer's wallet, and later needs to refund it. To refund it, something must identify what is being refunded."
  },
  {
    "type": "ADR",
    "id": "ADR-019",
    "slug": "adr-019",
    "title": "Fees and application settlement",
    "path": "decisions/adr/ADR-019-fees-and-application-settlement.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-019-fees-and-application-settlement.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Two commercial mechanisms must exist without the protocol acquiring commercial opinions."
  },
  {
    "type": "ADR",
    "id": "ADR-020",
    "slug": "adr-020",
    "title": "Transaction proof and public verification",
    "path": "decisions/adr/ADR-020-transaction-proof-and-public-verification.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-020-transaction-proof-and-public-verification.md",
    "category": "Execução e primitivas financeiras",
    "summary": "A receipt is a screenshot. That is the practical situation across most payment channels: the evidence a payer gives a payee that money was sent is an image, which is trivially fabricated, and the payee's only recourse is to wait for the mon"
  },
  {
    "type": "ADR",
    "id": "ADR-021",
    "slug": "adr-021",
    "title": "Reason codes",
    "path": "decisions/adr/ADR-021-reason-codes.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-021-reason-codes.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Outcomes need names. A trust evaluation reaches a status, a fetch fails for a reason, a validation step ends in a state, a check identifies itself. Independent implementations have to agree on those names or they cannot compare results — an"
  },
  {
    "type": "ADR",
    "id": "ADR-022",
    "slug": "adr-022",
    "title": "Idempotency",
    "path": "decisions/adr/ADR-022-idempotency.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-022-idempotency.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Networks fail after the request arrives and before the response returns. The caller cannot distinguish that from a request that never arrived, so it retries — and in a payment system the retry is the danger, because the first request may al"
  },
  {
    "type": "ADR",
    "id": "ADR-023",
    "slug": "adr-023",
    "title": "Test material can never be production-valid",
    "path": "decisions/adr/ADR-023-test-material-can-never-be-production-valid.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-023-test-material-can-never-be-production-valid.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Every payment system runs a sandbox, and every sandbox eventually touches production. The failure modes are specific and each has happened somewhere: a simulated provider deployed to production, where payments appear to succeed and no money"
  },
  {
    "type": "ADR",
    "id": "ADR-024",
    "slug": "adr-024",
    "title": "Identity verification stays operator policy",
    "path": "decisions/adr/ADR-024-identity-verification-stays-operator-policy.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-024-identity-verification-stays-operator-policy.md",
    "category": "Execução e primitivas financeiras",
    "summary": "Every operator verifies who its participants are, and the pressure to standardise it is constant. Operators ask what documents to accept, what tiers to define and what evidence to keep, and a protocol that answers looks helpful."
  },
  {
    "type": "ADR",
    "id": "ADR-025",
    "slug": "adr-025",
    "title": "Trust without a certificate authority",
    "path": "decisions/adr/ADR-025-trust-without-a-certificate-authority.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-025-trust-without-a-certificate-authority.md",
    "category": "Execução e primitivas financeiras",
    "summary": "An open protocol has to answer how one operator decides to interoperate with another. The conventional answer is a certificate: a central body inspects a participant, issues a signed artifact saying it is acceptable, and peers check for tha"
  },
  {
    "type": "ADR",
    "id": "ADR-026",
    "slug": "adr-026",
    "title": "Root authorization: three authorities, threshold two",
    "path": "decisions/adr/ADR-026-root-authorization-three-authorities-threshold-two.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-026-root-authorization-three-authorities-threshold-two.md",
    "category": "Execução e primitivas financeiras",
    "summary": "The BANZA Trust Root is the anchor every conforming implementation pins once and uses to verify all subsequent protocol material. Whatever controls it controls the maximum authority in the protocol, so the question \"how many parties must ac"
  },
  {
    "type": "ADR",
    "id": "ADR-027",
    "slug": "adr-027",
    "title": "Private keys never on serving infrastructure",
    "path": "decisions/adr/ADR-027-signing-keys-never-on-serving-infrastructure.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-027-signing-keys-never-on-serving-infrastructure.md",
    "category": "Confiança e chaves",
    "summary": "The protocol publishes signed artifacts, and the obvious way to publish signed artifacts is to sign them where they are served. The signing key then lives on a machine that is internet-facing, runs a web server and a database, accepts reque"
  },
  {
    "type": "ADR",
    "id": "ADR-028",
    "slug": "adr-028",
    "title": "Anti-rollback for versioned trust material",
    "path": "decisions/adr/ADR-028-anti-rollback-for-versioned-trust-material.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-028-anti-rollback-for-versioned-trust-material.md",
    "category": "Confiança e chaves",
    "summary": "Trust material is republished: keys rotate, revocation lists grow, protocol metadata is reissued. Every version is correctly signed, which creates an attack that needs no cryptographic break at all. An adversary positioned between a verifie"
  },
  {
    "type": "ADR",
    "id": "ADR-029",
    "slug": "adr-029",
    "title": "Canonical discovery surface",
    "path": "decisions/adr/ADR-029-canonical-discovery-surface.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-029-canonical-discovery-surface.md",
    "category": "Confiança e chaves",
    "summary": "Before a verifier can evaluate anything, it has to find the material. Discovery is the first step of every trust evaluation, and it is the step where an ambiguous specification does the most damage: if two implementations look in two places"
  },
  {
    "type": "ADR",
    "id": "ADR-030",
    "slug": "adr-030",
    "title": "Conformance profiles and the capability vocabulary",
    "path": "decisions/adr/ADR-030-conformance-profiles-and-the-capability-vocabulary.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-030-conformance-profiles-and-the-capability-vocabulary.md",
    "category": "Confiança e chaves",
    "summary": "\"Is this implementation conformant?\" is not answerable as asked. An implementation that correctly runs a sandbox with valid manifests and integer money is conformant to something real; so is one that federates with peers and settles across "
  },
  {
    "type": "ADR",
    "id": "ADR-031",
    "slug": "adr-031",
    "title": "Operator self-publication and machine-verifiable conformance",
    "path": "decisions/adr/ADR-031-operator-self-publication-and-machine-verifiable-conformance.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-031-operator-self-publication-and-machine-verifiable-conformance.md",
    "category": "Confiança e chaves",
    "summary": "Removing the certificate authority (ADR-025) leaves a practical question. If no central body inspects an implementation and pronounces it acceptable, how does an implementation become known and checkable at all?"
  },
  {
    "type": "ADR",
    "id": "ADR-032",
    "slug": "adr-032",
    "title": "Certification records and their lifecycle",
    "path": "decisions/adr/ADR-032-certification-records-and-their-lifecycle.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-032-certification-records-and-their-lifecycle.md",
    "category": "Confiança e chaves",
    "summary": "Conformance evidence is a measurement at a moment. Something has to hold that measurement over time, because the useful question is not \"did these vectors pass once?\" but \"does this implementation hold a current, in-scope demonstration?\""
  },
  {
    "type": "ADR",
    "id": "ADR-033",
    "slug": "adr-033",
    "title": "The BANZA Technical Registry",
    "path": "decisions/adr/ADR-033-the-banza-technical-registry.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-033-the-banza-technical-registry.md",
    "category": "Conformidade, perfis e registo",
    "summary": "Certification records and profiles are only useful if they can be found and checked by someone who did not receive them directly. That needs a published index."
  },
  {
    "type": "ADR",
    "id": "ADR-034",
    "slug": "adr-034",
    "title": "Endpoint-originated validation",
    "path": "decisions/adr/ADR-034-endpoint-originated-validation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-034-endpoint-originated-validation.md",
    "category": "Conformidade, perfis e registo",
    "summary": "Validating an implementation means evaluating its artifacts. Where those artifacts come from decides what the result means."
  },
  {
    "type": "ADR",
    "id": "ADR-035",
    "slug": "adr-035",
    "title": "Operator Zero: the read-only reference implementation",
    "path": "decisions/adr/ADR-035-operator-zero-the-read-only-reference-implementation.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-035-operator-zero-the-read-only-reference-implementation.md",
    "category": "Conformidade, perfis e registo",
    "summary": "A specification with no working implementation cannot be checked end to end. Its contracts have never been served, its vectors have never run against a live system, and the first team to implement it discovers every ambiguity at their own e"
  },
  {
    "type": "ADR",
    "id": "ADR-036",
    "slug": "adr-036",
    "title": "BanzAI: a non-authoritative interface to the protocol",
    "path": "decisions/adr/ADR-036-banzai-a-non-authoritative-interface-to-the-protocol.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-036-banzai-a-non-authoritative-interface-to-the-protocol.md",
    "category": "Conformidade, perfis e registo",
    "summary": "BANZA is a specification. Reading a specification well takes expertise most people arriving at a financial interoperability protocol do not have, and the questions they actually need answered — does my implementation conform?, what does thi"
  },
  {
    "type": "ADR",
    "id": "ADR-037",
    "slug": "adr-037",
    "title": "Operator onboarding",
    "path": "decisions/adr/ADR-037-operator-onboarding.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-037-operator-onboarding.md",
    "category": "Conformidade, perfis e registo",
    "summary": "Validation runs against public endpoints and costs real resources — fetches, engine execution, stored receipts. Exposing that to anonymous callers makes it a free amplification service, and the obvious fix is an account system with password"
  },
  {
    "type": "ADR",
    "id": "ADR-038",
    "slug": "adr-038",
    "title": "Rust-first official engines",
    "path": "decisions/adr/ADR-038-rust-first-official-engines.md",
    "canonicalUrl": "https://github.com/banza-protocol/banza/blob/main/decisions/adr/ADR-038-rust-first-official-engines.md",
    "category": "Conformidade, perfis e registo",
    "summary": "The protocol prescribes no implementation technology for operators, and that neutrality is permanent (ADR-002). It says nothing about what language the project's own official components are written in, and that question needs its own answer"
  }
];

export const decisionCategories: string[] = [
  "Identidade e camadas",
  "Autoridade e determinismo",
  "Execução e primitivas financeiras",
  "Confiança e chaves",
  "Conformidade, perfis e registo"
];

export function getDecision(slug: string): Decision | undefined {
  return decisions.find((d) => d.slug === slug);
}
