// GENERATED by tools/gen-operador-zero-artifacts.mjs — DO NOT EDIT. RUST_WRAPPER_ONLY.
//
// The ten served Operador Zero artifacts, vendored from examples/operators/zero/ so the website
// Docker image (built from website/ alone) can serve them without a runtime filesystem read. The
// canonical source is examples/operators/zero/; `make operator-zero-check` fails if this drifts.
//
// RUST_WRAPPER_ONLY: this is inert DATA, not an engine. It carries no logic — but the embedded
// artifact JSON contains engine marker strings (e.g. the `evidence_bundle` artifact type and a
// `fail-closed` note), which the Rust-first guard scans for. The simulator's engine is Rust
// (operator-zero-core); this file only holds the JSON that engine validated.

export const ARTIFACT_DATA: Record<string, unknown> = {
  ".well-known/banza/operator": {
    "base_url": "https://zero.banza.network",
    "brl_url": "https://zero.banza.network/revocation-list.json",
    "capabilities": {
      "supports_payment_requests": true,
      "supports_qr": true,
      "supports_settlement_simulation": true,
      "supports_transfers": true,
      "supports_wallets": true
    },
    "conformance_url": "https://zero.banza.network/conformance/evidence.json",
    "contact": "ops@zero.banza.network",
    "created_at": "2026-08-05T00:00:00Z",
    "demo_only": true,
    "endpoints": {
      "base_url": "https://zero.banza.network",
      "conformance_url": "https://zero.banza.network/conformance/evidence.json",
      "key_manifest_url": "https://zero.banza.network/key-manifest.json"
    },
    "environment": "sandbox",
    "key_manifest_url": "https://zero.banza.network/key-manifest.json",
    "manifest_hash": "4e015bbf5fbcd92aa9a8452c2ab4d88de928df0ed41ecd22f7c6dc81c7a96966",
    "manifest_version": 1,
    "monetary_value": false,
    "name": "Operador Zero (simulador demo)",
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "origin": "https://zero.banza.network",
    "production_allowed": false,
    "protocol_version": "1.0.0",
    "public_keys": [
      {
        "algorithm": "ed25519",
        "key_id": "operator-zero-key-1",
        "public_key": "ed25519:AAAA"
      }
    ],
    "self_publication_statement": "self-published by the operator; not issued or approved by BANZA",
    "simulated": true,
    "supported_levels": [
      "L0"
    ]
  },
  "key-manifest": {
    "delegated_signing_key": {
      "algorithm": "ed25519",
      "allowed_usages": [
        "signed_protocol_metadata"
      ],
      "delegated_key_id": "banza-oz-protocol-metadata-2026-08",
      "key_scope": "protocol-metadata",
      "public_key": "yJ3CZPcrFwoXFnGQHjLxRlOu1Rze4op94azlAypbMCo",
      "revoked": false,
      "signed_by_root_threshold": true,
      "valid_from": "2026-01-01T00:00:00Z",
      "valid_until": "2030-01-01T00:00:00Z"
    },
    "demo_only": true,
    "disclaimer": "Material de chaves OTE TEST-ONLY do Operador Zero (demo). Sem chaves privadas reais. Não é certificado, não é aprovação e não movimenta dinheiro real.",
    "keys": [
      {
        "key_id": "banza-oz-protocol-metadata-2026-08",
        "public_key": "yJ3CZPcrFwoXFnGQHjLxRlOu1Rze4op94azlAypbMCo",
        "status": "active",
        "usage": "signed_protocol_metadata"
      }
    ],
    "monetary_value": false,
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "production_allowed": false,
    "public_registry_entry": {
      "conformance_evidence_hash": "7625e9f9822e76c450827e0add1cc1512256a3e3bda59f971f2d9fab9ab99927",
      "delegated_key_id": "banza-oz-protocol-metadata-2026-08",
      "last_verified_at": "2026-08-05T00:00:00Z",
      "manifest_hash": "4e015bbf5fbcd92aa9a8452c2ab4d88de928df0ed41ecd22f7c6dc81c7a96966",
      "operator_id": "operator-zero",
      "revocation_status": "active",
      "signed_protocol_metadata_hash": "b2b2b6d782b1bcd3a2d041ba466894e72ad8958dc5c3fe8d5d2e574b2aa92467",
      "trust_root_version": "2026.08",
      "verified_by_tool_version": "banza-trust 0.2.0"
    },
    "schema": "banza-ote-key-material/1",
    "test_only": true,
    "trust_root_metadata": {
      "active_root_public_keys": [
        "72T4xy5j8-oWXzO4uCz7-Wtj7ZGPcyVfrguYHL06trw",
        "pM7p7N5-hm3MnESKTpYxA3A164dnvRwgGDhSqnxiGog",
        "rqQwbo1ZeXCPiGA7W3pd_SsFCzQMPb7Wuiq6Dc8LCfY"
      ],
      "boundary": {
        "authorises_operators": false,
        "moves_funds": false
      },
      "delegated_signing_keys": [
        {
          "allowed_usages": [
            "signed_protocol_metadata"
          ],
          "delegated_key_id": "banza-oz-protocol-metadata-2026-08",
          "public_key": "yJ3CZPcrFwoXFnGQHjLxRlOu1Rze4op94azlAypbMCo",
          "revoked": false,
          "signed_by_root_threshold": true,
          "valid_from": "2026-01-01T00:00:00Z",
          "valid_until": "2030-01-01T00:00:00Z"
        }
      ],
      "root_id": "banza-oz-root-2026",
      "root_signatures": [
        "qpCXwdFrfwrOu1zPASFaOak_IhOicc5geQY1vXcBpsowBYCyasg8JYeZ_QSddQOKEi8RcwMIohj2ZADWfi3IAw",
        "HEtYNCIG5TDi77YAVYhm87tskeqMT1cee9AMiTpVDlCU3VZJLpqGuzJLlx0X55v15vvP735bvuyi4gXS_2J7DA"
      ],
      "scope": "signs only the Key Manifest that endorses the delegated signing keys (ADR-027)",
      "threshold_policy": {
        "min_signatures": 2,
        "total_keyholders": 3
      },
      "trust_root_version": "2026.08",
      "valid_from": "2026-01-01T00:00:00Z",
      "valid_until": "2030-01-01T00:00:00Z"
    },
    "trusted_root_public_keys": [
      "72T4xy5j8-oWXzO4uCz7-Wtj7ZGPcyVfrguYHL06trw",
      "pM7p7N5-hm3MnESKTpYxA3A164dnvRwgGDhSqnxiGog",
      "rqQwbo1ZeXCPiGA7W3pd_SsFCzQMPb7Wuiq6Dc8LCfY"
    ]
  },
  "revocation-list": {
    "demo_only": true,
    "fail_closed_required": true,
    "monetary_value": false,
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "production_allowed": false,
    "reason_code": null,
    "revocation_entry_hash": null,
    "revocation_list_version": "2026.08-01",
    "revoked": false,
    "signed_by_revocation_key": "c2kFSkx9izlsXzwKM0hYGAHIdMXk6ekjwpNnI1fx1Tg"
  },
  "conformance/evidence": {
    "cases": [
      {
        "case_id": "L0-INV-LEDGER-001",
        "invariant_id": "INV-LEDGER-001",
        "reason": "débitos 101000 == créditos 101000; cada trace tem 1 DEBIT + 1 CREDIT",
        "status": "PASS"
      },
      {
        "case_id": "L0-INV-IDEM-001",
        "invariant_id": "INV-IDEM-001",
        "reason": "cada idempotency key mapeia a uma única resposta estável",
        "status": "PASS"
      },
      {
        "case_id": "L0-INV-SETTLE-001",
        "invariant_id": "INV-SETTLE-001",
        "reason": "net + fee == gross em todas as settlements",
        "status": "PASS"
      },
      {
        "case_id": "L0-INV-WALLET-001",
        "invariant_id": "INV-WALLET-001",
        "reason": "todos os saldos derivados do ledger são >= 0",
        "status": "PASS"
      }
    ],
    "certification_disclaimer": "PASS is technical conformance evidence, not production certification. Production certification requires the offline root-key ceremony and the first published production conformance evidence; no implementation holds production certification and no production certificate is active.",
    "demo_only": true,
    "disclaimer_pt": "PASS técnico é evidência de conformidade, não é certificação. A certificação de produção depende da cerimónia offline da chave raiz e da primeira evidência de conformidade de produção publicada; nenhuma implementação tem evidência de conformidade de produção activa.",
    "evidence": [
      "simb-scenario:valid_l0",
      "operator:SIM-A (test-only)",
      "ledger_entries:4"
    ],
    "evidence_hash": "7625e9f9822e76c450827e0add1cc1512256a3e3bda59f971f2d9fab9ab99927",
    "external_model_called": false,
    "failures": [],
    "injected_fault": null,
    "invariants": [
      {
        "id": "INV-LEDGER-001",
        "name": "Double-entry",
        "reason": "débitos 101000 == créditos 101000; cada trace tem 1 DEBIT + 1 CREDIT",
        "status": "PASS"
      },
      {
        "id": "INV-IDEM-001",
        "name": "Idempotência",
        "reason": "cada idempotency key mapeia a uma única resposta estável",
        "status": "PASS"
      },
      {
        "id": "INV-SETTLE-001",
        "name": "Identidade de settlement",
        "reason": "net + fee == gross em todas as settlements",
        "status": "PASS"
      },
      {
        "id": "INV-WALLET-001",
        "name": "Sem saldo negativo",
        "reason": "todos os saldos derivados do ledger são >= 0",
        "status": "PASS"
      }
    ],
    "level": "L0",
    "llm_calls": 0,
    "mode": "demo-simb",
    "monetary_value": false,
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "pre_review_gate": true,
    "production_allowed": false,
    "protocol_version": "1.0.0",
    "ready_disclaimer": "Readiness is verifiable conformance evidence, not an approval.",
    "ready_for_conformance_evidence_review": true,
    "report_id": "l0-valid_l0-PASS",
    "runner": "banza-conformance-rs",
    "runner_version": "0.1.0",
    "scenario_id": "valid_l0",
    "simb_pre_review_status": "SIMB_PRE_REVIEW_PASS",
    "status": "PASS",
    "test_only": true,
    "tool": "banza-conformance-rs",
    "tool_version": "0.1.0",
    "totals": {
      "fail": 0,
      "pass": 4,
      "total": 4
    }
  },
  "federation/metadata": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "artifact_type": "federation_metadata",
    "protocol_version": "1.0",
    "peers": [
      "peer-zero-alpha",
      "peer-zero-beta"
    ],
    "note": "Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  },
  "evidence-bundle": {
    "boundary": "Evidence Bundle é evidência técnica verificável. Não é certificado. Não é aprovação. A conformidade demonstra-se por evidência verificável; não há aprovação humana central.",
    "bundle_id": "bundle-e8fb84c565e5",
    "citations": [
      "docs/governance/EVIDENCE_BUNDLE.md",
      "docs/governance/SIMB_PRE_REVIEW_GATE.md",
      "/banzai"
    ],
    "conformance_l0": {
      "cases": [
        {
          "case_id": "L0-INV-LEDGER-001",
          "invariant_id": "INV-LEDGER-001",
          "reason": "débitos 101000 == créditos 101000; cada trace tem 1 DEBIT + 1 CREDIT",
          "status": "PASS"
        },
        {
          "case_id": "L0-INV-IDEM-001",
          "invariant_id": "INV-IDEM-001",
          "reason": "cada idempotency key mapeia a uma única resposta estável",
          "status": "PASS"
        },
        {
          "case_id": "L0-INV-SETTLE-001",
          "invariant_id": "INV-SETTLE-001",
          "reason": "net + fee == gross em todas as settlements",
          "status": "PASS"
        },
        {
          "case_id": "L0-INV-WALLET-001",
          "invariant_id": "INV-WALLET-001",
          "reason": "todos os saldos derivados do ledger são >= 0",
          "status": "PASS"
        }
      ],
      "certification_disclaimer": "PASS is technical conformance evidence, not production certification. Production certification requires the offline root-key ceremony and the first published production conformance evidence; no implementation holds production certification and no production certificate is active.",
      "demo_only": true,
      "disclaimer_pt": "PASS técnico é evidência de conformidade, não é certificação. A certificação de produção depende da cerimónia offline da chave raiz e da primeira evidência de conformidade de produção publicada; nenhuma implementação tem evidência de conformidade de produção activa.",
      "evidence": [
        "simb-scenario:valid_l0",
        "operator:SIM-A (test-only)",
        "ledger_entries:4"
      ],
      "evidence_hash": "7625e9f9822e76c450827e0add1cc1512256a3e3bda59f971f2d9fab9ab99927",
      "external_model_called": false,
      "failures": [],
      "injected_fault": null,
      "invariants": [
        {
          "id": "INV-LEDGER-001",
          "name": "Double-entry",
          "reason": "débitos 101000 == créditos 101000; cada trace tem 1 DEBIT + 1 CREDIT",
          "status": "PASS"
        },
        {
          "id": "INV-IDEM-001",
          "name": "Idempotência",
          "reason": "cada idempotency key mapeia a uma única resposta estável",
          "status": "PASS"
        },
        {
          "id": "INV-SETTLE-001",
          "name": "Identidade de settlement",
          "reason": "net + fee == gross em todas as settlements",
          "status": "PASS"
        },
        {
          "id": "INV-WALLET-001",
          "name": "Sem saldo negativo",
          "reason": "todos os saldos derivados do ledger são >= 0",
          "status": "PASS"
        }
      ],
      "level": "L0",
      "llm_calls": 0,
      "mode": "demo-simb",
      "monetary_value": false,
      "operator_display_name": "Operador Zero",
      "operator_id": "operator-zero",
      "pre_review_gate": true,
      "production_allowed": false,
      "protocol_version": "1.0.0",
      "ready_disclaimer": "Readiness is verifiable conformance evidence, not an approval.",
      "ready_for_conformance_evidence_review": true,
      "report_id": "l0-valid_l0-PASS",
      "runner": "banza-conformance-rs",
      "runner_version": "0.1.0",
      "scenario_id": "valid_l0",
      "simb_pre_review_status": "SIMB_PRE_REVIEW_PASS",
      "status": "PASS",
      "test_only": true,
      "tool": "banza-conformance-rs",
      "tool_version": "0.1.0",
      "totals": {
        "fail": 0,
        "pass": 4,
        "total": 4
      }
    },
    "created_at": "2026-08-05T00:00:00Z",
    "demo_only": true,
    "environment": "pre-production",
    "external_model_called": false,
    "hashes": {
      "bundle_hash": "f015547af6538e7ca1a3c673fdaf9be818f5ffd65fc3d369e2e7d0c70244acfa",
      "conformance_report_hash": "2c516ba6a2ddff6671faf3ec7a888a2702247216da0ca3c02127afea8df91a0f",
      "l1_readiness_hash": null,
      "l2_readiness_hash": null,
      "l3_readiness_hash": null,
      "l4_readiness_hash": null,
      "m2_protocol_gate_hash": null,
      "m2_root_ceremony_hash": null,
      "open_governance_hash": null,
      "operator_manifest_hash": null,
      "reference_trust_model_hash": null,
      "security_assurance_hash": null,
      "security_deep_assurance_hash": null,
      "simb_report_hash": "0a85ff92af4c8a279e05a6d3484dbf8f68881dea50d7a517086465b9d447eeae",
      "trace_report_hash": null,
      "trust_report_hash": null
    },
    "l1_readiness_report": null,
    "l2_readiness_report": null,
    "l2_readiness_summary": {
      "blockers": null,
      "disclaimer": "L2 readiness não é pagamento real nem certificação.",
      "payment_flow_summary": null,
      "readiness": null,
      "status": null
    },
    "l3_readiness_report": null,
    "l3_readiness_summary": {
      "blockers": null,
      "disclaimer": "L3 readiness não é federação activa nem certificação.",
      "federation_summary": null,
      "readiness": null,
      "status": null
    },
    "l4_readiness_report": null,
    "l4_readiness_summary": {
      "blockers": null,
      "disclaimer": "L4 readiness não é integração externa activa, não é certificação, não é licença e não transforma BANZA em prestador de serviços de pagamento.",
      "interoperability_summary": null,
      "readiness": null,
      "status": null
    },
    "limitations": [
      "Pré-produção: inferência determinística offline, sem chamadas a modelo de linguagem e sem modelo externo (os campos estruturados de contagem de chamadas permanecem a zero).",
      "Artefactos obrigatórios: SimB pre-review + Conformidade L0. Recomendados nesta fase: Trace, Trust & BRL, Operator Manifest Validation, L1, L2, L3, L4 Readiness e Security Assurance (preparação para os próximos níveis).",
      "Readiness READY_FOR_TECHNICAL_REVIEW é evidência técnica de prontidão — não é certificação nem aprovação.",
      "Os hashes são integridade técnica (SHA-256), não assinatura nem autoridade.",
      "A conformidade é verificada por conformance automation e evidência verificável, não por decisão humana central."
    ],
    "llm_calls": 0,
    "m2_protocol_gate_report": null,
    "m2_protocol_gate_summary": {
      "blocked_items": null,
      "disclaimer": null,
      "forbidden_activation_attempts": null,
      "m2_state": null,
      "missing_artifacts": null,
      "protocol_production_prepared": null,
      "status": null
    },
    "m2_root_ceremony_report": null,
    "m2_root_ceremony_summary": {
      "backup_summary": null,
      "boundary_summary": null,
      "custody_summary": null,
      "disclaimer": null,
      "forbidden_private_key_material_detected": null,
      "offline_environment_summary": null,
      "recovery_test_summary": null,
      "status": null,
      "threshold": null,
      "valid_signature_count": null
    },
    "missing_recommended": [
      "trace_verification",
      "trust_engine_report",
      "operator_manifest_validation",
      "l1_readiness_report",
      "l2_readiness_report",
      "l3_readiness_report",
      "l4_readiness_report",
      "security_assurance_report",
      "security_deep_assurance_report",
      "m2_protocol_gate_report",
      "m2_root_ceremony_report",
      "open_governance_report",
      "reference_trust_model_report"
    ],
    "missing_required": [],
    "mode": "local",
    "monetary_value": false,
    "not_a_certificate": true,
    "not_an_approval": true,
    "open_governance_report": null,
    "open_governance_summary": {
      "blocked_items": null,
      "ca_dependency_detected": null,
      "certificate_semantics_detected": null,
      "conformance_automation_summary": null,
      "deprecated_terms": null,
      "disclaimer": "Open governance report confirma a arquitectura de protocolo financeiro aberto. Não é autorização de operador, não é certificação, não é licença e não permite prestação de serviços financeiros pelo BANZA.",
      "governance_model": null,
      "human_operator_approval_detected": null,
      "operator_self_publication_summary": null,
      "revocation_summary": null,
      "status": null,
      "succession_summary": null,
      "trust_root_summary": null
    },
    "operator_candidate": "operator-zero",
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "operator_manifest_validation": null,
    "production_allowed": false,
    "readiness": "READY_FOR_TECHNICAL_REVIEW",
    "recommended_artifacts": [
      "trace_verification",
      "trust_engine_report",
      "operator_manifest_validation",
      "l1_readiness_report",
      "l2_readiness_report",
      "l3_readiness_report",
      "l4_readiness_report",
      "security_assurance_report",
      "security_deep_assurance_report",
      "m2_protocol_gate_report",
      "m2_root_ceremony_report",
      "open_governance_report",
      "reference_trust_model_report"
    ],
    "reference_trust_model_report": null,
    "reference_trust_model_summary": {
      "active_trust_model_summary": null,
      "blocked_items": null,
      "boundary_summary": null,
      "central_authority_claim_detected": null,
      "conformance_evidence_summary": null,
      "disclaimer": "Este relatório descreve o modelo activo de trust do protocolo financeiro aberto BANZA. Não é autorização de operador, não é certificação, não é licença e não permite prestação de serviços financeiros pelo BANZA.",
      "invalid_trust_evidence_detected": null,
      "operator_approval_claim_detected": null,
      "public_registry_summary": null,
      "revocation_fail_closed_summary": null,
      "signed_metadata_summary": null,
      "status": null,
      "trust_evaluation_summary": null
    },
    "required_artifacts": [
      "simb_pre_review",
      "conformance_l0"
    ],
    "requires_conformance_evidence_review": true,
    "schema_version": "banza-evidence-bundle/1",
    "security_assurance_report": null,
    "security_assurance_summary": {
      "control_gaps": null,
      "critical_risks": null,
      "disclaimer": "Security & Risk Assurance não é auditoria externa, não é certificação, não é licença e não activa produção.",
      "high_risks": null,
      "missing_evidence": null,
      "status": null
    },
    "security_deep_assurance_report": null,
    "security_deep_assurance_summary": {
      "disclaimer": "Deep Assurance (BX2.1–BX2.4) é aprofundamento de assurance — não é auditoria externa concluída, não é certificação, não é licença, não activa federação nem integração externa e não move fundos.",
      "missing_documents": null,
      "open_critical_gaps": null,
      "pre_audit_readiness": null,
      "status": null,
      "tracks": null
    },
    "simb_pre_review": {
      "balances": [
        {
          "balance_minor": 899000,
          "wallet_id": "sandbox-consumer-1"
        },
        {
          "balance_minor": 1000,
          "wallet_id": "sandbox-merchant-1"
        },
        {
          "balance_minor": 100000,
          "wallet_id": "sandbox-merchant-2"
        }
      ],
      "disclaimer": "SimB PASS é evidência técnica de pré-revisão. Não é certificação; SimB não certifica, não aprova e não cria operador real. A conformidade demonstra-se por evidência verificável, não por aprovação humana central.",
      "events": [
        "Operador simulado SIM-A criado (wallets sandbox seed, determinístico)",
        "Transferência sandbox-consumer-1 → sandbox-merchant-1 (1000 minor), idem=k1",
        "Replay idem=k1 (deve devolver a mesma resposta, sem novo posting)",
        "Transferência sandbox-consumer-1 → sandbox-merchant-2 (100000 minor), idem=k2",
        "Settlement da wallet sandbox-merchant-2 (net + fee == gross)"
      ],
      "external_model_called": false,
      "idempotency_results": [
        {
          "key": "k1",
          "replay": false,
          "response": "ok=true;tid=transfer-SIM-A-1",
          "transfer_id": "transfer-SIM-A-1"
        },
        {
          "key": "k1",
          "replay": true,
          "response": "ok=true;tid=transfer-SIM-A-1",
          "transfer_id": "transfer-SIM-A-1"
        },
        {
          "key": "k2",
          "replay": false,
          "response": "ok=true;tid=transfer-SIM-A-2",
          "transfer_id": "transfer-SIM-A-2"
        }
      ],
      "injected_fault": null,
      "invariant_checks": [
        {
          "id": "INV-LEDGER-001",
          "name": "Double-entry",
          "reason": "débitos 101000 == créditos 101000; cada trace tem 1 DEBIT + 1 CREDIT",
          "status": "PASS"
        },
        {
          "id": "INV-IDEM-001",
          "name": "Idempotência",
          "reason": "cada idempotency key mapeia a uma única resposta estável",
          "status": "PASS"
        },
        {
          "id": "INV-SETTLE-001",
          "name": "Identidade de settlement",
          "reason": "net + fee == gross em todas as settlements",
          "status": "PASS"
        },
        {
          "id": "INV-WALLET-001",
          "name": "Sem saldo negativo",
          "reason": "todos os saldos derivados do ledger são >= 0",
          "status": "PASS"
        }
      ],
      "label": "Operador válido L0",
      "ledger_entries": [
        {
          "amount_minor": 1000,
          "currency": "KZ_DEMO",
          "kind": "DEBIT",
          "trace_id": "trace-SIM-A-1",
          "wallet_id": "sandbox-consumer-1"
        },
        {
          "amount_minor": 100000,
          "currency": "KZ_DEMO",
          "kind": "DEBIT",
          "trace_id": "trace-SIM-A-2",
          "wallet_id": "sandbox-consumer-1"
        },
        {
          "amount_minor": 1000,
          "currency": "KZ_DEMO",
          "kind": "CREDIT",
          "trace_id": "trace-SIM-A-1",
          "wallet_id": "sandbox-merchant-1"
        },
        {
          "amount_minor": 100000,
          "currency": "KZ_DEMO",
          "kind": "CREDIT",
          "trace_id": "trace-SIM-A-2",
          "wallet_id": "sandbox-merchant-2"
        }
      ],
      "llm_calls": 0,
      "marker": "TEST ONLY — LOCAL SIMULATOR, NOT PRODUCTION",
      "mode": "demo · test-only",
      "not_a_certificate": true,
      "operator_id": "SIM-A",
      "pre_review_gate": true,
      "pre_review_status": "SIMB_PRE_REVIEW_PASS",
      "required_before_banza_ca_review": true,
      "scenario_id": "valid_l0",
      "settlement_summary": {
        "currency": "KZ_DEMO",
        "fee_minor": 1000,
        "gross_minor": 100000,
        "id": "settle-SIM-A-1",
        "identity_ok": true,
        "net_minor": 99000,
        "tx_count": 1,
        "wallet_id": "sandbox-merchant-2"
      },
      "status": "PASS",
      "test_only": true,
      "tool": "banza-simb",
      "tool_version": "0.1.0",
      "trace_summary": {
        "count": 2,
        "trace_ids": [
          "trace-SIM-A-1",
          "trace-SIM-A-2"
        ]
      },
      "warnings": []
    },
    "tool_versions": {
      "banza-conformance-rs": "0.1.0",
      "banza-evidence-bundle": "0.1.0",
      "banza-l1-readiness": null,
      "banza-l2-readiness": null,
      "banza-l3-readiness": null,
      "banza-l4-readiness": null,
      "banza-m2-protocol-gate": null,
      "banza-open-governance": null,
      "banza-operator-manifest": null,
      "banza-reference-trust-model": null,
      "banza-root-ceremony": null,
      "banza-security-assurance": null,
      "banza-security-assurance-deep": null,
      "banza-simb": "0.1.0",
      "banza-trust": null
    },
    "trace_verification": null,
    "trust_engine_report": null
  },
  "traces/full-e2e": {
    "blockers": [],
    "complete": true,
    "currency": "KZ_DEMO",
    "demo_only": true,
    "evidence_status": "evidence_complete",
    "evidence_status_label": "evidência completa",
    "ledger": {
      "accounts": [
        {
          "account_id": "demo-merchant-kiosque",
          "balance": 1000,
          "currency": "KZ_DEMO",
          "display_name": "Kiosque (comerciante fictício)",
          "is_settlement": false
        },
        {
          "account_id": "demo-user-ana",
          "balance": 99000,
          "currency": "KZ_DEMO",
          "display_name": "Ana (utilizador fictício)",
          "is_settlement": false
        },
        {
          "account_id": "operator-zero",
          "balance": 0,
          "currency": "KZ_DEMO",
          "display_name": "Operador Zero (liquidação fictícia)",
          "is_settlement": true
        }
      ],
      "currency": "KZ_DEMO",
      "demo_only": true,
      "ledger_status": "balanced",
      "monetary_value": false,
      "operator_display_name": "Operador Zero",
      "operator_id": "operator-zero",
      "production_allowed": false,
      "total": 100000
    },
    "monetary_value": false,
    "next_action": "simulacao_completa",
    "next_action_label": "Simulação completa",
    "note": "Simulação técnica. Não certifica, não aprova e não move dinheiro real.",
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "production_allowed": false,
    "reconciliation": {
      "closing_total": 100000,
      "currency": "KZ_DEMO",
      "demo_only": true,
      "discrepancies": [],
      "ledger_status": "balanced",
      "monetary_value": false,
      "movements": 2,
      "opening_total": 100000,
      "status": "reconciled",
      "status_label": "reconciliado"
    },
    "scenario": "full_e2e",
    "steps": [
      {
        "artifact_type": "manifest",
        "error": null,
        "ok": true,
        "step": "manifest"
      },
      {
        "artifact_type": "conformance_evidence",
        "ok": true,
        "step": "conformidade"
      },
      {
        "artifact_type": "trust_evidence",
        "ok": true,
        "status": "demo_trust_valid",
        "status_label": "trust demo válido",
        "step": "trust"
      },
      {
        "amount": 1500,
        "artifact_type": "payment",
        "currency": "KZ_DEMO",
        "ok": true,
        "payment_status": "confirmed",
        "payment_status_label": "confirmado",
        "refund_status": "partially_refunded",
        "refund_status_label": "parcialmente reembolsado",
        "refunded": 500,
        "step": "pagamento"
      },
      {
        "artifact_type": "federation_metadata",
        "ok": true,
        "status": "demo_federation_compatible",
        "status_label": "federação demo compatível",
        "step": "federacao"
      },
      {
        "artifact_type": "ledger",
        "ok": true,
        "status": "reconciled",
        "status_label": "reconciliado",
        "step": "reconciliacao"
      },
      {
        "artifact_type": "evidence_bundle",
        "ok": true,
        "status": "evidence_complete",
        "status_label": "evidência completa",
        "step": "evidence_bundle"
      }
    ]
  },
  "ledger/demo": {
    "accounts": [
      {
        "account_id": "demo-merchant-kiosque",
        "balance": 0,
        "currency": "KZ_DEMO",
        "display_name": "Kiosque (comerciante fictício)",
        "is_settlement": false
      },
      {
        "account_id": "demo-user-ana",
        "balance": 100000,
        "currency": "KZ_DEMO",
        "display_name": "Ana (utilizador fictício)",
        "is_settlement": false
      },
      {
        "account_id": "operator-zero",
        "balance": 0,
        "currency": "KZ_DEMO",
        "display_name": "Operador Zero (liquidação fictícia)",
        "is_settlement": true
      }
    ],
    "currency": "KZ_DEMO",
    "demo_only": true,
    "ledger_status": "empty",
    "monetary_value": false,
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "production_allowed": false,
    "total": 100000
  },
  "payments/demo-qr": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "currency": "KZ_DEMO",
    "artifact_type": "payment",
    "qr_id": "qr_demo_0001",
    "payment_status": "pending",
    "amount": 1500,
    "expires_at": "2026-07-21T00:05:00Z",
    "single_use": true,
    "note": "Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  },
  "payments/demo-refund": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "currency": "KZ_DEMO",
    "artifact_type": "payment",
    "transaction_id": "txn_qr_demo_0001_refund",
    "payment_status": "partially_refunded",
    "amount": 500,
    "original_transaction_id": "txn_qr_demo_0001",
    "note": "Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  },
  "discovery": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "implementation_id": "operator-zero-ref-impl",
    "artifact_type": "discovery",
    "currency": "KZ_DEMO",
    "protocol_version": "1.0.0",
    "environment": "sandbox",
    "profile": "L0",
    "supported_levels": [
      "L0"
    ],
    "canonical_origin": "https://zero.banza.network",
    "endpoints": {
      "manifest_url": "https://zero.banza.network/.well-known/banza/operator.json",
      "key_manifest_url": "https://zero.banza.network/key-manifest.json",
      "signed_metadata_url": "https://zero.banza.network/.well-known/banza/signed-protocol-metadata.json",
      "capabilities_url": "https://zero.banza.network/capabilities.json",
      "conformance_url": "https://zero.banza.network/conformance/evidence.json",
      "revocation_url": "https://zero.banza.network/revocation-list.json",
      "federation_metadata_url": "https://zero.banza.network/federation-metadata.json",
      "evidence_bundle_url": "https://zero.banza.network/evidence-bundle.json",
      "traces_url": "https://zero.banza.network/traces/full-e2e.json"
    },
    "note": "Documento de descoberta da implementação de referência. Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  },
  "capabilities": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "implementation_id": "operator-zero-ref-impl",
    "artifact_type": "capabilities",
    "currency": "KZ_DEMO",
    "protocol_version": "1.0.0",
    "environment": "sandbox",
    "profile": "L0",
    "supported_levels": [
      "L0"
    ],
    "capabilities": {
      "supports_wallets": true,
      "supports_qr": true,
      "supports_payments": true,
      "supports_refunds": true,
      "supports_settlement_simulation": true,
      "supports_reconciliation": true
    },
    "capability_list": [
      "qr_payment_demo",
      "refund_demo",
      "reconciliation_demo",
      "settlement_simulation_demo"
    ],
    "note": "Matriz de capacidades declaradas pela implementação de referência. Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  },
  ".well-known/banza/signed-protocol-metadata": {
    "capability_profile_hash": "sha256:capability-profile",
    "conformance_evidence_hash": "7625e9f9822e76c450827e0add1cc1512256a3e3bda59f971f2d9fab9ab99927",
    "conformance_tool_version": "banza-conformance-rs 0.1.0",
    "demo_only": true,
    "evidence_bundle_hash": "sha256:evidence-bundle",
    "metadata_id": "spm-operator-zero-2026-08",
    "monetary_value": false,
    "operator_display_name": "Operador Zero",
    "operator_id": "operator-zero",
    "operator_manifest_hash": "4e015bbf5fbcd92aa9a8452c2ab4d88de928df0ed41ecd22f7c6dc81c7a96966",
    "production_allowed": false,
    "protocol_version": "1.0.0",
    "registry_snapshot_hash": "sha256:registry-snapshot",
    "release_id": "banza-protocol-1.0.0",
    "revocation_list_hash": "sha256:revocation-list",
    "schema_versions": {
      "conformance_evidence": "1.0",
      "operator_manifest": "1.0"
    },
    "signature": "wUj6fRKHeni0RGsmyjI_rkjJnKWz-QBX8p4-lmrBm9jNB3M7c9r1tIyC7KqjDEaX5jgC2i7-nergJuRI1baIBw",
    "valid_from": "2026-01-01T00:00:00Z",
    "valid_until": "2030-01-01T00:00:00Z"
  },
  "federation-metadata": {
    "demo_only": true,
    "monetary_value": false,
    "production_allowed": false,
    "operator_id": "operator-zero",
    "operator_display_name": "Operador Zero",
    "implementation_id": "operator-zero-ref-impl",
    "artifact_type": "federation_metadata",
    "currency": "KZ_DEMO",
    "protocol_version": "1.0.0",
    "environment": "sandbox",
    "profile": "L0",
    "discovery_url": "https://zero.banza.network/discovery.json",
    "signed_metadata_url": "https://zero.banza.network/.well-known/banza/signed-protocol-metadata.json",
    "federation_status": "demo_federation_compatible",
    "profile_compatibility": {
      "supported_levels": [
        "L0"
      ],
      "compatible_profiles": [
        "L0"
      ]
    },
    "capabilities": [
      "qr_payment_demo",
      "refund_demo",
      "reconciliation_demo",
      "settlement_simulation_demo"
    ],
    "routing_eligibility": {
      "eligible": false,
      "reason": "Ambiente de demonstração — não participa no scheme operacional (Camada 3) nem encaminha valor real."
    },
    "handshake": {
      "method": "signed_challenge",
      "signature_algorithm": "ed25519",
      "nonce_required": true,
      "signed_metadata_url": "https://zero.banza.network/.well-known/banza/signed-protocol-metadata.json"
    },
    "peers": [
      "peer-zero-alpha",
      "peer-zero-beta"
    ],
    "note": "Metadata de federação da implementação de referência (compatibilidade de perfil, capacidades, elegibilidade de encaminhamento e handshake). Artefacto demonstrativo. Não certifica, não aprova e não movimenta dinheiro real."
  }
};

// M2.14A — versioned demo-validation state (rendered on zero.banza.network; not a served endpoint).
export const VALIDATION_STATE: Record<string, unknown> = {
  "operator_id": "operator-zero",
  "operator_display_name": "Operador Zero",
  "demo_only": true,
  "monetary_value": false,
  "production_allowed": false,
  "currency": "KZ_DEMO",
  "real_money": false,
  "certification": false,
  "operator_real": false,
  "status": "demo_validated",
  "status_label_pt": "avaliado — implementação de referência só de leitura",
  "pass_label_pt": "evidência técnica local",
  "journey_steps_completed": 9,
  "journey_steps_total": 9,
  "artifacts_ready": 6,
  "artifacts_total": 6,
  "blockers": 0,
  "evidence_bundle_url": "https://zero.banza.network/evidence-bundle.json",
  "trace_url": "https://zero.banza.network/traces/full-e2e.json",
  "boundary_pt": "Este estado é demonstração técnica. Não é certificação, não é aprovação, não é licença financeira e não representa operador de produção.",
  "note": "Estado de validação do Operador Zero — a implementação de referência canónica, só de leitura, do protocolo BANZA (ADR-041). É evidência técnica local: não certifica, não aprova, não licencia e não representa operador real. Não corre simulação nem tem ledger mutável. A moeda KZ_DEMO é uma unidade de demonstração, sem valor real. last_validation_commit regista o último commit em que a validação foi registada; é actualizado por fase de validação."
};
