import { readFileSync } from "node:fs";
import { join } from "node:path";

// Build-time loader for the BANZA Whitepaper v1.0 content. Single source of truth:
// docs/whitepaper/content/<lang>.json (repo). The Docker build context is `website/` only, so a synced
// copy lives at website/content/whitepaper/<lang>.json (derived from the LaTeX dossier by
// tools/whitepaper-content.py and mirrored here by tools/whitepaper-release.sh).
// The JSON is DERIVED from the canonical PT dossier (docs/whitepaper/latex/whitepaper.pt.tex, the
// approved Overleaf edition) via tools/whitepaper-pt-content.py; this web edition renders it. The
// renderer is NOT an editorial source — content changes start in the Overleaf PT edition.

export type WPEquationItem = { n: string; label: string; latex: string; html: string };
export type WPBlock =
  | { t: "p"; text: string }
  | { t: "list"; items: string[] }
  | { t: "eq"; items: WPEquationItem[] }
  | { t: "fig"; id: string };
export type WPSection = { id: string; number: number; title: string; label: string; blocks: WPBlock[] };
export type WPFigure = {
  id: string; n: number; file_pt: string; file_en: string; label: string;
  title: string; caption: string; alt: string;
};
export type WPAuthor = { display: string; full: string };
export type WPWeb = { website_label: string; website: string };

export type Whitepaper = {
  lang: "en" | "pt";
  is_canonical: boolean;
  title: string;
  subtitle: string;
  version: string;
  document_type: string;
  normative: boolean;
  status: string;
  date_iso: string;
  date_display: string;
  authors: WPAuthor[];
  author_note: string;
  affiliation: string;
  affiliation_legal: string;
  publisher: string;
  publisher_legal: string;
  license: string;
  copyright: string;
  canonical_url: string;
  canonicity_notice: string;
  scope_notice: string;
  keywords: string[];
  abstract: string;
  sections: WPSection[];
  figures: WPFigure[];
  references: string[];
  citation: string;
  web_block: WPWeb;
  source_commit: string;
};

const LANGS = ["en", "pt"] as const;
export type WPLang = (typeof LANGS)[number];

function load(lang: WPLang): Whitepaper {
  const p = join(process.cwd(), "content", "whitepaper", `${lang}.json`);
  return JSON.parse(readFileSync(p, "utf8")) as Whitepaper;
}

export function getWhitepaper(lang: WPLang): Whitepaper {
  return load(lang);
}

export function whitepaperLangs(): WPLang[] {
  return [...LANGS];
}

// Cross-reference maps derived from the content: figure label -> number, equation label -> tag,
// section label -> number. Used by the renderer to resolve inline {{fig:…}}/{{eq:…}}/{{sec:…}} tokens.
export type WPRefMaps = {
  fig: Record<string, number>;
  eq: Record<string, string>;
  sec: Record<string, number>;
};
export function whitepaperRefMaps(wp: Whitepaper): WPRefMaps {
  const fig: Record<string, number> = {};
  for (const f of wp.figures) fig[f.label] = f.n;
  const eq: Record<string, string> = {};
  const sec: Record<string, number> = {};
  for (const s of wp.sections) {
    sec[s.label] = s.number;
    for (const b of s.blocks) if (b.t === "eq") for (const it of b.items) eq[it.label] = it.n;
  }
  return { fig, eq, sec };
}

// Release manifest (version history + PDF SHA-256 hashes). Generated by tools/whitepaper-release.sh.
export type WPManifest = {
  version: string;
  released_at?: string;
  source_commit?: string;
  titles: { en: string; pt: string };
  authors: string[];
  publisher: string;
  license: string;
  canonical_language: string;
  translation_language: string;
  pdfs: { file: string; lang: string; sha256: string; bytes: number; pages?: number }[];
  history: { version: string; date: string; note: string }[];
};

export function getWhitepaperManifest(): WPManifest | null {
  try {
    const p = join(process.cwd(), "content", "whitepaper", "manifest.json");
    return JSON.parse(readFileSync(p, "utf8")) as WPManifest;
  } catch {
    return null;
  }
}
