//! banza-root-ceremony-cli (M2.1) — OFFLINE ceremony tooling for the custodians.
//!
//! SAFETY (enforced here, tested in `tests/cli.rs`):
//! - never writes a private key in the clear — the private seed is stored ONLY encrypted
//!   (ChaCha20-Poly1305; passphrase-derived key). A missing passphrase is refused.
//! - refuses to write key material into a Git worktree (a `.git` ancestor), unless `test_only` writes to
//!   a temp path OUTSIDE any worktree.
//! - never prints a private key, seed or passphrase; only the PUBLIC key + fingerprint leave the tool.
//! - verifies the 2-of-3 threshold and rejects 1-of-3 / duplicate custodian / forbidden scope via the
//!   `banza-root-ceremony` engine.
//! - NO network, NO HTTP, NO LLM.
//!
//! The M2 root establishes trust for the BANZA open financial protocol. It does not authorise payment
//! services, create operators, issue licences or move funds. Real production keys are generated by the
//! custodians on their own air-gapped machines; this tool never uploads or transmits anything.
//!
//! NOTE: the passphrase KDF here is iterated SHA-256 (adequate for offline TEST tooling). A production
//! ceremony should prefer a memory-hard KDF (Argon2id/scrypt) and hardware where available.

use banza_root_ceremony::{canonical_bytes, sign::TestKeypair, validate_root_ceremony};
use base64::Engine as _;
use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, Key, KeyInit, Nonce};
use ed25519_dalek::{Signer, SigningKey};
use rand::RngCore;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::Path;

pub const TEST_ONLY_MARKER: &str = "TEST ONLY — NOT PRODUCTION — NO REAL PRIVATE KEYS";
const KDF_ITERATIONS: u32 = 200_000;

#[derive(Debug, PartialEq)]
pub enum CliError {
    RefusedInGitWorktree(String),
    MissingPassphrase,
    PlaintextPrivateKeyRefused,
    BadPassphrase,
    Io(String),
    Malformed(String),
}

impl std::fmt::Display for CliError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CliError::RefusedInGitWorktree(p) => write!(
                f,
                "recuso escrever material de chave dentro de um Git worktree: {p}"
            ),
            CliError::MissingPassphrase => write!(
                f,
                "passphrase em falta — recuso escrever a private key sem encriptação"
            ),
            CliError::PlaintextPrivateKeyRefused => {
                write!(f, "recuso exportar/gravar a private key em claro")
            }
            CliError::BadPassphrase => write!(f, "passphrase inválida ou ficheiro corrompido"),
            CliError::Io(e) => write!(f, "io: {e}"),
            CliError::Malformed(e) => write!(f, "input malformado: {e}"),
        }
    }
}

fn b64(b: &[u8]) -> String {
    base64::engine::general_purpose::STANDARD_NO_PAD.encode(b)
}
fn unb64(s: &str) -> Option<Vec<u8>> {
    base64::engine::general_purpose::STANDARD_NO_PAD
        .decode(s)
        .ok()
}
fn b64url(b: &[u8]) -> String {
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(b)
}

/// True if `path` (or a parent) is inside a Git worktree (`.git` present).
pub fn is_in_git_worktree(path: &Path) -> bool {
    let mut p = path.to_path_buf();
    if p.is_relative() {
        if let Ok(cwd) = std::env::current_dir() {
            p = cwd.join(p);
        }
    }
    loop {
        if p.join(".git").exists() {
            return true;
        }
        if !p.pop() {
            return false;
        }
    }
}

/// Derive a 32-byte key from a passphrase (+ salt) via iterated SHA-256. TEST tooling KDF.
fn derive_key(passphrase: &str, salt: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(salt);
    h.update(passphrase.as_bytes());
    let mut out = h.finalize();
    for _ in 1..KDF_ITERATIONS {
        let mut hh = Sha256::new();
        hh.update(out);
        hh.update(salt);
        out = hh.finalize();
    }
    let mut k = [0u8; 32];
    k.copy_from_slice(&out);
    k
}

/// Encrypt a 32-byte Ed25519 seed with a passphrase → an encrypted-backup JSON blob (no plaintext key).
pub fn encrypt_seed(seed: &[u8; 32], passphrase: &str) -> Result<Value, CliError> {
    if passphrase.is_empty() {
        return Err(CliError::MissingPassphrase);
    }
    let mut salt = [0u8; 16];
    let mut nonce_bytes = [0u8; 12];
    rand::thread_rng().fill_bytes(&mut salt);
    rand::thread_rng().fill_bytes(&mut nonce_bytes);
    let key = derive_key(passphrase, &salt);
    let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
    let ct = cipher
        .encrypt(Nonce::from_slice(&nonce_bytes), seed.as_ref())
        .map_err(|_| CliError::Io("encrypt failed".into()))?;
    Ok(json!({
        "kdf": "sha256-iter",
        "iterations": KDF_ITERATIONS,
        "cipher": "chacha20poly1305",
        "salt": b64(&salt),
        "nonce": b64(&nonce_bytes),
        "ciphertext": b64(&ct),
        "note": format!("{TEST_ONLY_MARKER}. Encrypted private key seed — NOT plaintext. Keep the passphrase OFF this medium."),
    }))
}

/// Decrypt an encrypted-backup blob back to the 32-byte seed (used only offline, never printed).
pub fn decrypt_seed(blob: &Value, passphrase: &str) -> Result<[u8; 32], CliError> {
    if passphrase.is_empty() {
        return Err(CliError::MissingPassphrase);
    }
    let salt = blob
        .get("salt")
        .and_then(|x| x.as_str())
        .and_then(unb64)
        .ok_or(CliError::BadPassphrase)?;
    let nonce = blob
        .get("nonce")
        .and_then(|x| x.as_str())
        .and_then(unb64)
        .ok_or(CliError::BadPassphrase)?;
    let ct = blob
        .get("ciphertext")
        .and_then(|x| x.as_str())
        .and_then(unb64)
        .ok_or(CliError::BadPassphrase)?;
    let key = derive_key(passphrase, &salt);
    let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
    let pt = cipher
        .decrypt(Nonce::from_slice(&nonce), ct.as_ref())
        .map_err(|_| CliError::BadPassphrase)?;
    if pt.len() != 32 {
        return Err(CliError::BadPassphrase);
    }
    let mut s = [0u8; 32];
    s.copy_from_slice(&pt);
    Ok(s)
}

/// Public, non-secret result of `keygen`. The private key never appears here.
#[derive(Debug)]
pub struct KeygenOutput {
    pub public_key_b64url: String,
    pub fingerprint: String,
    pub encrypted_backup: Value,
}

/// Generate an Ed25519 keypair. The private seed is returned ONLY encrypted. Refuses a Git worktree
/// destination (unless test_only) and refuses an empty passphrase. Never returns/prints the private key.
pub fn keygen(
    dest_dir: &Path,
    passphrase: &str,
    test_only: bool,
) -> Result<KeygenOutput, CliError> {
    if passphrase.is_empty() {
        return Err(CliError::MissingPassphrase);
    }
    if is_in_git_worktree(dest_dir) && !test_only {
        return Err(CliError::RefusedInGitWorktree(
            dest_dir.display().to_string(),
        ));
    }
    if test_only && is_in_git_worktree(dest_dir) {
        // Even test-only material must not land in a worktree.
        return Err(CliError::RefusedInGitWorktree(
            dest_dir.display().to_string(),
        ));
    }
    let mut seed = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut seed);
    let signing = SigningKey::from_bytes(&seed);
    let public = signing.verifying_key().to_bytes();
    let encrypted_backup = encrypt_seed(&seed, passphrase)?;
    // seed is dropped here; it is never written in the clear or printed.
    Ok(KeygenOutput {
        public_key_b64url: b64url(&public),
        fingerprint: fingerprint_of(&b64url(&public)),
        encrypted_backup,
    })
}

pub fn fingerprint_of(pub_b64url: &str) -> String {
    match base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(pub_b64url) {
        Ok(b) => format!("{:x}", Sha256::digest(&b))[..32].to_string(),
        Err(_) => "invalid".to_string(),
    }
}

/// Sign root metadata (canonical, minus `signatures`) with an encrypted key. Returns a signature entry.
/// The private key is decrypted in memory only and never printed/returned.
pub fn sign_metadata(
    meta_without_sigs: &Value,
    enc_blob: &Value,
    passphrase: &str,
    key_id: &str,
    custodian: &str,
) -> Result<Value, CliError> {
    let seed = decrypt_seed(enc_blob, passphrase)?;
    let signing = SigningKey::from_bytes(&seed);
    let msg = canonical_bytes(meta_without_sigs, &["signatures"]);
    let sig = signing.sign(&msg);
    Ok(json!({ "key_id": key_id, "custodian": custodian, "signature": b64url(&sig.to_bytes()) }))
}

/// Verify a full ceremony input with the engine, returning its status string.
pub fn verify_ceremony(input: &Value) -> String {
    validate_root_ceremony(input)["status"]
        .as_str()
        .unwrap_or("M2_ROOT_CEREMONY_INVALID_REGULATORY_BOUNDARY")
        .to_string()
}

/// TEST-ONLY recovery test: decrypt, re-derive the public key, confirm it matches `expected_pub`, sign a
/// TEST-ONLY document and verify it. Never prints the key. Returns Ok(true) on success.
pub fn recovery_test(
    enc_blob: &Value,
    passphrase: &str,
    expected_pub_b64url: &str,
) -> Result<bool, CliError> {
    let seed = decrypt_seed(enc_blob, passphrase)?;
    let signing = SigningKey::from_bytes(&seed);
    let got_pub = b64url(&signing.verifying_key().to_bytes());
    if got_pub != expected_pub_b64url {
        return Ok(false);
    }
    // sign + verify a TEST-ONLY doc using the deterministic verifier path
    let doc = json!({ "recovery_test": TEST_ONLY_MARKER });
    let msg = canonical_bytes(&doc, &[]);
    let sig = signing.sign(&msg);
    Ok(banza_root_ceremony::verify_ed25519(
        &got_pub,
        &msg,
        &b64url(&sig.to_bytes()),
    ))
}

/// A TEST-ONLY deterministic keypair (used by docs/tests only — never a real key).
pub fn test_keypair(label: &str) -> TestKeypair {
    TestKeypair::from_seed(label.as_bytes())
}
