-- BANZA — telemetry precision: execution-kind classification + monotonic sub-ms duration (BZO-9, ADR-042).
--
-- Idempotent migration that extends the EXISTING receipt-store schema (M2_19H) with two telemetry
-- precisions, WITHOUT ever mutating a frozen receipt row:
--   (1) execution-kind classification — so a duration aggregate distinguishes genuine USER_REQUESTED
--       journeys from SYSTEM_E2E / BENCHMARK / UNCLASSIFIED runs (an instrumentation campaign must never
--       be averaged in as if it were a user journey). Historical rows stay NULL (unclassified — we do NOT
--       assume they are user runs); the immutable side table `validation_execution_kind_attestations`
--       records a kind for an already-frozen row without ever UPDATE-ing it.
--   (2) monotonic microsecond duration — `duration_us` columns hold a `process.hrtime.bigint()`-derived
--       measurement, so a sub-millisecond step no longer reads as "0 ms" and a backwards wall clock can
--       never yield a negative duration. Historical rows (no duration_us) fall back to wall-clock at read.
--
-- Safe to run repeatedly. Adds only NEW columns/tables/indexes/triggers/grants — no ALTER-that-loses-data,
-- no DROP of an existing object, no UPDATE of a frozen row. Apply on the host (human-gated deploy), after a
-- verified backup:
--   docker compose exec -T postgres psql -U banza_admin -d banza_protocol -f /migrations/BZO9_telemetry_precision.sql

BEGIN;

-- (1) execution-kind classification columns (nullable — historical rows stay NULL = unclassified).
ALTER TABLE validation_executions ADD COLUMN IF NOT EXISTS execution_kind text;
ALTER TABLE validation_executions ADD COLUMN IF NOT EXISTS trigger_source text;
ALTER TABLE validation_executions ADD COLUMN IF NOT EXISTS measurement_campaign_id text;
ALTER TABLE validation_executions ADD COLUMN IF NOT EXISTS initiated_by text;

-- (2) monotonic microsecond duration (nullable — historical rows fall back to wall-clock at read).
ALTER TABLE validation_executions ADD COLUMN IF NOT EXISTS duration_us bigint;
ALTER TABLE validation_step_executions ADD COLUMN IF NOT EXISTS duration_us bigint;

-- Immutability-preserving side table: attest the kind of an ALREADY-FROZEN execution row without ever
-- UPDATE-ing it (that would trip banza_execution_freeze). Append-only, one attestation per execution.
CREATE TABLE IF NOT EXISTS validation_execution_kind_attestations (
  attestation_id bigserial PRIMARY KEY,
  execution_id text NOT NULL REFERENCES validation_executions(execution_id),
  execution_kind text NOT NULL,
  measurement_campaign_id text,
  evidence text,
  attested_by text,
  attested_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (execution_id));
CREATE INDEX IF NOT EXISTS validation_execution_kind_attestations_exec_idx
  ON validation_execution_kind_attestations (execution_id);

-- Append-only: reuse the existing immutability function (M2_19H). No UPDATE/DELETE of an attestation.
DROP TRIGGER IF EXISTS validation_execution_kind_attestations_immutable ON validation_execution_kind_attestations;
CREATE TRIGGER validation_execution_kind_attestations_immutable
  BEFORE UPDATE OR DELETE ON validation_execution_kind_attestations
  FOR EACH ROW EXECUTE FUNCTION banza_forbid_receipt_mutation();

-- Retroactive attestation seed (unequivocal, evidence-bearing): every orchestrator_version='1.1.0' public
-- Operador Zero execution existing at migration time was generated by the BZO-8 instrumentation campaign on
-- 2026-08-05 (1.1.0 was deployed that day; no real user ran a journey in that window). We attest the kind on
-- the immutable SIDE table — we do NOT UPDATE the frozen execution rows (that trigger would reject it; this
-- is the whole point of the side table).
INSERT INTO validation_execution_kind_attestations
  (execution_id, execution_kind, measurement_campaign_id, evidence, attested_by)
SELECT execution_id, 'SYSTEM_E2E', 'bzo8-instrumentation-2026-08-05',
       'Generated by the BZO-8 instrumentation-validation campaign (2026-08-05); orchestrator_version 1.1.0 deployed same day, no user journeys in window.',
       'bzo9-migration'
  FROM validation_executions
 WHERE workspace = 'public' AND operator_id = 'operator-zero' AND orchestrator_version = '1.1.0'
 ON CONFLICT (execution_id) DO NOTHING;

-- Grants (idempotent). The new base-table columns need no extra grant (banzai_rw already has
-- SELECT/INSERT/UPDATE on validation_executions/validation_step_executions). The attestation side table is
-- append-only: SELECT/INSERT only, plus USAGE/SELECT on its sequence.
GRANT SELECT, INSERT ON validation_execution_kind_attestations TO banzai_rw;
GRANT USAGE, SELECT ON SEQUENCE validation_execution_kind_attestations_attestation_id_seq TO banzai_rw;

COMMIT;
