import type { Locale } from "@/lib/i18n";

// The per-answer provenance line, in the reader's own language.
//
// This copy was Portuguese template literals inside the ask adapter, with no locale anywhere in scope. On
// the English surface a reader got an English question, English suggestions, English chrome — and then
// "Resposta determinística · sem chamada ao modelo · 2 fontes" underneath the answer. The line that exists
// to tell someone how their answer was produced was itself in a language they had not asked for.
//
// Every entry states the same fact in both editions. These are honesty statements about execution — which
// engine ran, whether a model was called, how many sources — so a missing or approximate translation is
// not acceptable here in a way it might be for marketing copy.

export type Localized = Readonly<Record<Locale, string>>;
const L = (pt: string, en: string): Localized => Object.freeze({ pt, en });

export const ASK_STATUS_COPY = {
  // Counted units, joined into the line below.
  "unit.source": L("fonte", "source"),
  "unit.sources": L("fontes", "sources"),

  // The provenance line itself.
  "status.withContext": L("com contexto", "with context"),
  "status.deterministic": L("Resposta determinística · sem chamada ao modelo", "Deterministic answer · no model call"),
  "status.postValidation": L(
    "Resposta determinística · resposta do modelo substituída pela validação",
    "Deterministic answer · the model's answer was replaced by validation",
  ),
  "status.documentNotFound": L("Documento não encontrado · sem chamada ao modelo", "Document not found · no model call"),
  "status.insufficientEvidence": L("Evidência insuficiente · sem chamada ao modelo", "Insufficient evidence · no model call"),
  "status.localModel": L("Gerado por Qwen local", "Generated by local Qwen"),
  "status.externalCalls": L("chamadas externas: 0", "external calls: 0"),
  "status.cachedLocal": L(
    "Resposta em cache (Qwen local) · sem nova chamada ao modelo",
    "Cached answer (local Qwen) · no new model call",
  ),

  // Degraded statuses, keyed by the backend's fallback_reason. The mode IS degraded, and each states its
  // real cause rather than a blanket "the model was unavailable".
  "degraded.unavailable": L(
    "Fallback seguro · modelo indisponível · sem chamada externa",
    "Safe fallback · model unavailable · no external call",
  ),
  "degraded.timeout": L(
    "Fallback seguro · tempo limite excedido · sem chamada externa",
    "Safe fallback · timed out · no external call",
  ),
  "degraded.capacity": L(
    "Fallback seguro · capacidade temporariamente ocupada · sem chamada externa",
    "Safe fallback · capacity temporarily busy · no external call",
  ),
  "degraded.unvalidated": L(
    "Fallback seguro · resposta não validada · sem chamada externa",
    "Safe fallback · answer not validated · no external call",
  ),
  "degraded.incomplete": L(
    "Fallback seguro · resposta incompleta para a tarefa · sem chamada externa",
    "Safe fallback · answer incomplete for the task · no external call",
  ),
  "degraded.intentDeferred": L(
    "Resposta determinística a partir das fontes · sem chamada ao modelo",
    "Deterministic answer from the sources · no model call",
  ),
  "degraded.default": L(
    "Fallback seguro · erro temporário · sem chamada externa",
    "Safe fallback · temporary error · no external call",
  ),

  // Availability states. These are not chrome: `outage.*.text` becomes the ANSWER the reader sees, so an
  // English reader whose request timed out was being told so in Portuguese, in the answer bubble itself.
  // Safe and non-technical in both editions — never a stack trace, never internal architecture.
  "outage.busy.text": L(
    "O BanzAI está a processar muitos pedidos neste momento. Tenta novamente dentro de alguns segundos.",
    "BanzAI is handling a lot of requests right now. Try again in a few seconds.",
  ),
  "outage.busy.status": L("BanzAI ocupado · muitos pedidos", "BanzAI busy · many requests"),
  "outage.timeout.text": L(
    "A resposta demorou mais do que o esperado. Tenta novamente ou reformula a pergunta.",
    "The answer took longer than expected. Try again, or rephrase the question.",
  ),
  "outage.timeout.status": L("Tempo de resposta excedido", "Response timed out"),
  "outage.rate_limited.text": L(
    "Muitos pedidos em pouco tempo. Aguarda alguns segundos e tenta novamente.",
    "Too many requests in a short time. Wait a few seconds and try again.",
  ),
  "outage.rate_limited.status": L("Demasiados pedidos", "Too many requests"),
  "outage.unavailable.text": L(
    "O BanzAI está temporariamente indisponível. Tenta novamente dentro de instantes.",
    "BanzAI is temporarily unavailable. Try again in a moment.",
  ),
  "outage.unavailable.status": L("Temporariamente indisponível", "Temporarily unavailable"),

  // ADR-036 — the model answered, the authority validator rejected it, and the deterministic sources were
  // served instead. The reader is told which of those happened.
  "status.postValidationLimit": L(
    "Fallback seguro — resposta não validada (limite de autoridade) — sem chamada externa",
    "Safe fallback — answer not validated (authority limit) — no external call",
  ),
  "answer.postValidationLimit": L(
    "Resposta em modo degradado: a resposta do modelo não passou a validação de autoridade (ADR-036); resposta determinística a partir das fontes do protocolo.",
    "Degraded mode: the model's answer did not pass authority validation (ADR-036); this is a deterministic answer from the protocol sources.",
  ),

  // ADR-036 — an operational duration question with no comparable data. Distinct from insufficient
  // evidence, and it must not borrow that wording in either edition.
  "status.insufficientMeasurements": L(
    "Sem medições suficientes · sem chamada ao modelo",
    "Not enough measurements · no model call",
  ),
} as const;

export type AskStatusId = keyof typeof ASK_STATUS_COPY;

export function askStatus(id: AskStatusId, locale: Locale): string {
  return ASK_STATUS_COPY[id][locale];
}

/** "2 fontes" / "2 sources" — the count and its unit, agreed in the reader's language. */
export function sourcesLabel(n: number, locale: Locale): string {
  return `${n} ${askStatus(n === 1 ? "unit.source" : "unit.sources", locale)}`;
}

/** The degraded status for a backend `fallback_reason`, in the reader's language. */
export function degradedStatus(reason: string, locale: Locale): string {
  const BY_REASON: Record<string, AskStatusId> = {
    local_inference_unavailable: "degraded.unavailable",
    local_inference_timeout: "degraded.timeout",
    synthesis_capacity_tripped: "degraded.capacity",
    synthesis_output_unvalidated: "degraded.unvalidated",
    synthesis_task_incomplete: "degraded.incomplete",
    intent_deferred: "degraded.intentDeferred",
  };
  return askStatus(BY_REASON[reason] ?? "degraded.default", locale);
}
