import type { Locale } from "@/lib/i18n";

// The per-answer provenance line, in the reader's own language.
//
// This copy was Portuguese template literals inside the ask adapter, with no locale anywhere in scope. On
// the English surface a reader got an English question, English suggestions, English chrome — and then
// "Resposta determinística · sem chamada ao modelo · 2 fontes" underneath the answer. The line that exists
// to tell someone how their answer was produced was itself in a language they had not asked for.
//
// Every entry states the same fact in both editions. These are honesty statements about execution — which
// engine ran, whether a model was called, how many sources — so a missing or approximate translation is
// not acceptable here in a way it might be for marketing copy.

export type Localized = Readonly<Record<Locale, string>>;
const L = (pt: string, en: string): Localized => Object.freeze({ pt, en });

export const ASK_STATUS_COPY = {
  // Counted units, joined into the line below.
  "unit.source": L("fonte", "source"),
  "unit.sources": L("fontes", "sources"),

  // The provenance line itself.
  "status.withContext": L("com contexto", "with context"),
  "status.deterministic": L("Resposta determinística · sem chamada ao modelo", "Deterministic answer · no model call"),
  "status.postValidation": L(
    "Resposta determinística · resposta do modelo substituída pela validação",
    "Deterministic answer · the model's answer was replaced by validation",
  ),
  "status.documentNotFound": L("Documento não encontrado · sem chamada ao modelo", "Document not found · no model call"),
  "status.insufficientEvidence": L("Evidência insuficiente · sem chamada ao modelo", "Insufficient evidence · no model call"),
  "status.localModel": L("Gerado por Qwen local", "Generated by local Qwen"),
  "status.externalCalls": L("chamadas externas: 0", "external calls: 0"),
  "status.cachedLocal": L(
    "Resposta em cache (Qwen local) · sem nova chamada ao modelo",
    "Cached answer (local Qwen) · no new model call",
  ),

  // Degraded statuses, keyed by the backend's fallback_reason. The mode IS degraded, and each states its
  // real cause rather than a blanket "the model was unavailable".
  "degraded.unavailable": L(
    "Fallback seguro · modelo indisponível · sem chamada externa",
    "Safe fallback · model unavailable · no external call",
  ),
  "degraded.timeout": L(
    "Fallback seguro · tempo limite excedido · sem chamada externa",
    "Safe fallback · timed out · no external call",
  ),
  "degraded.capacity": L(
    "Fallback seguro · capacidade temporariamente ocupada · sem chamada externa",
    "Safe fallback · capacity temporarily busy · no external call",
  ),
  "degraded.unvalidated": L(
    "Fallback seguro · resposta não validada · sem chamada externa",
    "Safe fallback · answer not validated · no external call",
  ),
  "degraded.incomplete": L(
    "Fallback seguro · resposta incompleta para a tarefa · sem chamada externa",
    "Safe fallback · answer incomplete for the task · no external call",
  ),
  "degraded.intentDeferred": L(
    "Resposta determinística a partir das fontes · sem chamada ao modelo",
    "Deterministic answer from the sources · no model call",
  ),
  "degraded.default": L(
    "Fallback seguro · erro temporário · sem chamada externa",
    "Safe fallback · temporary error · no external call",
  ),
} as const;

export type AskStatusId = keyof typeof ASK_STATUS_COPY;

export function askStatus(id: AskStatusId, locale: Locale): string {
  return ASK_STATUS_COPY[id][locale];
}

/** "2 fontes" / "2 sources" — the count and its unit, agreed in the reader's language. */
export function sourcesLabel(n: number, locale: Locale): string {
  return `${n} ${askStatus(n === 1 ? "unit.source" : "unit.sources", locale)}`;
}

/** The degraded status for a backend `fallback_reason`, in the reader's language. */
export function degradedStatus(reason: string, locale: Locale): string {
  const BY_REASON: Record<string, AskStatusId> = {
    local_inference_unavailable: "degraded.unavailable",
    local_inference_timeout: "degraded.timeout",
    synthesis_capacity_tripped: "degraded.capacity",
    synthesis_output_unvalidated: "degraded.unvalidated",
    synthesis_task_incomplete: "degraded.incomplete",
    intent_deferred: "degraded.intentDeferred",
  };
  return askStatus(BY_REASON[reason] ?? "degraded.default", locale);
}
