// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// The canonical profile vocabulary, derived from the single normative source:
//   contracts/production/conformance-profiles.production.json
//
// A profile is a technical capability an implementation demonstrates. It is never a certification
// state, an operational status, a regulatory permission or a production approval, and a profile
// NAME must never encode one — see docs/governance/certification-boundary.md.
//
// Regenerate with `make canonical-profiles-rs`; `make profile-vocabulary-check` fails if this file
// and the registry disagree.

/// One conformance profile: its identifier and its canonical name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanonicalProfile {
    pub level: &'static str,
    pub name: &'static str,
}

/// Every profile the protocol defines, in registry order.
///
/// `rustfmt::skip` keeps this table one row per profile. Without it, formatting rewrites the
/// generated file and it stops matching a fresh generation — two truths again, which is the whole
/// thing this file exists to prevent.
#[rustfmt::skip]
pub const CANONICAL_PROFILES: [CanonicalProfile; 5] = [
    CanonicalProfile { level: "L0", name: "Protocol Sandbox" },
    CanonicalProfile { level: "L1", name: "Core Payment Capability" },
    CanonicalProfile { level: "L2", name: "Payment Initiation Capability" },
    CanonicalProfile { level: "L3", name: "Inter-Operator Interoperability" },
    CanonicalProfile { level: "L4", name: "External Interoperability" },
];

/// The canonical name for a profile identifier, or `None` if it is not a profile.
///
/// Unknown identifiers do not resolve by guesswork: an alias is valid only if the registry
/// registers it, and the registry registers none.
pub fn canonical_name(level: &str) -> Option<&'static str> {
    CANONICAL_PROFILES
        .iter()
        .find(|p| p.level == level)
        .map(|p| p.name)
}
