//! Golden parity: the Rust trace verifier must produce the SAME result (deep value equality) as the
//! TypeScript `explainTrace` it replaces. `tests/golden/trace.json` was generated by running the real
//! TS on these exact inputs (see the R10 report). Comparison is value-based (object key order is
//! irrelevant, matching how Hono/`c.json` serialize).

use banzai_trace::explain_trace;
use serde_json::{json, Value};

fn golden() -> Value {
    let raw = std::fs::read_to_string(format!(
        "{}/tests/golden/trace.json",
        env!("CARGO_MANIFEST_DIR")
    ))
    .expect("read golden");
    serde_json::from_str(&raw).expect("parse golden")
}

fn sample() -> Value {
    json!({
        "trace_id": "tr_abc123",
        "qr": { "entity_id": "qr_001", "type": "qr", "trace_id": "tr_abc123", "status": "paid", "amount_minor": 5000, "currency": "AOA" },
        "transfer": { "entity_id": "txf_001", "type": "transfer", "trace_id": "tr_abc123", "gross_minor": 5000, "net_minor": 4950, "fee_minor": 50, "status": "completed", "currency": "AOA" }
    })
}

fn rust_result(input: &Value) -> Value {
    // reference_operator_url = None mirrors the harness (env unset).
    serde_json::to_value(explain_trace(input, None)).unwrap()
}

fn assert_case(name: &str, input: Value) {
    let g = golden();
    let expected = g
        .get(name)
        .unwrap_or_else(|| panic!("golden missing case {name}"));
    let actual = rust_result(&input);
    assert_eq!(&actual, expected, "case `{name}` diverged from TS golden");
}

#[test]
fn parity_empty() {
    assert_case("empty", json!({}));
}

#[test]
fn parity_lookup() {
    assert_case("lookup", json!({ "trace_id": "tr_lookup_test" }));
}

#[test]
fn parity_qr() {
    assert_case("qr", json!({ "trace": sample() }));
}

#[test]
fn parity_badtrace() {
    let mut s = sample();
    s["transfer"]["trace_id"] = json!("tr_DIFFERENT");
    assert_case("badtrace", json!({ "trace": s }));
}

#[test]
fn parity_badstl() {
    let mut s = sample();
    s["transfer"]["fee_minor"] = json!(100);
    assert_case("badstl", json!({ "trace": s }));
}

#[test]
fn parity_ledgerflow() {
    let flow = json!({
        "trace_id": "tr_x",
        "transfer": { "entity_id": "txf_9", "type": "transfer", "trace_id": "tr_x", "gross_minor": 1000, "net_minor": 990, "fee_minor": 10 },
        "ledger_entries": [
            { "entity_id": "led_1", "type": "ledger_entry", "trace_id": "tr_x", "type2": "DEBIT" },
            { "entity_id": "led_2", "type": "ledger_entry", "trace_id": "tr_x" }
        ]
    });
    assert_case("ledgerflow", json!({ "trace": flow }));
}

#[test]
fn parity_arr() {
    let arr = json!([
        { "entity_id": "pr_1", "type": "payment_request", "trace_id": "tr_p" },
        { "entity_id": "txf_2", "type": "transfer", "trace_id": "tr_p" }
    ]);
    assert_case("arr", json!({ "trace": arr }));
}

#[test]
fn parity_raw_object() {
    assert_case(
        "raw_object",
        json!({ "trace": { "entity_id": "wal_1", "status": "active" } }),
    );
}
