#!/usr/bin/env python3
"""Derive the canonical L0-L4 profile vocabulary into a Rust constant.

There is exactly one normative definition of what each conformance profile is called:
contracts/production/conformance-profiles.production.json. Any second hand-maintained table is a
drift path — one of them will be edited and the other will not, and the stale one will be the one
a reader sees. That already happened: the conformance engine carried L4 as "Produção certificada"
while the registry said "External Interoperability".

The engine compiles to WASM and has no filesystem at runtime, so it cannot read the registry when
it runs. Generating a small constant at source level is the smallest mechanism that makes the
duplication impossible to diverge: the file is derived, checked byte-for-byte against a fresh
generation, and never hand-edited.

Writes engines/banza-conformance/src/canonical_profiles.rs. Output is a pure function of the
registry: no timestamps, no host paths, no environment.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = 'contracts/production/conformance-profiles.production.json'
TARGET = 'engines/banza-conformance/src/canonical_profiles.rs'

HEADER = '''// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// The canonical profile vocabulary, derived from the single normative source:
//   {registry}
//
// A profile is a technical capability an implementation demonstrates. It is never a certification
// state, an operational status, a regulatory permission or a production approval, and a profile
// NAME must never encode one — see docs/governance/certification-boundary.md.
//
// Regenerate with `make canonical-profiles-rs`; `make profile-vocabulary-check` fails if this file
// and the registry disagree.

/// One conformance profile: its identifier and its canonical name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanonicalProfile {{
    pub level: &'static str,
    pub name: &'static str,
}}

/// Every profile the protocol defines, in registry order.
///
/// `rustfmt::skip` keeps this table one row per profile. Without it, formatting rewrites the
/// generated file and it stops matching a fresh generation — two truths again, which is the whole
/// thing this file exists to prevent.
#[rustfmt::skip]
pub const CANONICAL_PROFILES: [CanonicalProfile; {count}] = [
'''

FOOTER = '''];

/// The canonical name for a profile identifier, or `None` if it is not a profile.
///
/// Unknown identifiers do not resolve by guesswork: an alias is valid only if the registry
/// registers it, and the registry registers none.
pub fn canonical_name(level: &str) -> Option<&'static str> {
    CANONICAL_PROFILES
        .iter()
        .find(|p| p.level == level)
        .map(|p| p.name)
}
'''


def rust_str(s):
    if '"' in s or '\\' in s or '\n' in s:
        raise SystemExit('profile name is not a plain string literal: %r' % s)
    return '"%s"' % s


def main():
    reg = json.load(open(os.path.join(ROOT, REGISTRY), encoding='utf-8'))
    profiles = reg['profiles']
    if not profiles:
        raise SystemExit('registry declares no profiles')

    rows = []
    seen = set()
    for p in profiles:
        level, name = p['level'], p['name']
        if level in seen:
            raise SystemExit('duplicate profile level in registry: %s' % level)
        seen.add(level)
        rows.append('    CanonicalProfile { level: %s, name: %s },\n'
                    % (rust_str(level), rust_str(name)))

    out = HEADER.format(registry=REGISTRY, count=len(rows)) + ''.join(rows) + FOOTER

    dest = os.path.join(ROOT, TARGET)
    if len(sys.argv) > 1 and sys.argv[1] == '--stdout':
        sys.stdout.write(out)
        return
    with open(dest, 'w', encoding='utf-8') as fh:
        fh.write(out)
    print('  wrote %s  (%d profiles from %s)' % (TARGET, len(rows), REGISTRY))


if __name__ == '__main__':
    main()
