#!/usr/bin/env python3
"""Generate the Rust locator -> semantic item_id table from the JS realization catalogue.

Rust decides WHICH facts a tasked answer contains; the catalogue decides how each is worded per locale.
For Rust to name those facts semantically it needs the same locator->item_id relation the catalogue
already declares — and a second hand-maintained copy of 129 pairs is a drift path whose failure mode is
Rust naming one fact while the catalogue words another.

So the table is GENERATED from `services/banzai-api/src/taskedRealizations.js`, which is the single
place the relation is authored.

Regenerate:  python3 tools/gen-tasked-item-ids-rs.py
"""
import re

CATALOGUE = "services/banzai-api/src/taskedRealizations.js"
OUT = "engines/banzai-query-core/src/tasked_item_ids.generated.rs"

src = open(CATALOGUE, encoding="utf-8").read()
pairs = re.findall(r'\n  "([a-z0-9_.]+)": \{\n    locator: "([a-z0-9_.]+)",', src)
if not pairs:
    raise SystemExit("no item_id/locator pairs found — the catalogue shape changed")
if len({p[0] for p in pairs}) != len(pairs):
    raise SystemExit("duplicate item_id in the catalogue")
if len({p[1] for p in pairs}) != len(pairs):
    raise SystemExit("duplicate locator in the catalogue")

rows = "\n".join(f'    ("{loc}", "{item}"),' for item, loc in sorted(pairs, key=lambda p: p[1]))
open(OUT, "w", encoding="utf-8").write(
    "// @generated by tools/gen-tasked-item-ids-rs.py — do not edit.\n"
    "//\n"
    "// Maps a tasked item's SOURCE COORDINATE (subject.task.section[.index]) to its stable SEMANTIC\n"
    "// IDENTITY. The coordinate moves when a step is inserted; the identity does not, which is why the\n"
    "// plan that crosses the WASM boundary carries the identity and not the coordinate.\n"
    "//\n"
    "// Authored in services/banzai-api/src/taskedRealizations.js, generated here, so the engine and the\n"
    "// realization catalogue cannot disagree about which fact a name refers to.\n\n"
    f"pub const TASKED_ITEM_IDS: &[(&str, &str)] = &[\n{rows}\n];\n\n"
    "/// The semantic identity of the item at `locator`, or None when the coordinate is unknown.\n"
    "pub fn item_id_for(locator: &str) -> Option<&'static str> {\n"
    "    TASKED_ITEM_IDS\n"
    "        .iter()\n"
    "        .find(|(loc, _)| *loc == locator)\n"
    "        .map(|(_, id)| *id)\n"
    "}\n"
)
print(f"{len(pairs)} locator -> item_id pairs -> {OUT}")
