#!/usr/bin/env python3
"""Derive the canonical L0-L4 profile vocabulary into a Rust constant.

There is exactly one normative definition of what each conformance profile is called:
contracts/production/conformance-profiles.production.json. Any second hand-maintained table is a
drift path — one of them will be edited and the other will not, and the stale one will be the one
a reader sees. That already happened: the conformance engine carried L4 as "Produção certificada"
while the registry said "External Interoperability".

The engine compiles to WASM and has no filesystem at runtime, so it cannot read the registry when
it runs. Generating a small constant at source level is the smallest mechanism that makes the
duplication impossible to diverge: the file is derived, checked byte-for-byte against a fresh
generation, and never hand-edited.

Writes two derived files, both pure functions of the registry — no timestamps, no host paths, no
environment:

  engines/banza-conformance/src/canonical_profiles.rs        the conformance engine's vocabulary
  website/lib/canonicalProfiles.generated.ts                 the website's vocabulary
  engines/banzai-query-core/src/canonical_profiles.generated.rs  what BanzAI may say about profiles

BanzAI needs its own copy for the same packaging reason as the website: the query engine compiles to
WASM with no filesystem, so it cannot read the registry when it answers. It also needs the CLOSED set
to refuse an unregistered identifier — measured, "What is the L7 conformance profile?" resolved a
confident definition of conformance, so a profile-shaped token outside the registry became a real
profile by lexical similarity. Knowing which levels exist is what makes refusing possible.

The website needs its own copy because its Docker build context is `website/` alone: `contracts/` is
not inside it, so the site cannot read the registry at build time. That is a packaging fact, not a
licence to hand-maintain a second table — the file is generated, byte-compared against a fresh
generation, and never edited.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = 'contracts/production/conformance-profiles.production.json'
TARGET = 'engines/banza-conformance/src/canonical_profiles.rs'
TS_TARGET = 'website/lib/canonicalProfiles.generated.ts'
KB_TARGET = 'engines/banzai-query-core/src/canonical_profiles.generated.rs'

HEADER = '''// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// The canonical profile vocabulary, derived from the single normative source:
//   {registry}
//
// A profile is a technical capability an implementation demonstrates. It is never a certification
// state, an operational status, a regulatory permission or a production approval, and a profile
// NAME must never encode one — see docs/governance/certification-boundary.md.
//
// Regenerate with `make canonical-profiles-rs`; `make profile-vocabulary-check` fails if this file
// and the registry disagree.

/// One conformance profile: its identifier and its canonical name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CanonicalProfile {{
    pub level: &'static str,
    pub name: &'static str,
}}

/// Every profile the protocol defines, in registry order.
///
/// `rustfmt::skip` keeps this table one row per profile. Without it, formatting rewrites the
/// generated file and it stops matching a fresh generation — two truths again, which is the whole
/// thing this file exists to prevent.
#[rustfmt::skip]
pub const CANONICAL_PROFILES: [CanonicalProfile; {count}] = [
'''

FOOTER = '''];

/// The canonical name for a profile identifier, or `None` if it is not a profile.
///
/// Unknown identifiers do not resolve by guesswork: an alias is valid only if the registry
/// registers it, and the registry registers none.
pub fn canonical_name(level: &str) -> Option<&'static str> {
    CANONICAL_PROFILES
        .iter()
        .find(|p| p.level == level)
        .map(|p| p.name)
}
'''


KB_HEADER = '''// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// What BanzAI may say about conformance profiles, derived from the single normative source:
//   {registry}
//
// Two things come from here, and both need the CLOSED set rather than a list of names:
//
//   the profiles BanzAI states           — L0..Ln, exactly as the registry names them
//   the identifiers BanzAI REFUSES       — anything profile-shaped that the registry does not register
//
// The second is why this file exists. Measured before it did: "What is the L7 conformance profile?"
// resolved a confident definition of conformance, so an identifier the protocol never published became
// a real profile through lexical similarity. An engine that cannot enumerate what exists cannot decline
// what does not.
//
// A profile is a technical capability an implementation demonstrates. It is never a certification state,
// an operational status, a regulatory permission or a production approval, and a profile NAME must never
// encode one — see docs/governance/certification-boundary.md.

/// One profile, exactly as the normative registry names it.
pub struct CanonicalProfile {{
    /// The profile identifier. A machine token: never translated.
    pub level: &'static str,
    /// The canonical name, from the normative registry. Never translated, never localised.
    pub name: &'static str,
}}

#[rustfmt::skip]
pub const CANONICAL_PROFILES: [CanonicalProfile; {count}] = [
'''

KB_FOOTER = '''];

/// The canonical name for a profile identifier, or `None` when the registry does not register it.
///
/// Case-insensitive on the IDENTIFIER only. The registry writes "L0"; a normalized query carries "l0",
/// and comparing them literally made every profile look unregistered — measured, that turned seven
/// published facts into refusals while the guard reported success at refusing L7. The NAME is never
/// case-folded: it is canonical text, returned exactly as the registry writes it.
pub fn canonical_name(level: &str) -> Option<&'static str> {
    CANONICAL_PROFILES
        .iter()
        .find(|p| p.level.eq_ignore_ascii_case(level))
        .map(|p| p.name)
}

/// True when `level` is a profile the protocol actually publishes.
pub fn is_registered(level: &str) -> bool {
    canonical_name(level).is_some()
}

/// A profile-shaped token in `nq` that the registry does NOT register, if any.
///
/// Profile-shaped means `l` followed by digits — the form the protocol uses. The check is deliberately
/// exact: an unregistered identifier is never corrected into a registered one, because "L7" is not a
/// misspelling of "L4", it is a question about something that does not exist. Fuzzy-matching canonical
/// identifiers is what would turn that into a confident wrong answer.
pub fn unregistered_profile_token(nq: &str) -> Option<String> {
    nq.split(|c: char| !c.is_alphanumeric())
        .find(|t| {
            let t = t.to_ascii_lowercase();
            t.len() >= 2
                && t.starts_with('l')
                && t[1..].chars().all(|c| c.is_ascii_digit())
                && !is_registered(&t)
        })
        .map(|t| t.to_ascii_lowercase())
}
'''


TS_HEADER = '''// GENERATED by tools/gen-canonical-profiles-rs.py — do not edit.
//
// The canonical profile vocabulary, derived from the single normative source:
//   {registry}
//
// The website carries its own copy because its Docker build context is `website/` alone and does not
// contain `contracts/`. It is derived, not authored: `make profile-vocabulary-check` compares it
// byte-for-byte against a fresh generation.
//
// A profile is a technical capability an implementation demonstrates. It is never a certification
// state, an operational status, a regulatory permission or a production approval, and a profile NAME
// must never encode one — see docs/governance/certification-boundary.md.

export type CanonicalProfile = {{
  /** The profile identifier. A machine token: never translated. */
  level: string;
  /** The canonical name, from the normative registry. Never translated, never localised. */
  name: string;
}};

export const CANONICAL_PROFILES: readonly CanonicalProfile[] = [
'''

TS_FOOTER = '''] as const;

/** The canonical name for a profile identifier, or `undefined` if it is not a profile.
 *
 * Unknown identifiers do not resolve by guesswork: an alias is valid only if the registry registers
 * one, and the registry registers none. */
export function canonicalProfileName(level: string): string | undefined {
  return CANONICAL_PROFILES.find((p) => p.level === level)?.name;
}
'''


def rust_str(s):
    if '"' in s or '\\' in s or '\n' in s:
        raise SystemExit('profile name is not a plain string literal: %r' % s)
    return '"%s"' % s


def main():
    reg = json.load(open(os.path.join(ROOT, REGISTRY), encoding='utf-8'))
    profiles = reg['profiles']
    if not profiles:
        raise SystemExit('registry declares no profiles')

    rows = []
    seen = set()
    for p in profiles:
        level, name = p['level'], p['name']
        if level in seen:
            raise SystemExit('duplicate profile level in registry: %s' % level)
        seen.add(level)
        rows.append('    CanonicalProfile { level: %s, name: %s },\n'
                    % (rust_str(level), rust_str(name)))

    out = HEADER.format(registry=REGISTRY, count=len(rows)) + ''.join(rows) + FOOTER

    kb_out = KB_HEADER.format(registry=REGISTRY, count=len(rows)) + ''.join(rows) + KB_FOOTER

    ts_rows = ['  { level: %s, name: %s },\n' % (rust_str(p['level']), rust_str(p['name']))
               for p in profiles]
    ts_out = TS_HEADER.format(registry=REGISTRY) + ''.join(ts_rows) + TS_FOOTER

    if len(sys.argv) > 1 and sys.argv[1] == '--stdout':
        sys.stdout.write(out)
        return
    if len(sys.argv) > 1 and sys.argv[1] == '--stdout-ts':
        sys.stdout.write(ts_out)
        return
    if len(sys.argv) > 1 and sys.argv[1] == '--stdout-kb':
        sys.stdout.write(kb_out)
        return
    with open(os.path.join(ROOT, TARGET), 'w', encoding='utf-8') as fh:
        fh.write(out)
    with open(os.path.join(ROOT, TS_TARGET), 'w', encoding='utf-8') as fh:
        fh.write(ts_out)
    with open(os.path.join(ROOT, KB_TARGET), 'w', encoding='utf-8') as fh:
        fh.write(kb_out)
    print('  wrote %s' % TARGET)
    print('  wrote %s' % KB_TARGET)
    print('  wrote %s  (%d profiles from %s)' % (TS_TARGET, len(rows), REGISTRY))


if __name__ == '__main__':
    main()
